/**
 * Upgrade AI/BI Genie Spaces Explanations — 26 questions
 */
const fs = require('fs');

const upgrades = {
  "db-da-88": `✅ CORRECT (A): The correct workflow is Configure → Context → SQL Queries tab. This is where analysts add sample questions alongside their matching SQL. Genie uses these as few-shot examples to understand the expected query patterns and business logic.\n\n❌ Why others are wrong:\n• (B) Separate notebooks: Genie doesn't integrate with notebooks via workspace object references. Sample queries are provided directly in the Genie space configuration, not through linked notebooks.\n• (C) Description field: The Description field is for a brief text summary of the space's purpose, not for sample questions. Genie does NOT parse the Description field for query examples.\n• (D) Upload spreadsheet: Genie does not support spreadsheet uploads for training. All configuration is done through the built-in UI — SQL Queries tab and Instructions section.\n\n🔑 EXAM TIP: Genie configuration hierarchy:\n1. Trusted Assets (tables) → what data Genie can access\n2. Instructions → business rules and terminology definitions\n3. Sample Questions + SQL → few-shot examples for accurate query generation\n4. Column/Table comments → semantic metadata from Unity Catalog`,

  "db-da-94": `✅ CORRECT (C): To mark a table as deprecated in Unity Catalog, use ALTER TABLE SET TAGS with a key-value pair that follows the certification convention. The correct pattern is setting a tag like 'certified' = 'deprecated' or using system tags to communicate certification status across the organization.\n\n❌ Why others are wrong:\n• (A) Likely uses incorrect tag syntax or a non-standard key that doesn't follow Unity Catalog conventions.\n• (B) May use COMMENT instead of TAGS — comments are descriptive text, not structured metadata that tools can programmatically query.\n• (D) May use UPDATE or ALTER with incorrect syntax — Unity Catalog uses SET TAGS for structured key-value metadata.\n\n🔑 EXAM TIP: Unity Catalog metadata mechanisms:\n• TAGS (SET TAGS): Structured key-value pairs. Used for certification, classification, and governance. Queryable by tools and AI (Genie).\n• COMMENTS (COMMENT ON): Free-text descriptions. Used for documentation and semantic understanding.\n• Both are important for data governance but serve different purposes.`,

  "db-da-101": `✅ CORRECT (D): Lakeflow Spark Declarative Pipelines (formerly DLT — Delta Live Tables) with Auto Loader is the ideal solution. Declarative Pipelines support multiple languages (SQL, Python), define transformation logic declaratively, and Auto Loader automatically handles schema evolution as new data arrives — detecting new columns and adapting the schema without manual intervention.\n\n❌ Why others are wrong:\n• (A) Separate Delta tables with fixed schemas: "Fixed schemas" directly contradicts the requirement to "automatically handle schema changes." No automation for ingestion or scheduling.\n• (B) Unity Catalog with manual ETL + cron: "Manual" and "cron-based" don't meet the automation requirement. Cron scheduling lacks the orchestration features of Databricks Workflows.\n• (C) Workflows with Spark notebooks + manual schema: "Manual schema management" fails the automatic schema evolution requirement. Auto Loader handles this natively.\n\n🔑 EXAM TIP: Auto Loader key features:\n• Automatically detects and ingests new files from cloud storage\n• Schema evolution: automatically adapts to new columns (schemaEvolution mode)\n• Schema inference: automatically detects data types\n• Exactly-once processing guarantees via checkpointing\n• Works with CSV, JSON, Parquet, Avro, ORC, and more`,

  "db-da-109": `✅ CORRECT (A): Defining Primary Key on customers.id and Foreign Key on orders.cust_id provides explicit relationship metadata that Genie reads to correctly generate JOIN statements. Even though PK/FK constraints are NOT enforced in Databricks (they're informational only), Genie uses this metadata to understand the data model.\n\n❌ Why others are wrong:\n• (B) Materialized view with pre-join: This over-engineers the solution. It denormalizes data, increases storage, and doesn't teach Genie how to handle other join patterns.\n• (C) System Instruction: Instructions help with business terms but are fragile for join logic. PK/FK metadata is the STRUCTURAL solution — it tells Genie exactly how tables relate.\n• (D) Liquid Clustering: Liquid Clustering optimizes file layout for query performance (data skipping). It has ZERO impact on join logic or Genie's understanding of table relationships.\n\n🔑 EXAM TIP: PK/FK in Databricks:\n• NOT enforced (no constraint validation on INSERT/UPDATE)\n• ARE informational — used by query optimizers and AI tools (Genie)\n• Syntax: ALTER TABLE customers ADD CONSTRAINT pk_cust PRIMARY KEY (id);\n         ALTER TABLE orders ADD CONSTRAINT fk_cust FOREIGN KEY (cust_id) REFERENCES customers(id);\n• Critical for Genie accuracy on multi-table spaces`,

  "db-da-117": `✅ CORRECT (B): Trusted Assets guide Genie's AI to prioritize SPECIFIC tables when generating SQL answers. They act as a curated allow-list that tells Genie: "Use THESE tables for answering questions." This prevents the AI from picking up irrelevant, temporary, or deprecated tables from the catalog, reducing hallucinations and incorrect results.\n\n❌ Why others are wrong:\n• (A) Encrypts the data: Trusted Assets have nothing to do with encryption. Data encryption is handled at the storage layer (cloud provider) and Unity Catalog access controls.\n• (C) Caches assets for performance: Trusted Assets don't affect caching or query performance. They influence query GENERATION (which SQL Genie writes), not query EXECUTION speed.\n• (D) Prevents querying other tables: Trusted Assets GUIDE Genie's preference but don't technically block access to other tables. Users can still ask about any table they have permissions on.\n\n🔑 EXAM TIP: Trusted Assets serve two purposes:\n1. Table/data selection: Tells Genie which tables to prioritize\n2. Verified SQL templates: Pre-written queries that Genie uses as templates for similar questions\nBoth reduce AI hallucinations and improve accuracy.`,

  "db-da-122": `✅ CORRECT (B): Draft Mode is the analyst's STAGING environment for testing, validating, and curating Genie responses before end-users interact with them. In Draft Mode, the analyst can verify that instructions work correctly, test sample questions, and refine the space. Released (Published) Mode exposes the curated space to end-users.\n\n❌ Why others are wrong:\n• (A) Smaller cluster for costs: Draft Mode doesn't use different compute. Both modes use the same SQL Warehouse. The difference is about VISIBILITY, not compute.\n• (C) Released Mode = public internet: Released Mode makes the space available to authorized workspace users, NOT to the public internet. Access still requires proper permissions.\n• (D) No difference: There IS a clear difference — Draft Mode is for testing/curation, Released Mode is for user consumption.\n\n🔑 EXAM TIP: Genie Space lifecycle:\n1. Create space (Draft Mode)\n2. Configure: add tables, instructions, sample questions\n3. Test: verify accuracy in Draft Mode\n4. Publish: Release to users\n5. Iterate: Review feedback, update in Draft, re-publish`,

  "db-da-150": `✅ CORRECT (B): Databricks recommends including only necessary tables (ideally 5 or fewer) and limiting columns to what's relevant. Too many tables and columns create "noise" that confuses Genie's SQL generation — it may pick wrong tables, create incorrect joins, or select irrelevant columns.\n\n❌ Why others are wrong:\n• (A) As many tables as possible: MORE tables = MORE confusion for the LLM. Each additional table increases the chance of incorrect table selection and joins.\n• (C) At least 20 tables: Far too many. This would degrade accuracy significantly.\n• (D) No impact on accuracy: FALSE. The number of tables directly impacts Genie's ability to select the right data source.\n• (E) Only one table: While very focused, this is too restrictive. Genie can handle multiple well-documented tables for cross-table queries.\n\n🔑 EXAM TIP: Genie accuracy formula:\n• Fewer tables (≤5) + fewer columns + rich metadata = HIGH accuracy\n• Many tables + many columns + poor metadata = LOW accuracy\n• Always include COMMENT descriptions on tables AND columns in Unity Catalog`,

  "db-da-185": `✅ CORRECT (A): Share the Genie space with embedded credentials and assign stakeholders as account users with published dashboard access. This provides interaction capability (asking questions) without workspace membership. The embedded credentials ensure queries run with proper authentication, while account-level user status isolates them from the underlying workspace.\n\n❌ Why others are wrong:\n• (B) Export to CSV: Loses all interactivity. Stakeholders need to ASK QUESTIONS (natural language), not just view static data.\n• (C) Workspace accounts + SQL access entitlement: Creates workspace members — directly violates the requirement of "no access to the underlying Databricks workspace."\n• (D) Workspace membership with Consumer access: Any form of workspace membership violates the isolation requirement.\n\n🔑 EXAM TIP: Sharing with external users:\n• Account users ≠ Workspace members\n• Account users can access published dashboards/Genie spaces without workspace access\n• Embedded credentials control what data is accessible\n• This is the secure, scalable approach for external stakeholders`,

  "db-da-218": `✅ CORRECT (B): Update instructions and add example SQL queries. This is the proven improvement method — it gives Genie explicit guidance on how to generate correct responses for the specific question patterns that were flagged as inaccurate.\n\n❌ Why others are wrong:\n• (A) Add more tables and columns: MORE data = MORE noise = WORSE accuracy. Increasing data volume does NOT improve Genie's understanding — it confuses it.\n• (C) Turn off feedback: Feedback (thumbs up/down) is the PRIMARY signal for identifying accuracy problems. Disabling it eliminates the improvement feedback loop.\n• (D) Delete flagged responses: Deleting history doesn't change Genie's behavior. Genie generates SQL from instructions and metadata, not from conversation history.\n\n🔑 EXAM TIP: Genie accuracy improvement workflow:\n1. Review History tab for flagged (thumbs-down) responses\n2. Identify patterns in failed queries\n3. Add/update Instructions with business rules\n4. Create Sample Questions with correct SQL\n5. Create Trusted Assets for critical, recurring queries\n6. Repeat iteratively`,

  "db-da-220": `✅ CORRECT (B): Marking verified queries as Trusted Assets signals to both Genie and users that these queries are "gold standard" — pre-validated for correctness. Genie prioritizes Trusted Assets when matching similar questions, ensuring consistent, accurate results.\n\n❌ Why others are wrong:\n• (A) Disable domain instructions: Instructions provide critical business context. Removing them REDUCES accuracy, not increases trust.\n• (C) Enable automatic generation without review: Removes human oversight and quality control. Unreviewed auto-generated SQL can be inaccurate.\n• (D) Allow users to edit datasets: Editing source data introduces data quality risks and governance violations. Users should consume data, not modify it.\n\n🔑 EXAM TIP: Trusted Assets vs. Sample Questions:\n• Trusted Assets = VERIFIED, production-ready SQL that Genie uses AS-IS for matching questions\n• Sample Questions = Training examples that GUIDE Genie's SQL generation\n• Both improve accuracy, but Trusted Assets provide higher confidence for critical metrics`,

  "db-da-282": `✅ CORRECT (B): Add only the necessary tables and columns and ensure all metadata in Unity Catalog is well-annotated. This combines FOCUS (fewer, relevant tables) with CONTEXT (rich descriptions) — the two primary drivers of Genie accuracy.\n\n❌ Why others are wrong:\n• (A) Include ALL available tables: Adding irrelevant tables creates noise that degrades SQL generation quality. The LLM may select wrong tables or create incorrect joins.\n• (C) Remove PK/FK relationships: Removing relationships BREAKS Genie's understanding of how tables relate. PK/FK metadata is critical for correct join generation.\n• (D) Default/generic templates: Generic instructions lack the specific business context that makes Genie accurate. Custom metadata tailored to actual schemas is always better.\n\n🔑 EXAM TIP: The three pillars of Genie accuracy:\n1. FOCUS: Include only necessary tables and columns (≤5 tables)\n2. METADATA: Rich descriptions on tables AND columns in Unity Catalog\n3. EXAMPLES: Sample Questions and Trusted Assets with verified SQL`,

  "db-da-296": `✅ CORRECT (B): Trusted Assets are pre-written, verified SQL queries that Genie uses instead of generating new SQL for matching questions. For sensitive executive reports, Trusted Assets ensure 100% accuracy — Genie uses the exact vetted SQL rather than attempting to generate potentially incorrect queries.\n\n❌ Why others are wrong:\n• (A) Priority Execution: Not a real Genie feature. There is no 'Priority Execution' setting.\n• (C) EXEC_PRIORITY tags: Not a standard Unity Catalog tag. Tags like 'certified' exist, but 'EXEC_PRIORITY' is not a recognized system tag.\n• (D) Auto-trust admin queries: Genie does NOT automatically trust queries based on who wrote them. Trust is explicitly configured through Trusted Assets.\n\n🔑 EXAM TIP: When to use Trusted Assets:\n• Sensitive executive reports where accuracy is critical\n• Complex queries with specific business logic (fiscal quarters, custom metrics)\n• Recurring questions that users ask frequently\n• Queries involving non-obvious join patterns or aggregations`,

  "db-da-297": `✅ CORRECT (B): Adding clear descriptions and synonyms in Unity Catalog metadata (COMMENT ON COLUMN) is the most effective and PERSISTENT solution. Genie reads column comments to understand business semantics. For example: COMMENT ON COLUMN sales.revenue IS 'Total gross revenue from sales transactions in USD. Not to be confused with profit or net income.'\n\n❌ Why others are wrong:\n• (A) Rename columns: Renaming source columns is a schema change that affects ALL downstream consumers — dashboards, notebooks, ETL pipelines. It's invasive and risky.\n• (C) Clear cache and rephrase: Genie doesn't have a user-facing cache that stores learned behaviors. The problem is semantic, not caching-related.\n• (D) Sample Questions: While helpful, Sample Questions only cover specific question patterns. Metadata fixes the ROOT cause — Genie's understanding of what each column means.\n\n🔑 EXAM TIP: The metadata hierarchy for Genie:\n1. Column COMMENTS → most persistent, affects ALL queries\n2. Table COMMENTS → provides context for table selection\n3. Instructions → defines business rules and terminology\n4. Sample Questions → covers specific query patterns\n5. Trusted Assets → provides exact SQL for critical questions`,

  "db-da-298": `✅ CORRECT (B): Genie is a text-to-SQL interface. For complex operations like many-to-many pivots, multi-step window functions, or specialized cross-table correlations, it requires detailed guidance through Instructions, Sample Questions, or Trusted Assets. Standard SQL Dashboards use analyst-written SQL, which can handle any complexity directly.\n\n❌ Why others are wrong:\n• (A) Can't share with 'Can View' users: FALSE. Genie spaces support 'Can Use' permission for consumption, similar to 'Can View.'\n• (C) Can't connect to Unity Catalog: FALSE. Genie is BUILT ON Unity Catalog — it's a core dependency.\n• (D) No visualization support: FALSE. Genie generates visualizations alongside SQL results (charts, tables).\n\n🔑 EXAM TIP: Genie vs. SQL Dashboards:\n• Genie: Natural language → AI-generated SQL. Best for ad-hoc exploration, simple queries.\n• SQL Dashboards: Analyst-written SQL. Best for predefined, complex, production reporting.\n• Genie limitation: Struggles with complex joins, pivots, and multi-step logic without guidance.`,

  "db-da-299": `✅ CORRECT (B): 'Can Use' is the appropriate permission level for consumers who need to ASK QUESTIONS but not modify the space configuration. It allows interaction (querying, viewing results) without access to add tables, create Trusted Assets, or change instructions.\n\n❌ Why others are wrong:\n• (A) Can Manage: Over-privileged. 'Can Manage' allows full control including adding/removing tables, changing instructions, and managing permissions. Not appropriate for a read-only manager.\n• (C) Can Edit: Also over-privileged. 'Can Edit' allows modifying tables and Trusted Assets — more than what a consumer needs.\n• (D) All workspace users have access: FALSE. Genie spaces have their own permission model. Access is NOT automatic for workspace users.\n\n🔑 EXAM TIP: Genie Space permissions:\n• Owner: Full control (create, configure, share, delete)\n• Can Edit: Modify configuration (tables, Trusted Assets, instructions)\n• Can Use: Ask questions and view results only\n• Default: NO access (must be explicitly granted)`,

  "db-da-300": `✅ CORRECT (B): Review the generated SQL, correct it if needed, and add it as a Sample Question or Trusted Asset. This is the iterative improvement workflow — identify failures, fix them, and encode the correct SQL so Genie learns from the corrections.\n\n❌ Why others are wrong:\n• (A) Delete failed questions: Deleting history doesn't fix Genie's behavior. The underlying problem (incorrect SQL generation) remains unchanged.\n• (C) Restart SQL Warehouse: The warehouse executes queries — it doesn't affect Genie's SQL generation logic. Restarting compute won't fix accuracy.\n• (D) Tell users questions are out-of-scope: Dismissive approach that doesn't improve the space. The analyst should ADDRESS the failure, not blame the users.\n\n🔑 EXAM TIP: Genie improvement workflow:\n1. Check History tab → find thumbs-down responses\n2. Review the SQL Genie generated\n3. Write or correct the SQL\n4. Add as Sample Question (for guidance) or Trusted Asset (for exact reuse)\n5. Test the improvement in Draft Mode\n6. Re-publish`,

  "db-da-321": `✅ CORRECT (E — Both B and D): The most effective approach combines BOTH:\n• (B) Column/table descriptions in Unity Catalog bridge the gap between technical column names and business terminology. 'total_amount_usd represents the revenue from each transaction' teaches Genie the semantic mapping.\n• (D) Trusted Assets with sample SQL provide concrete examples that demonstrate correct column usage, so Genie can replicate the pattern.\n\n❌ Why others alone are insufficient:\n• (A) Rename column: Invasive schema change affecting all downstream consumers.\n• (B) alone: Descriptions help but may not cover all query variations.\n• (C) Create a view with alias: Adds an extra layer but doesn't teach Genie the underlying business vocabulary.\n• (D) alone: Trusted Assets cover specific queries but don't teach Genie the general semantic meaning.\n\n🔑 EXAM TIP: Best practice for Genie vocabulary mapping:\n• Unity Catalog COMMENTS = teach the semantic meaning (persistent, universal)\n• Trusted Assets = demonstrate correct usage (specific, template-based)\n• Together: maximum coverage for vocabulary mismatches`,

  "db-da-322": `✅ CORRECT (B): Document PK/FK in Unity Catalog (ALTER TABLE ADD CONSTRAINT or COMMENT descriptions) AND create Trusted Assets with verified join patterns. PK/FK metadata tells Genie the proper cardinality and direction of joins. Trusted Assets provide concrete examples of correct multi-table queries.\n\n❌ Why others are wrong:\n• (A) Remove all but one table: Eliminates Genie's multi-table capability entirely. Overly restrictive.\n• (C) 'Strict join mode': NOT a real feature. There is no such setting in Genie configuration.\n• (D) Users specify join conditions: Unrealistic. Business users asking natural language questions shouldn't need to know SQL join syntax.\n• (E) Pre-joined flat tables: Denormalization creates data redundancy, increases storage, and loses the flexibility of normalized queries.\n\n🔑 EXAM TIP: Preventing incorrect Genie joins:\n1. Define PK/FK constraints in Unity Catalog (even though not enforced)\n2. Add table comments describing relationships\n3. Create Trusted Assets with correct join patterns\n4. Keep the number of tables minimal (≤5)`,

  "db-da-323": `✅ CORRECT (B): A Trusted Asset is a vetted, pre-written SQL query that Genie uses as a reference template. When a user asks a question similar to a Trusted Asset, Genie adapts the verified query instead of generating SQL from scratch — ensuring accuracy and consistency for recurring, critical question patterns.\n\n❌ Why others are wrong:\n• (A) Certified Delta table: Describes a data certification concept, not a Genie-specific feature. Tables CAN be certified, but that's Unity Catalog governance, not Genie Trusted Assets.\n• (C) ML model: Genie uses a general-purpose LLM, not custom fine-tuned models. Trusted Assets guide the LLM without retraining it.\n• (D) Read-only dashboard widget: Dashboard widgets are visualization components, not Genie features.\n• (E) User role with elevated permissions: Trusted Assets are SQL queries, not user roles.\n\n🔑 EXAM TIP: Trusted Asset definition:\n• WHAT: A pre-written, verified SQL query\n• WHO creates them: Analysts/editors of the Genie space\n• HOW Genie uses them: As exact templates for matching questions\n• WHY: 100% accuracy for critical queries (no AI generation risk)`,

  "db-da-324": `✅ CORRECT (B): Genie INHERITS Unity Catalog permissions. When a user questions Genie, the generated SQL runs under THEIR identity. If they lack SELECT permission on a table or column, the query fails with a permission error. The analyst should ensure the finance team DOES NOT have access to the salary table.\n\n❌ Why others are wrong:\n• (A) Separate permission system: FALSE. Genie does NOT have its own data access permissions. It relies 100% on Unity Catalog's permission model.\n• (C) AI-based auto-masking: FALSE. Genie does NOT automatically detect or mask sensitive data. Column masking must be configured explicitly in Unity Catalog.\n• (D) Full access to all tables: FALSE. Access is governed by Unity Catalog permissions, not by Genie space membership.\n• (E) Service accounts only: FALSE. Genie runs queries under the user's identity (not a service account), unless the space is configured with embedded credentials.\n\n🔑 EXAM TIP: Genie + Security:\n• Data access: Governed by Unity Catalog (SELECT, USAGE)\n• Space access: Governed by Genie permissions (Can Use, Can Edit)\n• Row-level security: Use Row Filters in Unity Catalog\n• Column masking: Use Column Masks in Unity Catalog\n• Genie respects ALL UC security policies`,

  "db-da-325": `✅ CORRECT (B): The recommended workflow is: (1) Review flagged responses in conversation history, (2) Identify patterns in misunderstood queries, (3) Add Sample Questions with correct SQL, (4) Create Trusted Assets for recurring question types. This is an iterative, data-driven improvement process.\n\n❌ Why others are wrong:\n• (A) Delete and recreate: Destroys all configuration, instructions, and Trusted Assets. Starting over is wasteful and loses accumulated improvements.\n• (C) Retrain/fine-tune LLM: Genie uses a managed LLM that CANNOT be fine-tuned by users. Improvement is done through configuration (instructions, examples, metadata), not model training.\n• (D) Reduce tables blindly: While fewer tables CAN help, blindly removing tables without analyzing the failures doesn't address the root cause.\n• (E) Larger SQL Warehouse: Warehouse size affects query EXECUTION speed, not SQL GENERATION accuracy. Genie's accuracy is about metadata and examples, not compute power.\n\n🔑 EXAM TIP: Genie CANNOT be fine-tuned. You improve it through:\n1. Better metadata (comments, PK/FK)\n2. Better instructions (business rules)\n3. Sample Questions (few-shot examples)\n4. Trusted Assets (verified SQL templates)`,

  "db-da-326": `✅ CORRECT (B): The correct sequence:\n1. Create the space\n2. Connect a SQL Warehouse (compute)\n3. Add Unity Catalog tables with good descriptions (data + metadata)\n4. Add Sample Questions and Trusted Assets (guidance)\n5. Share with users and iterate based on feedback (deployment + improvement)\n\n❌ Why others are wrong:\n• (A) Missing the critical step of adding descriptions/comments. Also "write and test queries" is vague — the specific features are Sample Questions and Trusted Assets.\n• (C) Upload CSV files: Genie doesn't support CSV uploads. All data must come from Unity Catalog tables.\n• (D) Train the Genie model: Genie's LLM cannot be trained by users. Configuration is through metadata and examples.\n• (E) Dashboards linked to Genie: Genie and Dashboards are separate features. Users interact with Genie directly, not through dashboard intermediaries.\n\n🔑 EXAM TIP: Genie setup checklist:\n☐ Create space + assign SQL Warehouse\n☐ Add Unity Catalog tables (≤5 recommended)\n☐ Verify table/column COMMENTS exist\n☐ Define PK/FK constraints\n☐ Write Instructions (business rules, terminology)\n☐ Add Sample Questions with SQL\n☐ Create Trusted Assets for critical queries\n☐ Test in Draft Mode → Publish → Iterate`,

  "db-da-327": `✅ CORRECT (B): Add detailed column-level COMMENT descriptions in Unity Catalog (e.g., COMMENT ON COLUMN orders.status IS 'Order fulfillment status: pending, shipped, delivered, cancelled') AND create Genie space instructions that define the business terminology. Comments provide persistent, schema-level context; instructions provide space-level disambiguation rules.\n\n❌ Why others are wrong:\n• (A) Rename columns with prefixes: Works but requires schema changes that affect ALL downstream consumers (dashboards, ETL, notebooks).\n• (C) Split into smaller tables: Architectural over-engineering that increases complexity and number of joins.\n• (D) Remove ambiguous columns: Loses data that users need. Removing 'status' from the space means users can't ask about order status at all.\n• (E) Upload glossary PDF: Genie CANNOT read uploaded documents. It only reads Unity Catalog metadata and its own configuration.\n\n🔑 EXAM TIP: Genie reads metadata from:\n✅ Unity Catalog column COMMENTS\n✅ Unity Catalog table COMMENTS\n✅ PK/FK constraint definitions\n✅ Genie space Instructions\n✅ Sample Questions / Trusted Assets\n❌ Does NOT read: uploaded files, PDFs, spreadsheets, or external docs`,

  "db-da-328": `✅ CORRECT (B): Add Genie space Instructions that define ambiguous business terms (e.g., "'top products' means ranked by revenue unless otherwise specified") AND create Sample Questions demonstrating each variation ("Top 5 products by revenue", "Top 5 products by units sold"). This teaches Genie the default interpretation while showing alternative variations.\n\n❌ Why others are wrong:\n• (A) Configure default to revenue: There is no setting to configure default rankings. Genie's behavior is guided through Instructions and examples, not configuration switches.\n• (C) Disable 'top' keyword: Genie doesn't have vocabulary management settings. You can't disable specific words.\n• (D) Separate spaces per metric: Over-engineers the solution and fragments the user experience. Users shouldn't need to know which space to use.\n• (E) Train users to specify: Puts the burden on users. The analyst should configure Genie to handle ambiguity intelligently.\n\n🔑 EXAM TIP: Handling ambiguous business terms:\n1. Define defaults in Instructions: "'top' = by revenue unless specified"\n2. Demonstrate variations in Sample Questions\n3. Add column COMMENTS explaining each metric\n4. Create Trusted Assets for each critical variation`,

  "db-da-329": `✅ CORRECT (B): Genie spaces support role-based access:\n• Owners: Full control (configuration, permissions, deletion)\n• Editors: Modify tables, Trusted Assets, and instructions\n• Can Use: Ask questions and view results (consumer-level)\n\n❌ Why others are wrong:\n• (A) All workspace users have full access: FALSE. Genie spaces require explicit permission grants.\n• (C) Only admins can create/manage: FALSE. Any user with appropriate permissions can create and manage Genie spaces.\n• (D) Public by default: FALSE. Genie spaces are private by default — access must be explicitly granted.\n• (E) Only UC permissions: Genie has its OWN permission model (space-level) in addition to Unity Catalog permissions (data-level).\n\n🔑 EXAM TIP: Two separate permission layers for Genie:\n1. SPACE permissions (Who can interact): Owner, Can Edit, Can Use\n2. DATA permissions (What data they can see): Unity Catalog SELECT, USAGE\nBoth layers must be satisfied for a user to successfully query data through Genie.`,

  "db-da-330": `✅ CORRECT (D — Both B and C): The most robust approach combines:\n• (B) Genie space instructions define the fiscal calendar business rule ("Fiscal Q1 = April to June")\n• (C) A pre-computed fiscal_quarter column with a clear COMMENT makes the fiscal quarter unambiguous — Genie can directly reference it\n\nTogether, Genie can either use the pre-computed column directly OR generate date logic using the instruction-defined rules.\n\n❌ Why others alone are insufficient:\n• (A) SQL Warehouse locale settings: Warehouse locale affects date formatting, NOT fiscal calendar logic. There's no fiscal calendar configuration at the warehouse level.\n• (B) alone: Instructions define the rule, but Genie still needs to generate CASE WHEN logic every time — error-prone for complex date math.\n• (C) alone: A pre-computed column works but without instructions, Genie may not know when to use calendar vs. fiscal quarters.\n• (E) Auto-detect fiscal calendars: FALSE. Genie does NOT automatically detect non-standard fiscal calendars from data patterns.\n\n🔑 EXAM TIP: Custom business logic in Genie:\n• Simple logic → Instructions + Sample Questions are sufficient\n• Complex logic (fiscal calendars, custom metrics) → Pre-compute in source tables + Instructions + Trusted Assets\n• Pre-computed columns reduce Genie's SQL generation burden and increase accuracy`
};

const filePath = './questions_databricks.js';
let content = fs.readFileSync(filePath, 'utf-8');

let upgraded = 0;
let failed = 0;

// Load questions to find real IDs
global.window = { questionsData: [] };
require(filePath);
const questions = window.questionsData;

for (const [id, newExpl] of Object.entries(upgrades)) {
  const escapedExpl = newExpl.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
  
  // Find question by runtime ID to get its prompt text
  const q = questions.find(x => x.id === id);
  if (!q) {
    console.log(`❌ ${id} not found in runtime data!`);
    failed++;
    continue;
  }
  
  // Use a unique text from the question to locate it in the file
  let searchText;
  if (typeof q.prompt === 'string') {
    searchText = q.prompt.substring(0, 60);
  } else if (Array.isArray(q.prompt)) {
    const textBlock = q.prompt.find(p => p.type === 'text');
    searchText = textBlock ? textBlock.content.substring(0, 60) : null;
  }
  
  if (!searchText) {
    console.log(`❌ ${id} has no searchable prompt text`);
    failed++;
    continue;
  }
  
  // Find in file content
  const promptIdx = content.indexOf(searchText);
  if (promptIdx === -1) {
    console.log(`❌ ${id} prompt text not found in file`);
    failed++;
    continue;
  }
  
  // Find the explanation field after the prompt
  const explStart = content.indexOf('"explanation":', promptIdx);
  if (explStart === -1 || explStart - promptIdx > 5000) {
    console.log(`❌ ${id} explanation field not found within range`);
    failed++;
    continue;
  }
  
  const valueStart = content.indexOf('"', explStart + '"explanation":'.length);
  if (valueStart === -1) {
    console.log(`❌ ${id} explanation value start not found`);
    failed++;
    continue;
  }
  
  let valueEnd = valueStart + 1;
  while (valueEnd < content.length) {
    if (content[valueEnd] === '\\') { valueEnd += 2; continue; }
    if (content[valueEnd] === '"') break;
    valueEnd++;
  }
  
  content = content.substring(0, valueStart) + '"' + escapedExpl + '"' + content.substring(valueEnd + 1);
  console.log(`✅ ${id} upgraded`);
  upgraded++;
}

fs.writeFileSync(filePath, content, 'utf-8');
console.log(`\nDone! Upgraded ${upgraded}/${Object.keys(upgrades).length} AI/BI Genie explanations.`);
if (failed > 0) console.log(`Failed: ${failed}`);

// Verify
try {
  delete require.cache[require.resolve(filePath)];
  global.window = { questionsData: [] };
  require(filePath);
  console.log(`✅ File valid! Total questions: ${window.questionsData.length}`);
} catch(e) {
  console.log(`❌ Syntax error: ${e.message.substring(0, 300)}`);
}
