/**
 * Upgrade Managing Data Explanations — 35 questions
 */
const fs = require('fs');

const upgrades = {
  "db-da-11": `✅ CORRECT (C): The table was EXTERNAL (unmanaged). When you DROP TABLE on an external table, Databricks ONLY removes the metadata entry from the metastore. The underlying data files in the external storage location (e.g., S3, ADLS, GCS) remain completely untouched — the analyst will still find the original files.\n\n❌ Why others are wrong:\n• (A) Data larger than 10 GB: Table size has NO impact on DROP TABLE behavior. The behavior depends on the table TYPE (managed vs. external), not its size.\n• (B) Table had no location: All tables have a storage location. Managed tables use the default warehouse location; external tables use a user-specified LOCATION.\n• (D) Data smaller than 10 GB: Same as A — size is irrelevant.\n• (E) Table was managed: If the table were MANAGED, DROP TABLE would delete BOTH metadata AND data files — the opposite of what happened.\n\n🔑 EXAM TIP: DROP TABLE behavior:\n• MANAGED table: Deletes metadata + data files\n• EXTERNAL table: Deletes metadata only; data files remain\nThis is the #1 most tested concept in the Managing Data domain.`,

  "db-da-12": `✅ CORRECT (E): DESCRIBE EXTENDED shows Type = EXTERNAL, confirming this is an unmanaged table. When you DROP TABLE on an external table, the table is removed from the metastore (metadata deleted), but the underlying data files at the external location remain completely untouched. You can still access the data via the direct file path.\n\n❌ Why others are wrong:\n• (A) SELECT from delta path errors: FALSE. The data files still exist at the external location. You CAN still read them directly using the file path.\n• (B) SELECT from table returns rows: FALSE after DROP. The table name no longer exists in the metastore, so this query will fail with "table not found."\n• (C) Files with customers extension deleted: There is no such behavior. The data files are NOT deleted for external tables.\n• (D) Both metadata and data deleted: This describes MANAGED table behavior, not external table behavior.\n\n🔑 EXAM TIP: DESCRIBE EXTENDED output fields:\n• Type: MANAGED or EXTERNAL\n• Location: Physical path of data files\n• Provider: delta, parquet, csv, etc.\n• Owner: User who created the table`,

  "db-da-18": `✅ CORRECT (C): To transfer ownership of a managed table, the current owner edits the Owner field in the table page and selects the new owner's individual account. This is a direct, explicit transfer using Catalog Explorer (or Data Explorer in legacy workspaces).\n\n❌ Why others are wrong:\n• (A) Removing their own account: Removing the owner without specifying a new one creates an ownership gap — this is not valid behavior.\n• (B) Selecting All Users: The question requires transfer to "a single other user," not a group. 'All Users' is a group, not an individual.\n• (D) Selecting Admins group: Same issue — 'Admins' is a group, and the requirement specifies a single user.\n• (E) Removing all access: This removes permissions, not ownership. Ownership is different from access permissions.\n\n🔑 EXAM TIP: Ownership in Unity Catalog:\n• Each object (table, schema, catalog) has ONE owner\n• Owner can be a user OR a group\n• Only the owner or admin can transfer ownership\n• Ownership ≠ Permissions (owner has implicit FULL control)`,

  "db-da-19": `✅ CORRECT (B): DROP TABLE database_name.table_name removes the specified managed table — both its metadata and data files — without affecting other tables in the database. The fully qualified name (database.table) targets exactly one table.\n\n❌ Why others are wrong:\n• (A) DROP DATABASE: This drops the ENTIRE database and all its tables. Violates the requirement to keep other tables intact.\n• (C) DELETE TABLE: Not valid SQL syntax. The command is DROP TABLE, not DELETE TABLE.\n• (D) DELETE TABLE ... FROM: Not valid SQL syntax. DELETE is used for rows (DELETE FROM table WHERE ...), not for dropping tables.\n• (E) DROP TABLE ... FROM: Not valid syntax. The correct syntax uses dot notation (database.table), not FROM keyword.\n\n🔑 EXAM TIP: SQL syntax for table operations:\n• DROP TABLE: Removes table definition + data (managed) or definition only (external)\n• DELETE FROM: Removes ROWS from a table (DML operation)\n• TRUNCATE TABLE: Removes all rows but keeps the table structure\n• DROP DATABASE: Removes entire database and all contained tables`,

  "db-da-54": `✅ CORRECT (D): When no LOCATION is specified during database creation, Hive metastore managed databases default to the warehouse directory path: dbfs:/user/hive/warehouse/<database_name>.db. So for the 'accounting' database, the default location is dbfs:/user/hive/warehouse/accounting.db.\n\n❌ Why others are wrong:\n• (A) dbfs:/accounting/data/accounting.db: This is NOT the default warehouse path. Custom paths must be explicitly specified with LOCATION clause.\n• (B) dbfs:/accounting/data: Missing the .db extension and not the default warehouse path.\n• (C) dbfs:/accounting/data.db: Not the default path. Custom paths require explicit LOCATION specification.\n\n🔑 EXAM TIP: Default storage locations:\n• Hive metastore database: dbfs:/user/hive/warehouse/<db_name>.db\n• Unity Catalog managed tables: Managed by UC (cloud storage path defined by metastore)\n• External tables: Custom path specified with LOCATION clause\n• The default path changes when LOCATION is explicitly provided in CREATE DATABASE`,

  "db-da-56": `✅ CORRECT (B): Managed table data is deleted; external table data remains. This is the fundamental difference between the two table types:\n• MANAGED table: Databricks manages the entire lifecycle — DROP TABLE removes both the metastore entry AND the underlying data files.\n• EXTERNAL (unmanaged) table: Databricks only manages the metadata — DROP TABLE removes the metastore entry but leaves data files unchanged.\n\n❌ Why others are wrong:\n• (A) Both deleted: Only true for managed tables, not external.\n• (C) External deleted, managed untouched: REVERSED. The opposite is true.\n• (D) Both untouched: Only true for external tables, not managed.\n\n🔑 EXAM TIP: This is the MOST IMPORTANT concept in Managing Data:\n• Managed = Databricks controls everything (metadata + data files)\n• External = Databricks controls metadata only; you control data files\n• When in doubt on the exam: "Does DROP TABLE delete the data?" → Check if it's managed or external.`,

  "db-da-58": `✅ CORRECT (A): Catalog Explorer (the UI for browsing Unity Catalog objects) shows detailed metadata for tables, including the Owner field. Navigate to the specific table page to see its owner.\n\n❌ Why others are wrong:\n• (B) Database page in Data Explorer: The database page lists tables but doesn't show individual table ownership details.\n• (C) Schema page in Data Explorer: The schema page shows schema-level properties, not individual table ownership.\n• (D) Table page in SQL Editor: The SQL Editor is for writing and executing queries, not for viewing table metadata properties like ownership.\n\n🔑 EXAM TIP: Where to find table metadata:\n• Catalog Explorer: Owner, Type (managed/external), Location, Tags, Comments, Schema, Permissions\n• SQL commands: DESCRIBE TABLE, DESCRIBE EXTENDED, DESCRIBE DETAIL\n• DESCRIBE EXTENDED: Shows Type, Location, Owner, Storage Properties`,

  "db-da-93": `✅ CORRECT (D): The array_contains() function checks if a specific value exists within an array column. Syntax: WHERE array_contains(tags, 'sql'). This is the correct Databricks SQL function for filtering rows based on array membership.\n\n❌ Why others are wrong:\n• Other options likely use incorrect syntax such as:\n  - tags CONTAINS 'sql' — not valid SQL syntax\n  - tags LIKE '%sql%' — LIKE works on strings, not arrays\n  - 'sql' IN tags — IN is for checking if a value is in a list of literals, not for array column membership\n\n🔑 EXAM TIP: Array functions in Databricks SQL:\n• array_contains(array, value) → checks if value exists in array\n• explode(array) → converts array elements into separate rows\n• array_join(array, delimiter) → concatenates array elements into a string\n• size(array) → returns the number of elements\n• filter(array, x -> condition) → higher-order function to filter array elements`,

  "db-da-95": `✅ CORRECT (A): An effective Genie space requires three core components:\n1. Well-annotated datasets in Unity Catalog (rich metadata = semantic understanding)\n2. Curated sample queries (few-shot examples = correct SQL patterns)\n3. Domain-specific instructions (business rules = context for interpretation)\n\n❌ Why others are wrong:\n• (B) Standalone chatbot via custom APIs: Genie is a BUILT-IN platform feature, not an external chatbot. No custom API integration is needed.\n• (C) Dedicated physical server: Genie runs on SQL Warehouses, which are serverless or shared compute. No dedicated physical hardware is required.\n• (D) External data warehouse replication: Genie queries Unity Catalog directly. Data replication to an external warehouse defeats the purpose of the lakehouse architecture.\n\n🔑 EXAM TIP: Genie's accuracy depends on three layers:\n1. DATA LAYER: Unity Catalog tables with rich metadata (comments, PK/FK)\n2. GUIDANCE LAYER: Instructions, sample questions, Trusted Assets\n3. COMPUTE LAYER: SQL Warehouse for query execution\nAll three must be properly configured for accurate results.`,

  "db-da-96": `✅ CORRECT (A): Unity Catalog manages BOTH structured data (via Tables — Delta, Parquet, CSV) AND unstructured data (via Volumes — images, PDFs, audio, ML models, logs). This provides a UNIFIED governance layer across all data types.\n\n❌ Why others are wrong:\n• (B) Must convert unstructured to Delta: FALSE. Volumes store unstructured data in its original format — no conversion required.\n• (C) Manages structured in tables, unstructured in blob storage: Partially correct but misleading. Volumes ARE the Unity Catalog abstraction over blob storage — you don't manage them separately.\n• (D) Excludes files and non-tabular data: FALSE. Volumes were specifically designed to govern non-tabular files.\n\n🔑 EXAM TIP: Unity Catalog object types:\n• Tables: Structured data (rows/columns) — Delta, Parquet, CSV, JSON\n• Views: Virtual tables defined by SQL queries\n• Volumes: Unstructured/non-tabular data — PDFs, images, audio, ML artifacts\n• Functions: User-defined functions (UDFs)\n• Models: ML models registered for serving`,

  "db-da-126": `✅ CORRECT (B): Unity Catalog Volumes are the correct object for governing non-tabular data like PDFs and images. Volumes provide:\n• Three-level namespace: catalog.schema.volume\n• Access control (GRANT/REVOKE)\n• Lineage tracking\n• Path access: /Volumes/<catalog>/<schema>/<volume>/<path>\n\n❌ Why others are wrong:\n• (A) External Table: Tables are for structured, tabular data (rows and columns). PDFs and images are not tabular.\n• (C) Delta Live Table: DLT defines data transformation pipelines and produces tables — it's not for storing raw files.\n• (D) View: Views are SQL-based virtual tables. They cannot store or govern physical files like PDFs.\n\n🔑 EXAM TIP: When to use Tables vs. Volumes:\n• Tables: Structured data with a defined schema (columns, types)\n• Volumes: Everything else — PDFs, images, audio, video, logs, ML artifacts, configuration files\n• Both are governed by Unity Catalog with access controls and lineage`,

  "db-da-128": `✅ CORRECT (C): system.access.audit contains the audit logs for Unity Catalog operations. It records WHO did WHAT and WHEN — including events like CREATE TABLE, DROP TABLE, SELECT, GRANT, REVOKE, and more. Essential for compliance auditing and incident investigation.\n\n❌ Why others are wrong:\n• (A) system.billing.usage: Tracks compute usage and costs (DBU consumption) — not security events or data operations.\n• (B) system.information_schema.tables: Lists metadata about existing tables (names, schemas, types) — but doesn't track OPERATIONS or history of who did what.\n• (D) system.storage.files: Not a standard Unity Catalog system table. File-level information is tracked in the Delta transaction log, not a separate system table.\n\n🔑 EXAM TIP: Key system tables:\n• system.access.audit → WHO did what (security/compliance auditing)\n• system.billing.usage → HOW MUCH compute was used (cost management)\n• system.information_schema.tables → WHAT tables exist (catalog listing)\n• DESCRIBE HISTORY table_name → WHAT operations were done on a specific table`,

  "db-da-132": `✅ CORRECT (B): Lakehouse Federation creates federated catalogs in Unity Catalog that point to external databases (PostgreSQL, MySQL, Snowflake, SQL Server, BigQuery). This enables direct SQL queries from Databricks without moving or copying data.\n\n❌ Why others are wrong:\n• (A) Delta Sharing: Delta Sharing is for sharing Delta Lake data OUTWARD to external consumers. It doesn't create federated catalogs for querying external databases inward.\n• (C) Auto Loader: Auto Loader ingests files (CSV, JSON, Parquet) from cloud storage INTO Databricks — it doesn't query external databases.\n• (D) COPY INTO: COPY INTO loads data from files INTO a Delta table. It's an ingestion command, not a federation feature.\n• (E) Databricks Connect: Databricks Connect connects external IDEs to Databricks compute — it doesn't create federated database access.\n\n🔑 EXAM TIP: Data access methods:\n• Lakehouse Federation → query external databases in place (no data movement)\n• Delta Sharing → share Delta data with external organizations\n• Auto Loader → ingest files from cloud storage\n• COPY INTO → batch load files into Delta tables\n• Databricks Connect → connect IDEs to Databricks clusters`,

  "db-da-138": `✅ CORRECT (B): Data Lineage in Unity Catalog automatically tracks:\n• Table-level lineage: Which tables feed into which tables\n• Column-level lineage: Which columns are derived from which source columns\n• Query lineage: Which queries transform data between tables\n• Downstream impact: Which reports/dashboards are affected by a table change\n\n❌ Why others are wrong:\n• (A) Data Masking: Data Masking hides sensitive data values (e.g., showing last 4 digits of SSN). It's about data PROTECTION, not tracking data FLOW.\n• (C) Delta Time Travel: Time Travel provides access to historical SNAPSHOTS of a table. It doesn't track cross-table data flow or dependencies.\n• (D) Liquid Clustering: Optimizes file layout for query performance (data skipping). It's about STORAGE performance, not data tracking.\n• (E) Row Filters: Row-level security filters that restrict which rows a user can see. It's about ACCESS control, not lineage tracking.\n\n🔑 EXAM TIP: Lineage use cases:\n• Impact analysis: "If I change this table, what breaks?"\n• Root cause: "Where did this bad data come from?"\n• Compliance: "Prove how this report was generated"\n• All tracked AUTOMATICALLY — no manual configuration needed`,

  "db-da-139": `✅ CORRECT (C): Unity Catalog uses a three-level namespace: Catalog → Schema → Table/View. Objects are referenced as catalog_name.schema_name.table_name. This hierarchy provides organizational isolation and governance across workspaces.\n\n❌ Why others are wrong:\n• (A) Database → Table → Column: This describes a legacy Hive-style hierarchy. Unity Catalog uses Catalog → Schema (replaces Database) → Table.\n• (B) Workspace → Cluster → Query: These are infrastructure concepts, not data governance hierarchy.\n• (D) Account → User → Permission: This describes identity management, not data organization.\n• (E) Storage → Container → File: This describes cloud storage hierarchy, not Unity Catalog's logical namespace.\n\n🔑 EXAM TIP: Unity Catalog three-level namespace:\n• Level 1: CATALOG (organizational boundary — e.g., 'production', 'development')\n• Level 2: SCHEMA (logical grouping — e.g., 'sales', 'hr', 'finance')\n• Level 3: TABLE / VIEW / VOLUME / FUNCTION / MODEL\n• Full path: catalog.schema.table\n• USAGE privilege is required at each level to traverse`,

  "db-da-143": `✅ CORRECT (B): DEEP CLONE creates a complete, INDEPENDENT copy including all data files, metadata, and transaction history. Changes to the clone don't affect the source, and vice versa. This is the proper method for full production backups.\n\n❌ Why others are wrong:\n• (A) SHALLOW CLONE: Only copies metadata and creates references to the source's data files. NOT independent — if the source runs VACUUM, the clone loses access to old files.\n• (C) CTAS (CREATE TABLE AS SELECT): Copies current data but loses transaction history, table properties, and constraints. No historical versions are preserved.\n• (D) COPY INTO: Ingests data FROM files INTO a table. Not designed for table-to-table cloning.\n• (E) INSERT INTO: Appends data but doesn't replicate schema, constraints, or history.\n\n🔑 EXAM TIP: DEEP CLONE vs SHALLOW CLONE:\n• DEEP: Full copy (data + metadata + history) → independent, backup-grade\n• SHALLOW: Metadata only (references source files) → fast, lightweight, testing\n• DEEP is expensive but safe; SHALLOW is cheap but fragile`,

  "db-da-144": `✅ CORRECT (B): SHALLOW CLONE creates a lightweight copy by only copying metadata (schema, partitioning, transaction log) and REFERENCING the source's data files. No data file duplication — this makes it fast and cost-effective for read-only testing or development environments.\n\n❌ Why others are wrong:\n• (A) DEEP CLONE: Full data copy — too expensive and slow for "quick lightweight" testing. Appropriate for backups, not throwaway test copies.\n• (C) CTAS: Creates a full data copy (like DEEP CLONE for data) but loses transaction history and properties.\n• (D) COPY INTO: File-to-table ingestion. Not for table-to-table cloning.\n• (E) INSERT OVERWRITE: Replaces all data in a target table. Not a cloning mechanism.\n\n🔑 EXAM TIP: SHALLOW CLONE caveat:\n• If source table runs VACUUM, referenced files may be deleted\n• Shallow clone becomes broken → queries fail\n• Best for short-lived testing/dev environments\n• NOT suitable for long-term backups\n• Syntax: CREATE TABLE clone_table SHALLOW CLONE source_table`,

  "db-da-146": `✅ CORRECT (B): Default VACUUM retention is 7 days (168 hours). VACUUM permanently deletes unreferenced data files older than this threshold. Once deleted, Time Travel queries to those versions fail.\n\n❌ Why others are wrong:\n• (A) 30 days, archived: No archiving mechanism. Files are permanently DELETED, not archived.\n• (C) 24 hours, recycle bin: No recycle bin in Delta Lake. Deletion is permanent. And default is 7 days, not 24 hours.\n• (D) 90 days, compressed: No compression behavior. VACUUM deletes, not compresses.\n• (E) No default: There IS a default — 7 days (168 hours). Users can override with VACUUM RETAIN <hours> HOURS.\n\n🔑 EXAM TIP: VACUUM facts:\n• Default retention: 7 days (168 hours)\n• Reduces below 7 days requires: SET spark.databricks.delta.retentionDurationCheck.enabled = false\n• VACUUM removes: old data files no longer referenced by the transaction log\n• VACUUM does NOT remove: transaction log entries (those have separate retention)\n• WARNING: VACUUM + short retention = loss of Time Travel capability`,

  "db-da-149": `✅ CORRECT (B): Unity Catalog Volumes provide governance over non-tabular data: images, PDFs, logs, JSON files, ML artifacts, audio, video, and more. They follow the three-level namespace (catalog.schema.volume) and files are accessed via /Volumes/<catalog>/<schema>/<volume>/<path>.\n\n❌ Why others are wrong:\n• (A) Only structured tabular data: Tables handle structured data. Volumes handle everything ELSE.\n• (C) Managing compute clusters: Compute management is done through Workspace settings, not Volumes.\n• (D) Storing SQL query results temporarily: Temporary results are stored in session state, not Volumes.\n• (E) Defining access control policies: Access control policies are defined through GRANT/REVOKE in Unity Catalog, not Volumes.\n\n🔑 EXAM TIP: Volume types:\n• Managed Volume: Unity Catalog manages the storage location and lifecycle\n• External Volume: User specifies the cloud storage location (like external tables)\n• Access: /Volumes/<catalog>/<schema>/<volume>/<path>\n• Governance: Same UC permissions (GRANT/REVOKE) as tables`,

  "db-da-177": `✅ CORRECT (C): Time Travel querying allows you to read a table's historical state without modifying the current data. Use VERSION AS OF or TIMESTAMP AS OF to specify the desired point in time.\n\nSQL Pattern:\nSELECT * FROM table VERSION AS OF 5;\nSELECT * FROM table TIMESTAMP AS OF '2026-04-06T10:00:00';\n\n❌ Why others are wrong:\n• (A) RESTORE command: RESTORE doesn't just READ historical data — it MODIFIES the table by reverting it to a previous version. The analyst needs to COMPARE, not revert.\n• (B) VACUUM retention: VACUUM controls how long historical data files are kept. It doesn't provide a querying mechanism.\n• (D) CLONE with VERSION AS OF: While you CAN clone a specific version, this creates a full table copy — overkill for simply comparing data.\n\n🔑 EXAM TIP: Time Travel methods:\n• READ (non-destructive): SELECT ... VERSION AS OF n; SELECT ... TIMESTAMP AS OF 'date'\n• WRITE (destructive): RESTORE TABLE ... TO VERSION AS OF n\n• Time Travel requires data files to exist (not VACUUMed)\n• Default file retention: 7 days; log retention: 30 days`,

  "db-da-194": `✅ CORRECT (D): DESCRIBE HISTORY table_name queries the Delta Lake transaction log and returns a chronological list of ALL operations: writes, updates, deletes, merges, schema changes, optimize, vacuum — with timestamps, user IDs, and operation details.\n\n❌ Why others are wrong:\n• (A) SELECT logs FROM table_name: Not valid SQL. There is no 'logs' column in tables.\n• (B) SHOW TRANSACTIONS: Not a valid Databricks SQL command.\n• (C) VACUUM: VACUUM removes old files to reclaim storage. It does NOT show operation history.\n\n🔑 EXAM TIP: DESCRIBE HISTORY output columns:\n• version: Version number (0, 1, 2, ...)\n• timestamp: When the operation occurred\n• operation: WRITE, MERGE, DELETE, UPDATE, CREATE TABLE, etc.\n• operationParameters: Details of the operation\n• userName: Who performed the operation\n• Use for: Auditing, debugging, identifying when changes occurred`,

  "db-da-200": `✅ CORRECT (B): ALTER TABLE sales_data SET TAGS ('certified' = 'true') is the correct syntax. Unity Catalog supports custom tags as key-value pairs using the SET TAGS clause. The 'certified' tag makes the table discoverable as a trusted asset across the organization.\n\n❌ Why others are wrong:\n• (A) SET TAGS ('system.Certified'): Syntactically incomplete — tags must be key-value pairs ('key' = 'value'), not single strings.\n• (C) GRANT CERTIFY: There is no CERTIFY privilege in Unity Catalog. GRANT is for access permissions (SELECT, USAGE, ALL PRIVILEGES).\n• (D) UPDATE TABLE ADD COMMENT: Invalid syntax. Comments are set with ALTER TABLE SET COMMENT 'text' or COMMENT ON TABLE.\n\n🔑 EXAM TIP: Unity Catalog metadata methods:\n• TAGS (SET TAGS): Structured key-value pairs for classification and governance\n• COMMENTS (SET COMMENT): Free-text descriptions for documentation\n• Syntax: ALTER TABLE table_name SET TAGS ('key1' = 'value1', 'key2' = 'value2');\n• Remove: ALTER TABLE table_name UNSET TAGS ('key1');`,

  "db-da-207": `✅ CORRECT (D): The time travel query will FAIL because the default data file retention is 7 days, and VACUUM (run weekly) has already removed the 10-day-old data files. Even though the transaction log has a 30-day retention (preserving the VERSION metadata), the actual data files needed to read the historical version have been deleted.\n\n❌ Why others are wrong:\n• (A) Automatic backup: FALSE. Delta Lake does NOT automatically back up data files. VACUUM is a destructive, permanent deletion operation.\n• (B) 30-day log retention sufficient: The 30-day retention applies to the TRANSACTION LOG (metadata), not the data files. You can see that version 10-days-ago EXISTS in the log, but you can't READ it because the data files are gone.\n• (C) Max 7 versions with reset: FALSE. Delta Lake doesn't have a maximum version count, and VACUUM doesn't reset version numbering.\n\n🔑 EXAM TIP: Two separate retention periods:\n• Transaction LOG retention: 30 days (metadata about versions)\n• Data FILE retention: 7 days (actual data files for Time Travel)\n• VACUUM deletes data FILES beyond the file retention period\n• Result: After VACUUM, you can see old versions in DESCRIBE HISTORY but CANNOT query them`,

  "db-da-211": `✅ CORRECT (B): Creating a MANAGED table (CREATE TABLE catalog.schema.table_name) places the data under Unity Catalog's full lifecycle management. Benefits:\n• Automatic storage location management\n• Predictive Optimization (automated OPTIMIZE and VACUUM)\n• Full governance (access control, lineage, auditing)\n\n❌ Why others are wrong:\n• (A) Foreign table: Foreign tables (via Lakehouse Federation) keep data OUTSIDE Unity Catalog's lifecycle management. No automatic optimization.\n• (C) Temporary table: Session-scoped. Disappears when the session ends. Not usable for production workloads.\n• (D) External table: While governed by UC permissions, external tables don't benefit from UC-managed storage lifecycle or Predictive Optimization.\n\n🔑 EXAM TIP: Managed vs. External vs. Foreign:\n• Managed: UC manages storage + lifecycle + full optimization → best for production\n• External: UC manages metadata only, user manages storage → for existing data locations\n• Foreign: UC provides read-only access to external databases → no data copying\n• Predictive Optimization ONLY works with managed tables`,

  "db-da-213": `✅ CORRECT (D): Delta Sharing is the correct solution. It provides secure, read-only data sharing ACROSS organizations without requiring the recipient to have a Databricks account or workspace. The analyst creates a Share, adds specific tables, defines a recipient, and the recipient's admin grants access to their users.\n\n❌ Why others are wrong:\n• (A) Add emails to workspace: Gives too much access — workspace membership exposes other resources beyond the shared dataset.\n• (B) COPY INTO + GRANT SELECT: COPY INTO creates a local copy (data duplication). GRANT SELECT only works within the same Unity Catalog ecosystem — external institutions aren't part of it.\n• (C) GRANT SELECT: Only works for principals within the same Unity Catalog metastore. External organizations are outside the UC boundary.\n\n🔑 EXAM TIP: Delta Sharing key facts:\n• Open protocol for secure cross-organization data sharing\n• Recipients don't need Databricks (can use Spark, pandas, Power BI)\n• Read-only access (recipients can't modify source data)\n• Fine-grained: share specific tables, not entire catalogs\n• Audit trail maintained in Unity Catalog`,

  "db-da-216": `✅ CORRECT (C): REVOKE USAGE ON CATALOG 'finance_catalog' FROM 'developers' is the correct syntax. REVOKE removes previously granted privileges. USAGE is the required privilege for accessing a catalog — without it, the group cannot traverse into schemas or tables within that catalog.\n\n❌ Why others are wrong:\n• (A) GRANT USAGE TO 'finance': This GRANTS access to the finance group — it doesn't remove the developers' access.\n• (B) ALTER CATALOG DROP PERMISSIONS: Invalid syntax. Unity Catalog uses REVOKE for removing privileges, not ALTER...DROP PERMISSIONS.\n• (D) REVOKE USE: 'USE' is not a valid Unity Catalog privilege. The correct privilege name is 'USAGE'.\n\n🔑 EXAM TIP: Unity Catalog privilege model:\n• USAGE: Required to traverse the hierarchy (catalog → schema → table)\n• SELECT: Required to query table data\n• MODIFY: Required to write/update data\n• ALL PRIVILEGES: Grants all applicable privileges\n• Syntax: GRANT/REVOKE <privilege> ON <object_type> <name> TO/FROM <principal>`,

  "db-da-239": `✅ CORRECT (A): Lakehouse Federation creates a foreign catalog for MySQL, enabling a direct SQL JOIN between the Delta table and the MySQL table within Databricks. This maintains governance (Unity Catalog lineage and permissions) and minimizes data movement.\n\n❌ Why others are wrong:\n• (B) Python script outside Databricks: Loses all governance, lineage, and auditing. Processing outside the platform violates security and compliance requirements.\n• (C) Full ingestion into Delta: Requires ETL pipeline, storage costs, and data synchronization. More effort than needed for a single report.\n• (D) Temp view via JDBC: While functionally possible, temporary views don't persist across sessions and aren't governed by Unity Catalog permissions or lineage tracking like federated catalogs.\n\n🔑 EXAM TIP: Lakehouse Federation vs. alternatives:\n• Federation: Query in place, no data movement, full UC governance\n• JDBC temp views: Query in place, session-scoped, no governance\n• Full ETL: Data copied, persistent, but requires pipeline maintenance\n• Use Federation when: governance is required AND data shouldn't move`,

  "db-da-240": `✅ CORRECT (A): CREATE TABLE ... USING PARQUET LOCATION 's3://...' is the correct syntax. The LOCATION clause tells Databricks to treat this as an external table pointing to existing Parquet files at the specified path. The USING clause specifies the file format.\n\n❌ Why others are wrong:\n• (B) CREATE EXTERNAL TABLE ... FROM: 'FROM' is not valid syntax for table creation. The correct keyword is LOCATION.\n• (C) EXPORT TABLE ... TO: EXPORT creates files FROM a table, not the reverse.\n• (D) IMPORT TABLE ... FROM: IMPORT is not a standard Databricks SQL command for table creation.\n\n🔑 EXAM TIP: External table creation patterns:\n• CREATE TABLE t USING PARQUET LOCATION 's3://path' → external table pointing to Parquet\n• CREATE TABLE t USING CSV LOCATION 'path' → external table pointing to CSV\n• CREATE TABLE t LOCATION 'path' → defaults to Delta format\n• The LOCATION clause is what makes a table EXTERNAL\n• Without LOCATION, the table is MANAGED (UC or Hive controls storage)`,

  "db-da-358": `✅ CORRECT (B): RESTORE TABLE ... TO VERSION AS OF reverts the entire table to a previous version by updating the transaction log pointer. This is the fastest recovery mechanism because it doesn't copy or rewrite data — it simply changes which version of the table is "current." The pre-corruption files are still available within the retention period.\n\n❌ Why others are wrong:\n• (A) DELETE WHERE last_modified: This tries to filter by an assumed column, but corrupted records may retain their original timestamps. Also, DELETE creates a new version — it doesn't "undo" the corruption.\n• (C) VACUUM: VACUUM removes old files. Running it BEFORE restore could DELETE the pre-corruption files needed for recovery. NEVER run VACUUM during recovery.\n• (D) Cloud backup restore: Slow, requires admin intervention, and may not capture the exact pre-corruption state.\n• (E) OPTIMIZE: OPTIMIZE compacts files for performance. It does NOT fix data content — corrupted data remains corrupted.\n\n🔑 EXAM TIP: Recovery workflow:\n1. DESCRIBE HISTORY table_name → find the version BEFORE corruption\n2. RESTORE TABLE table_name TO VERSION AS OF <version>\n3. Verify recovery: SELECT * FROM table_name\n4. Do NOT run VACUUM before RESTORE`,

  "db-da-359": `✅ CORRECT (A): Schema Enforcement (also called Schema Validation) in Delta Lake rejects writes whose schema doesn't match the target table. The error occurs because the source has a column (loyalty_tier) that doesn't exist in the target table.\n\nResolution options:\n1. ALTER TABLE silver.customers ADD COLUMN loyalty_tier STRING — explicitly add the column\n2. Enable Schema Evolution: SET spark.databricks.delta.schema.autoMerge.enabled = true — automatically adds new columns\n\n❌ Why others are wrong:\n• (B) Data type mismatch: The error message explicitly says "Column not found," not "type mismatch." This is a missing column, not a type issue.\n• (C) INSERT blocked on Silver tables: FALSE. INSERT works on ANY Delta table regardless of the medallion layer.\n• (D) Different catalogs: Cross-catalog INSERT is supported as long as the user has proper permissions.\n• (E) Only applies to Parquet: FALSE. Schema Enforcement is a DELTA LAKE feature — it applies to all Delta tables.\n\n🔑 EXAM TIP: Schema Enforcement vs. Evolution:\n• Enforcement (default ON): REJECTS writes with mismatched schemas\n• Evolution (default OFF): ACCEPTS writes and automatically adds new columns\n• Enable evolution: .option('mergeSchema', 'true') or SET spark.databricks.delta.schema.autoMerge.enabled = true\n• ALTER TABLE ADD COLUMN: Manual, explicit schema change`,

  "db-da-360": `✅ CORRECT (B): VERSION AS OF 5 returns the current state; VERSION AS OF 2 returns the March 25 state. EXCEPT ALL returns rows that exist in version 5 but NOT in version 2 — showing what was added or changed since March 25.\n\n❌ Why others are wrong:\n• (A) @v2 syntax: The @v2 shorthand is NOT standard Delta Lake SQL syntax in Databricks. The correct syntax is VERSION AS OF 2.\n• (C) MINUS keyword: MINUS is Oracle SQL syntax. Databricks SQL uses EXCEPT or EXCEPT ALL.\n• (D) DIFF command: There is no DIFF command in Delta Lake SQL.\n• (E) _change_type column: This column only appears in Change Data Feed (CDF) queries using table_changes(). It requires CDF to be explicitly enabled on the table.\n\n🔑 EXAM TIP: Time Travel comparison patterns:\n• EXCEPT ALL: Shows rows added/changed (set difference)\n• Full comparison: Query both versions and compare\n• VERSION AS OF n: Specify by version number\n• TIMESTAMP AS OF 'datetime': Specify by timestamp\n• Change Data Feed: Alternative for tracking row-level changes (requires enablement)`,

  "db-da-361": `✅ CORRECT (B): The recommended maintenance strategy: regular OPTIMIZE to compact small files into larger ones, followed by VACUUM with default 7-day retention to clean up old files while preserving Time Travel capability.\n\n❌ Why others are wrong:\n• (A) VACUUM with 0 hours: Destroys ALL Time Travel capability and can corrupt active reads. NEVER use 0-hour retention in production.\n• (C) DROP/CREATE weekly: Destroys table history, constraints, permissions, and downstream dependencies. Wasteful and risky.\n• (D) Increase warehouse size: Addresses the SYMPTOM (slow queries) not the ROOT CAUSE (small files). More compute = more cost without fixing the problem.\n• (E) Auto Loader optimizes file sizes: Auto Loader handles INGESTION. It doesn't optimize EXISTING data files in the table.\n\n🔑 EXAM TIP: Delta table maintenance:\n1. OPTIMIZE: Compacts small files into ~1GB files for better read performance\n2. VACUUM: Removes old, unreferenced files to reclaim storage\n3. Best practice: OPTIMIZE regularly → VACUUM after OPTIMIZE\n4. Predictive Optimization: Automates both for managed tables\n5. ZORDER BY / Liquid Clustering: Additional optimization for query performance`,

  "db-da-362": `✅ CORRECT (A): ALTER TABLE ADD COLUMN is a METADATA-ONLY operation in Delta Lake. It updates the schema definition in the transaction log without touching any data files. Existing files return NULL for the new column. This is instant regardless of table size (even with 50 million rows).\n\n❌ Why others are wrong:\n• (B) UPDATE SET loyalty_score = NULL: UPDATE cannot add new columns. It can only modify existing columns. This query would fail with "column not found."\n• (C) CREATE OR REPLACE with SELECT *, NULL AS: This REWRITES all data files — extremely expensive for 50M rows and unnecessary for a simple schema change.\n• (D) Must drop and recreate: FALSE. ALTER TABLE ADD COLUMN is fully supported for Delta tables.\n• (E) INSERT INTO with new column: INSERT cannot add columns to the schema. It inserts rows, not schema changes.\n\n🔑 EXAM TIP: Delta Lake schema operations (metadata-only = instant):\n• ADD COLUMN: Instant, no data rewrite\n• RENAME COLUMN: Instant, no data rewrite\n• DROP COLUMN: Requires data rewrite (can be lazy with column mapping)\n• CHANGE DATA TYPE: May require data rewrite depending on the type change`,

  "db-da-363": `✅ CORRECT (B): Delta Lake provides FULL ACID guarantees for ALL write operations, including MERGE:\n• Atomicity: All changes commit together or none do\n• Consistency: Schema enforcement validates the write\n• Isolation: Concurrent readers see the pre-MERGE snapshot until commit (snapshot isolation)\n• Durability: Changes are persisted to the transaction log and cloud storage\n\n❌ Why others are wrong:\n• (A) Atomicity only + partial reads: FALSE. Delta Lake provides SNAPSHOT ISOLATION — concurrent readers NEVER see partial results.\n• (C) Eventual consistency: FALSE. Delta Lake is IMMEDIATELY consistent after commit, not eventually consistent.\n• (D) ACID only for INSERT: FALSE. ACID applies to ALL operations — INSERT, UPDATE, DELETE, MERGE, OPTIMIZE.\n• (E) MERGE lacks ACID because two tables: FALSE. MERGE is a single ATOMIC transaction regardless of the number of source tables.\n\n🔑 EXAM TIP: Delta Lake ACID guarantees:\n• ALL write operations are ACID (INSERT, UPDATE, DELETE, MERGE)\n• Isolation level: Serializable by default (snapshot isolation for reads)\n• Implementation: Optimistic Concurrency Control via transaction log\n• Conflict resolution: Write conflicts are detected and retried automatically`,

  "db-da-364": `✅ CORRECT (B): The _change_type column in Change Data Feed (CDF) indicates the TYPE of row-level change:\n• 'insert': New row added\n• 'update_preimage': Row values BEFORE the update\n• 'update_postimage': Row values AFTER the update\n• 'delete': Row was removed\n\n❌ Why others are wrong:\n• (A) SQL command type: _change_type tracks ROW-level changes, not COMMAND-level operations. DESCRIBE HISTORY shows command-level operations.\n• (C) Schema change type: Schema changes (ADD COLUMN, etc.) are tracked in the transaction log, not through CDF.\n• (D) File-level changes: File operations (add/remove files) are tracked in the transaction log, not CDF.\n• (E) User-defined label: _change_type is AUTOMATICALLY generated by Delta Lake, not set manually.\n\n🔑 EXAM TIP: Change Data Feed (CDF):\n• Must be explicitly enabled: ALTER TABLE SET TBLPROPERTIES (delta.enableChangeDataFeed = true)\n• Query with: SELECT * FROM table_changes('table', start_version, end_version)\n• Special columns: _change_type, _commit_version, _commit_timestamp\n• Use case: Efficient incremental ETL — process only changed rows, not full table`
};

const filePath = './questions_databricks.js';
let content = fs.readFileSync(filePath, 'utf-8');

let upgraded = 0, failed = 0;

global.window = { questionsData: [] };
require(filePath);
const questions = window.questionsData;

for (const [id, newExpl] of Object.entries(upgrades)) {
  const escapedExpl = newExpl.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
  
  const q = questions.find(x => x.id === id);
  if (!q) { console.log(`❌ ${id} not found!`); failed++; continue; }
  
  let searchText;
  if (typeof q.prompt === 'string') {
    searchText = q.prompt.substring(0, 50);
  } else if (Array.isArray(q.prompt)) {
    const tb = q.prompt.find(p => p.type === 'text');
    searchText = tb ? tb.content.substring(0, 50) : null;
  }
  
  if (!searchText) { console.log(`❌ ${id} no searchable text`); failed++; continue; }
  
  const promptIdx = content.indexOf(searchText);
  if (promptIdx === -1) { console.log(`❌ ${id} prompt not found in file`); failed++; continue; }
  
  const explStart = content.indexOf('"explanation":', promptIdx);
  if (explStart === -1 || explStart - promptIdx > 5000) { console.log(`❌ ${id} explanation not in range`); failed++; continue; }
  
  const valueStart = content.indexOf('"', explStart + '"explanation":'.length);
  if (valueStart === -1) { console.log(`❌ ${id} value start not found`); failed++; continue; }
  
  let valueEnd = valueStart + 1;
  while (valueEnd < content.length) {
    if (content[valueEnd] === '\\') { valueEnd += 2; continue; }
    if (content[valueEnd] === '"') break;
    valueEnd++;
  }
  
  content = content.substring(0, valueStart) + '"' + escapedExpl + '"' + content.substring(valueEnd + 1);
  console.log(`✅ ${id} upgraded`);
  upgraded++;
}

fs.writeFileSync(filePath, content, 'utf-8');
console.log(`\nDone! Upgraded ${upgraded}/${Object.keys(upgrades).length} Managing Data explanations.`);
if (failed > 0) console.log(`Failed: ${failed}`);

try {
  delete require.cache[require.resolve(filePath)];
  global.window = { questionsData: [] };
  require(filePath);
  console.log(`✅ File valid! Total questions: ${window.questionsData.length}`);
} catch(e) {
  console.log(`❌ Syntax error: ${e.message.substring(0, 300)}`);
}
