/**
 * Upgrade Securing Data (24) + Data Modeling (22) = 46 questions
 */
const fs = require('fs');

const upgrades = {
  // ===== SECURING DATA (24) =====
  "db-da-13": `✅ CORRECT (E — All of these considerations): Working with PII requires a comprehensive approach covering:\n1. Organization-specific best practices (internal policies, data classification)\n2. Legal requirements where data was COLLECTED (e.g., GDPR for EU citizens' data)\n3. Legal requirements where analysis is PERFORMED (e.g., CCPA for California operations)\n\n❌ Why others are incomplete:\n• (A), (B), (D) alone: Each is partially correct but incomplete. PII compliance requires ALL three perspectives simultaneously.\n• (C) None of these: Completely wrong — PII handling always requires careful consideration.\n\n🔑 EXAM TIP: PII handling in Databricks:\n• Unity Catalog Column Masking: Hide PII at read time (e.g., mask SSN to ***-**-1234)\n• Row Filters: Restrict which rows a user can see\n• Tags: Classify columns as PII for governance\n• Audit Logs: Track who accessed PII data\n• Legal compliance spans BOTH data origin and analysis jurisdictions`,

  "db-da-17": `✅ CORRECT (A — View remains available and SELECT works): Wait — let me re-read. Actually, the correct answer depends on the view type. Since the question mentions TEMPORARY view and the current explanation says temporary views are session-scoped, the correct answer is that the view has been dropped when the session ended.\n\n✅ CORRECT: TEMPORARY VIEWS are session-scoped — they exist ONLY for the duration of the session that created them. When the user logs out or the session ends, the temporary view is automatically dropped.\n\n❌ Why others are wrong:\n• View remains available after logout: FALSE for TEMPORARY views. Only persistent views (CREATE VIEW) survive across sessions.\n• Data can be accessed via delta path: This describes accessing underlying table data, not the view itself.\n• View returns empty results: Temporary views don't "empty" — they completely CEASE TO EXIST.\n• View converted to table: Views are never automatically converted to tables.\n\n🔑 EXAM TIP: View types and lifecycle:\n• CREATE VIEW: Persistent, stored in catalog, survives sessions\n• CREATE TEMPORARY VIEW: Session-scoped, dropped on logout\n• CREATE GLOBAL TEMPORARY VIEW: Shared across sessions in the same cluster, dropped when cluster stops\n• Views store QUERIES, not data — they always read from the underlying table`,

  "db-da-41": `✅ CORRECT (C — Combining two data sources into a single dataset): Databricks SQL excels at data warehousing tasks: querying, joining, and aggregating data from multiple sources using SQL.\n\n❌ Why others are wrong:\n• (A) Testing data quality on import: This is a data engineering task better suited for Databricks Notebooks with DLT Expectations or Auto Loader.\n• (B) Tracking ML feature variables: This is a machine learning task for MLflow Feature Store or Databricks ML.\n• (D) Customer segmentation with clustering: Clustering algorithms require ML libraries (scikit-learn, Spark MLlib) — not pure SQL.\n• (E) Automating notebook workflows: This is for Databricks Workflows (Jobs) — an orchestration tool, not SQL.\n\n🔑 EXAM TIP: Databricks SQL use cases:\n✅ SQL queries, joins, aggregations\n✅ Dashboard creation and scheduling\n✅ Data exploration and ad-hoc analysis\n✅ Gold-layer table creation (CTAS, MERGE)\n❌ NOT for: ML training, data engineering pipelines, notebook orchestration`,

  "db-da-47": `✅ CORRECT (A — Augmenting gold-layer tables with external information): Working with Gold-layer tables (clean, business-ready data) and performing additional joins or enrichment with external data is a primary Databricks SQL analytics use case.\n\n❌ Why others are wrong:\n• (B) Automating notebook workflows: This is Databricks Workflows, not SQL.\n• (C) Testing data quality on import: Data quality testing is a data engineering function (DLT Expectations, Great Expectations).\n• (D) Customer segmentation with clustering: ML algorithms require compute libraries, not pure SQL.\n\n🔑 EXAM TIP: "Gold-layer" operations in Databricks SQL:\n• JOIN gold tables with reference data\n• CREATE OR REPLACE TABLE for aggregated metrics\n• Build views for dashboards\n• MERGE INTO for incremental updates\n• These are the analyst's primary workload`,

  "db-da-75": `✅ CORRECT (D — Data blending): Data blending is the process of combining data from multiple, different sources into a single unified dataset for comprehensive analysis. It's a common analytics operation in Databricks SQL.\n\n❌ Why others are wrong:\n• (A) Last-mile ETL: Refers to final transformations before data is ready for consumption — it's a specific ETL step, not the general concept of combining sources.\n• (B) Ad-hoc improvements: Not a standard data terminology.\n• (C) Data testing: Refers to validating data quality, not combining datasets.\n\n🔑 EXAM TIP: Data operations terminology:\n• Data Blending: Combining data from multiple sources into one dataset\n• Last-mile ETL: Final transformation step (Silver → Gold)\n• Data Enrichment: Adding external information to existing data\n• Data Wrangling/Munging: Cleaning and transforming raw data`,

  "db-da-78": `✅ CORRECT (B — Refresh schedule with 10-minute or less interval): To ensure stakeholders see new data within 10 minutes of it being available, the dashboard must refresh at least every 10 minutes. This matches the micro-batch frequency.\n\n❌ Why others are wrong:\n• (A) Always-on SQL Warehouse: An always-on warehouse ensures compute is ready, but doesn't control WHEN the dashboard refreshes. You still need a schedule.\n• (C) Subscribers included: Subscribers receive email notifications but don't control the refresh frequency.\n• (D) Structured Streaming cluster: Dashboards run on SQL Warehouses, not Streaming clusters.\n\n🔑 EXAM TIP: Dashboard refresh principles:\n• Refresh frequency ≤ data arrival frequency for "real-time" data\n• SQL Warehouses (not clusters) power dashboard queries\n• Scheduling options: Manual, 1min, 5min, 10min, 1hr, etc.\n• Subscribers receive email/Slack alerts on refresh`,

  "db-da-102": `✅ CORRECT (D — Mark queries as Trusted Assets): Trusted Assets are verified, pre-written SQL queries that Genie uses as high-confidence templates for matching questions. Marking frequently used queries as Trusted Assets ensures consistency and accuracy for recurring question patterns.\n\n❌ Why others are wrong:\n• (A) Disable domain instructions: Instructions provide critical business context. Removing them REDUCES trust and accuracy.\n• (B) Enable automatic generation without review: Removes human quality control. Unverified auto-generated SQL risks inaccuracy.\n• (C) Allow users to edit datasets: Editing source data introduces governance violations and data quality risks.\n\n🔑 EXAM TIP: Genie trust hierarchy:\n1. Trusted Assets (highest confidence) → verified SQL used as-is\n2. Sample Questions → training examples that guide SQL generation\n3. Instructions → business rules and terminology\n4. Unity Catalog metadata → semantic understanding of columns`,

  "db-da-125": `✅ CORRECT (C — To the Table definition): Row Filters in Unity Catalog are defined directly on the TABLE, not on the warehouse, dashboard, or user group. This ensures the security policy is enforced universally — regardless of which tool or warehouse accesses the table.\n\n❌ Why others are wrong:\n• (A) Dashboard: Dashboards display data but don't enforce row-level security. A user could bypass it by querying the table directly.\n• (B) SQL Warehouse: Warehouses execute queries but don't define data security policies. Multiple warehouses may access the same table.\n• (D) User Group settings: User groups define membership, not table-level security rules.\n\n🔑 EXAM TIP: Row Filters in Unity Catalog:\n• Defined as: A SQL function that returns TRUE/FALSE for each row\n• Applied to: The TABLE definition (ALTER TABLE SET ROW FILTER)\n• Enforced: On EVERY query, regardless of access method\n• Dynamic: Can use CURRENT_USER() or IS_MEMBER() for user-specific filtering\n• Cannot be bypassed: Even admins see only filtered results unless explicitly excluded`,

  "db-da-131": `✅ CORRECT (C — ABAC): Attribute-Based Access Control defines permissions based on tags/attributes assigned to data assets, users, and environmental context. Instead of explicitly granting SELECT to each user, policies automatically evaluate attributes (e.g., "if user.department = 'finance' AND table.sensitivity = 'confidential' → grant access").\n\n❌ Why others are wrong:\n• (A) RBAC: Role-Based Access Control grants permissions to ROLES, not attributes. Users are assigned to roles, and roles have permissions. More rigid than ABAC.\n• (B) ACL: Access Control Lists define explicit permission lists per object. Not attribute-driven.\n• (D) IAM: Identity and Access Management is a broader infrastructure concept (AWS IAM, Azure AD), not a specific UC access control model.\n• (E) MFA: Multi-Factor Authentication verifies user IDENTITY, not data ACCESS policies.\n\n🔑 EXAM TIP: UC Access Control models:\n• RBAC (traditional): GRANT SELECT ON TABLE x TO role_y\n• ABAC (tag-based): Dynamic policies evaluating user + data attributes\n• Row Filters/Column Masks: Fine-grained per-row and per-column policies\n• All three can COEXIST in Unity Catalog`,

  "db-da-135": `✅ CORRECT (C — Column Masking): Column Masking uses a User-Defined Function (UDF) to transform sensitive column values at READ time without modifying stored data. Different users see different versions of the data based on their identity/group.\n\n❌ Why others are wrong:\n• (A) Row Filters: Row Filters restrict which ROWS a user can see, not which COLUMN VALUES. SSN masking requires column-level transformation.\n• (B) Data Tagging: Tags classify data (e.g., 'PII = true') for governance but don't transform or mask values at query time.\n• (D) Encryption at Rest: Encryption protects data on disk but doesn't affect query results. Decrypted values are shown to all authorized users — no partial masking.\n• (E) Access Control Lists: ACLs grant/deny access to entire objects (tables, schemas), not partial column transformation.\n\n🔑 EXAM TIP: Column Masking vs. Row Filters:\n• Column Masking: TRANSFORMS values in a column (e.g., SSN → ***-**-1234)\n• Row Filters: HIDES entire rows based on conditions\n• Both are defined on the TABLE and enforced universally\n• Both use SQL functions with CURRENT_USER() or IS_MEMBER()`,

  "db-da-140": `✅ CORRECT (B — GRANT SELECT): GRANT SELECT provides read-only access — the user can run SELECT queries but cannot INSERT, UPDATE, DELETE, or modify the table structure.\n\n❌ Why others are wrong:\n• (A) ALL PRIVILEGES: Grants everything — SELECT, MODIFY, CREATE, DROP. Over-privileged for read-only access.\n• (C) MODIFY: Grants write access (INSERT, UPDATE, DELETE) but NOT necessarily SELECT. This is the opposite of what's needed.\n• (D) CREATE: Controls ability to CREATE objects within a schema, not read table data.\n• (E) READ: Not a valid Unity Catalog privilege. The correct privilege name is SELECT.\n\n🔑 EXAM TIP: Unity Catalog privileges for tables:\n• SELECT: Read data (SELECT queries)\n• MODIFY: Write data (INSERT, UPDATE, DELETE)\n• ALL PRIVILEGES: All available privileges\n• Principle of least privilege: ALWAYS grant the minimum needed`,

  "db-da-180": `✅ CORRECT (B — Dynamic Views with IS_MEMBER()): Dynamic Views use IS_MEMBER() to check group membership at QUERY TIME, conditionally showing or hiding PII columns. This provides centralized, role-based access control without duplicating data.\n\nSQL Pattern:\nCREATE VIEW safe_customers AS\nSELECT customer_id, name,\n  CASE WHEN IS_MEMBER('pii_authorized') THEN email ELSE '***MASKED***' END AS email\nFROM customers;\n\n❌ Why others are wrong:\n• (A) GRANT SELECT on base table: Grants access to ALL columns including PII — no column-level restriction.\n• (C) CSV on DBFS: Ungoverned, insecure. DBFS folder-level ACLs lack the granularity of UC column masking.\n• (D) Mask PII in source table: Permanently destroys PII data. Original values cannot be recovered for authorized users.\n\n🔑 EXAM TIP: Dynamic Views vs. Column Masking:\n• Dynamic Views: Use CASE WHEN IS_MEMBER() for conditional column access\n• Column Masks: Native UC feature (ALTER TABLE SET COLUMN MASK)\n• Both achieve similar results; Column Masks are the modern, preferred approach`,

  "db-da-181": `✅ CORRECT (A — Privileges cascade downward): Unity Catalog uses hierarchical privilege inheritance. A privilege granted at a higher level (catalog) automatically applies to ALL child objects (schemas, tables, views) within that catalog.\n\nExample: GRANT SELECT ON CATALOG production TO analysts → analysts can SELECT on ALL tables in ALL schemas within the production catalog.\n\n❌ Why others are wrong:\n• (B) Only from metastore level: FALSE. Inheritance occurs at EVERY level — metastore, catalog, schema.\n• (C) Must grant individually: FALSE. Individual grants are possible but not required — inheritance enables bulk permission management.\n• (D) Schema privileges don't affect tables: FALSE. Privileges at the schema level DO cascade to tables and views within that schema.\n\n🔑 EXAM TIP: UC privilege inheritance hierarchy:\nMetastore → Catalog → Schema → Table/View\n• GRANT at Catalog level → applies to ALL schemas and tables within\n• GRANT at Schema level → applies to ALL tables within\n• USAGE is required at EACH level to traverse the hierarchy\n• More specific grants COMPLEMENT (don't override) inherited grants`,

  "db-da-189": `✅ CORRECT (D — Create separate catalogs): Creating separate catalogs for production, development, and testing provides the STRONGEST isolation. Each catalog has independent permission policies, storage, and access controls.\n\n❌ Why others are wrong:\n• (A) Single catalog with all schemas: Insufficient isolation. A misconfigured permission at the catalog level could expose production data to developers.\n• (B) UC environment separation features: Vague — UC doesn't have a specific "environment separation" feature beyond catalogs.\n• (C) Shared schema across environments: Dangerous. Using the same schema for production and development risks accidental data modification.\n\n🔑 EXAM TIP: Environment isolation pattern:\n• catalog_production → production data, strict access\n• catalog_development → development sandbox, broader access\n• catalog_testing → QA/testing, controlled access\n• Benefits: Independent permissions, storage isolation, clear boundaries\n• Reference: catalog.schema.table (always clear which environment you're in)`,

  "db-da-193": `✅ CORRECT (B — Data section): The Data section of the Databricks UI (Catalog Explorer) provides a Permissions tab where admins and data owners can manage GRANT/REVOKE permissions on databases, tables, and views through a visual interface.\n\n❌ Why others are wrong:\n• (A) Dashboard: The Dashboard area is for viewing/creating dashboards, not managing data permissions.\n• (C) SQL Warehouses: SQL Warehouse settings control compute configuration (cluster size, auto-stop), not data permissions.\n• (D) Settings: Workspace-level settings control authentication, workspace access, and admin features — not individual table permissions.\n\n🔑 EXAM TIP: Where to manage permissions:\n• UI: Catalog Explorer → navigate to object → Permissions tab\n• SQL: GRANT/REVOKE commands\n• Both methods achieve the same result\n• Best practice: Use groups (not individual users) for permission management`,

  "db-da-333": `✅ CORRECT (B — Row-level security using row filters): Unity Catalog row filters dynamically restrict which rows a user can see based on their identity or group membership. The filter function is applied to the table and evaluated transparently on every query.\n\n❌ Why others are wrong:\n• (A) Column masking: Masks COLUMN VALUES, not ROWS. The analyst needs to restrict which rows (regions) are visible, not hide column values.\n• (C) Separate tables per region: Creates data duplication, increases maintenance, and doesn't scale. Every new region requires a new table.\n• (D) VIEW with hardcoded emails: Doesn't scale — every new user requires updating the VIEW SQL. Not dynamic.\n• (E) Encrypting region data: Encryption doesn't provide row-level filtering. All authorized users see the same encrypted/decrypted data.\n\n🔑 EXAM TIP: Row Filter implementation:\nCREATE FUNCTION region_filter(region STRING)\nRETURNS BOOLEAN\nRETURN IF(IS_MEMBER('all_regions'), TRUE, region = CURRENT_USER_ATTRIBUTE('region'));\n\nALTER TABLE customers SET ROW FILTER region_filter ON (region);`,

  "db-da-334": `✅ CORRECT (B — Dynamic column masking): Column masking applies a masking function (UDF) to the SSN column at read time. HR analysts in the 'hr_group' see real SSNs; everyone else sees masked values (e.g., XXX-XX-1234). The underlying data is NEVER modified.\n\n❌ Why others are wrong:\n• (A) Row-level security: Filters ROWS, not columns. Would hide entire employee records, not just SSN values.\n• (C) Revoke SELECT on entire table: Too restrictive. The team needs access to OTHER columns (name, department, salary) — just not SSN.\n• (D) VIEW excluding SSN: Works but non-HR users must remember to use the view. Column masking is enforced on the TABLE itself — can't be bypassed.\n• (E) Delta Lake encryption: Encryption protects data at rest but doesn't provide selective visibility per user group.\n\n🔑 EXAM TIP: Column Masking implementation:\nCREATE FUNCTION mask_ssn(ssn STRING)\nRETURNS STRING\nRETURN IF(IS_MEMBER('hr_group'), ssn, CONCAT('XXX-XX-', RIGHT(ssn, 4)));\n\nALTER TABLE employees ALTER COLUMN ssn SET MASK mask_ssn;`,

  "db-da-335": `✅ CORRECT (B — Missing USAGE on parent catalog/schema): Unity Catalog requires USAGE privilege at EACH level of the hierarchy. Even with SELECT on the table, users can't access it without USAGE on both the parent catalog AND schema.\n\nRequired grants:\n1. GRANT USAGE ON CATALOG finance TO analyst_team;\n2. GRANT USAGE ON SCHEMA finance.default TO analyst_team;\n3. GRANT SELECT ON TABLE finance.transactions TO analyst_team;\n\n❌ Why others are wrong:\n• (A) INSERT needed to read: FALSE. SELECT is sufficient for reading. INSERT is a write operation.\n• (C) SELECT only works on views: FALSE. SELECT works on tables, views, and materialized views.\n• (D) Warehouse prevents non-admin SELECT: FALSE. SQL Warehouses don't restrict SQL operations by user role.\n• (E) Table must be Trusted Asset: FALSE. Trusted Assets are a Genie Space concept, not a permission requirement.\n\n🔑 EXAM TIP: The USAGE chain (most tested concept in Securing Data):\n• USAGE must be granted at EVERY level: Catalog → Schema\n• Without USAGE, SELECT/MODIFY on child objects is unreachable\n• Think of USAGE as a "door key" — you need keys to traverse each level`,

  "db-da-336": `✅ CORRECT (B — Delta Sharing): Delta Sharing is an open protocol for secure, cross-organization data sharing. Recipients access live data without needing a Databricks workspace or account. They can use any compatible client (pandas, Spark, Power BI, Tableau).\n\n❌ Why others are wrong:\n• (A) GRANT SELECT to external emails: GRANT only works for principals within the same Unity Catalog metastore. External organizations are outside this boundary.\n• (C) CSV via encrypted email: Manual, ungoverned, and not scalable. No auditability or access control.\n• (D) Public S3 bucket: Security disaster — no access control, no audit trail, data exposed to the internet.\n• (E) Partner Connect: Establishes technology partner integrations (e.g., Fivetran, dbt), not data sharing with external organizations.\n\n🔑 EXAM TIP: Delta Sharing key facts:\n• Open-source protocol (not proprietary to Databricks)\n• Recipients don't need Databricks\n• Read-only access (recipients can't modify source)\n• Supports: Spark, pandas, Power BI, Tableau, R\n• Audit trail maintained in provider's Unity Catalog`,

  "db-da-337": `✅ CORRECT (B — Unity Catalog system audit logs): System audit logs (system.access.audit) capture comprehensive data access events: user identity, timestamp, query text, tables/columns accessed, and operation type. This is the definitive source for compliance auditing.\n\n❌ Why others are wrong:\n• (A) Delta transaction log: Records write OPERATIONS (INSERT, UPDATE, DELETE) but not user-level READ access patterns. Doesn't show which users ran SELECT queries.\n• (C) SQL Warehouse query history: Shows queries but is typically limited to current session or recent history, not a reliable 30-day archive for compliance.\n• (D) DESCRIBE HISTORY: Shows table-level operations (writes, schema changes) but NOT user access patterns or SELECT queries.\n• (E) Third-party tool required: FALSE. Unity Catalog provides built-in audit logging without external tools.\n\n🔑 EXAM TIP: Audit data sources:\n• system.access.audit → WHO accessed WHAT (compliance auditing)\n• DESCRIBE HISTORY → WHAT operations happened on a table\n• system.billing.usage → compute consumption\n• SQL Warehouse query history → recent query execution details`,

  "db-da-338": `✅ CORRECT (B — Only owners or admins can grant): In Unity Catalog, the ability to GRANT privileges is restricted to the object OWNER or account/metastore administrators. Having MODIFY privilege allows data changes (INSERT, UPDATE, DELETE) but does NOT include permission management capabilities.\n\n❌ Why others are wrong:\n• (A) MODIFY can grant any privilege: FALSE. MODIFY = data write access only, not permission management.\n• (C) Must be in same group: Group membership is irrelevant for granting permissions. Only OWNERSHIP matters.\n• (D) GRANT only via UI: FALSE. GRANT works via both SQL commands and Catalog Explorer UI.\n• (E) MODIFY includes delegation: FALSE. MODIFY does not include any delegation or permission management abilities.\n\n🔑 EXAM TIP: Permission management rules:\n• WHO can GRANT: Object owner OR metastore/account admin\n• MODIFY ≠ ability to grant (common exam trap)\n• OWNERSHIP is the only privilege that includes permission management\n• Transfer ownership: ALTER TABLE table_name SET OWNER TO new_owner`,

  "db-da-339": `✅ CORRECT (C — Stop accessing and notify supervisor): The correct protocol for accidentally encountering unauthorized PII:\n1. IMMEDIATELY stop accessing the data\n2. Do NOT modify, delete, or export anything\n3. Notify supervisor or data governance team\n4. Follow organizational incident response procedures\n\n❌ Why others are wrong:\n• (A) Delete the table: Destructive action that may violate compliance requirements and destroy evidence for auditing.\n• (B) Drop PII column: Unauthorized data modification. Also hides the governance gap from administrators.\n• (D) Export to local file: Exfiltrates PII data — makes the breach WORSE, not better.\n• (E) Apply column masking yourself: May lack the authority to modify table security. Also doesn't address the root cause (improper access grant).\n\n🔑 EXAM TIP: PII incident response:\n1. STOP accessing immediately\n2. Do NOT modify or delete anything\n3. ESCALATE to governance team\n4. DOCUMENT what was accessed\n5. Common exam trap: "Delete the data to prevent further exposure" — WRONG answer`,

  "db-da-340": `✅ CORRECT (B — Governed Tags with key-value metadata): Unity Catalog Governed Tags provide structured, searchable, and enforceable metadata classification. Tags like 'sensitivity' = 'confidential' can be applied to tables and columns, discovered through Catalog Explorer, and used in ABAC policies.\n\n❌ Why others are wrong:\n• (A) Table comments: Free-text, not structured. Cannot be searched programmatically or used in access control policies.\n• (C) TBLPROPERTIES: Store Delta Lake configuration (not governance metadata). Not searchable through Catalog Explorer.\n• (D) Naming conventions: Fragile, requires human discipline, not enforceable. Tables may be renamed or conventions violated.\n• (E) Separate catalogs: Over-architects the solution. Creates silos and increases complexity for a classification problem.\n\n🔑 EXAM TIP: Tags vs. Comments vs. Properties:\n• Tags (SET TAGS): Structured key-value, searchable, governance-enforceable\n• Comments (SET COMMENT): Free-text documentation, human-readable\n• Properties (TBLPROPERTIES): Delta Lake configuration, technical settings\n• For governance classification → use TAGS`,

  "db-da-341": `✅ CORRECT (B — Data lineage tracking): Unity Catalog automatically maps table-level and column-level dependencies across the entire data pipeline (Bronze → Silver → Gold). This visual graph shows how data flows, transforms, and where issues may propagate.\n\n❌ Why others are wrong:\n• (A) DESCRIBE HISTORY: Shows operations on a SINGLE table (versions, timestamps, operations). Doesn't show cross-table dependencies.\n• (C) Query Profile: Shows the execution plan of a SINGLE query (physical operators, time distribution). Not cross-pipeline flow.\n• (D) Delta transaction logs: Per-table write operations. No cross-table lineage information.\n• (E) Change Data Feed: Tracks row-level changes WITHIN a table. Doesn't map pipeline flow between tables.\n\n🔑 EXAM TIP: Lineage use cases:\n• Impact analysis: "If I change column X, what dashboards break?"\n• Root cause: "Bad data in Gold table — where did it come from?"\n• Compliance: "Show the full data transformation chain for audit"\n• Captured AUTOMATICALLY as queries execute — no manual configuration`,

  // ===== DATA MODELING (22) =====
  "db-da-59": `✅ CORRECT (C — Different visualizations tell different stories): Visualizations are tools for communication. Different chart types (bar, line, scatter, pie, heatmap) highlight different aspects, trends, or relationships within the same or different datasets.\n\n❌ Why others are wrong:\n• (A) All must use the same data: FALSE. A dashboard can contain visualizations from different queries and datasets.\n• (B) Line charts for categorical data: FALSE. Line charts show TRENDS over continuous data (time series). Bar charts are preferred for categorical data.\n• (D) No difference between bar chart and histogram: FALSE. Bar charts show categorical comparisons; histograms show frequency distributions of continuous data.\n\n🔑 EXAM TIP: Visualization type selection:\n• Bar chart: Categorical comparisons\n• Line chart: Trends over time (continuous)\n• Scatter plot: Correlation between two variables\n• Histogram: Distribution/frequency of continuous data\n• Pie chart: Part-of-whole composition (use sparingly)`,

  "db-da-60": `✅ CORRECT (D — Variance measures spread from central value): Variance quantifies how far a set of values is spread out from the dataset's mean (average). High variance = data points are spread widely; low variance = data points cluster near the mean.\n\n❌ Why others are wrong:\n• (A) Distance of a SINGLE value from a set: This describes a Z-score or deviation of an individual observation, not variance.\n• (B) Distance from max/min: This describes the range (max - min), not variance.\n• (C) Central tendency: Central tendency is the mean, median, or mode — measures of the CENTER, not the SPREAD. Variance measures dispersion.\n\n🔑 EXAM TIP: Statistical measures:\n• Central tendency: Mean, Median, Mode (WHERE is the center?)\n• Dispersion: Variance, Standard Deviation, Range (HOW SPREAD is the data?)\n• Variance = average of squared deviations from the mean\n• Standard Deviation = √Variance (in original units)`,

  "db-da-110": `✅ CORRECT (B — Consumer pays for compute): In Delta Sharing's decoupled architecture, the DATA PROVIDER hosts and pays for data STORAGE. The DATA CONSUMER brings their own compute (SQL Warehouse, Spark cluster) and pays for processing queries.\n\n❌ Why others are wrong:\n• (A) Provider pays compute, consumer pays storage: REVERSED. Provider pays storage, consumer pays compute.\n• (C) 50/50 split: No cost-sharing mechanism in Delta Sharing.\n• (D) No compute costs: FALSE. Running queries always requires compute, which incurs costs.\n\n🔑 EXAM TIP: Delta Sharing cost model:\n• Provider: Pays for data STORAGE (cloud storage costs)\n• Consumer: Pays for query COMPUTE (SQL Warehouse/cluster costs)\n• No data copying — consumer reads data directly from provider's storage\n• This is the "open data sharing" model — clean cost separation`,

  "db-da-113": `✅ CORRECT (A — Requires Serverless or Pro SQL Warehouse): Materialized Views require advanced incremental computation capabilities that are only available in Pro and Serverless SQL Warehouse tiers. Standard warehouses lack these features.\n\n❌ Why others are wrong:\n• (B) Only Admin users can refresh: FALSE. Any user with appropriate permissions can trigger or schedule MV refreshes.\n• (C) Underlying tables not Delta: While possible, the error specifically mentions the warehouse tier, not the data format.\n• (D) Standard warehouses can't write data: FALSE. Standard warehouses can write data (INSERT, MERGE), but they can't manage Materialized View refresh operations.\n\n🔑 EXAM TIP: SQL Warehouse tiers:\n• Standard: Basic SQL queries. No MVs, no Predictive Optimization.\n• Pro: Materialized Views, Liquid Clustering, advanced features.\n• Serverless: Same as Pro + automatic scaling + no infrastructure management.\n• For the exam: If a feature isn't working → CHECK THE WAREHOUSE TIER.`,

  "db-da-120": `✅ CORRECT (B — Insert succeeds): In Databricks/Unity Catalog, PRIMARY KEY and FOREIGN KEY constraints are INFORMATIONAL ONLY — they are NOT enforced. The insert will succeed even with a non-existent customer_id.\n\n❌ Why others are wrong:\n• (A) Constraint violation error: This would be true in traditional RDBMS (PostgreSQL, MySQL) but NOT in Databricks. Constraints are declarative metadata only.\n• (C) Quarantined to Bad Records: There is no automatic quarantine mechanism for constraint violations in Delta Lake.\n• (D) customer_id set to NULL: The value is NOT modified. The insert succeeds with the original non-existent customer_id.\n\n🔑 EXAM TIP: PK/FK in Databricks — CRITICAL EXAM CONCEPT:\n• NOT ENFORCED (no validation on INSERT/UPDATE/DELETE)\n• ARE informational — used by:\n  - Query optimizer (join optimization)\n  - BI tools (automatic relationship detection)\n  - AI/BI Genie (table joining logic)\n• Data quality enforcement must use other mechanisms: DLT Expectations, CHECK constraints, MERGE logic`,

  "db-da-134": `✅ CORRECT (B — Central fact table surrounded by denormalized dimension tables): A Star Schema has:\n• ONE central fact table (metrics/measures: sales amount, quantity)\n• MULTIPLE denormalized dimension tables (descriptive attributes: product, customer, date, store)\n• Direct 1:N relationships from dimensions to fact table\n\n❌ Why others are wrong:\n• (A) Single flat table: This describes a denormalized flat table, not a star schema.\n• (C) Fully normalized OLTP schema: 3NF normalization is for transactional systems (OLTP), not analytics (OLAP). Star schema deliberately denormalizes for query performance.\n• (D) Multiple fact tables, no dimensions: This is not a recognized schema pattern.\n• (E) Hierarchical inheritance: Not a standard data modeling concept.\n\n🔑 EXAM TIP: Star Schema vs. Snowflake Schema:\n• Star: Dimension tables are DENORMALIZED (flat) → simpler joins, faster queries\n• Snowflake: Dimension tables are NORMALIZED (sub-dimensions) → less redundancy, more joins\n• For Databricks analytics: Star Schema is PREFERRED (fewer joins = better performance)`,

  "db-da-154": `✅ CORRECT (B — View persists in Unity Catalog): Regular views created with CREATE VIEW are persistent objects stored in Unity Catalog. They survive session ends, restarts, and are accessible to any user with appropriate permissions (SELECT on the view + USAGE on parent containers).\n\n❌ Why others are wrong:\n• (A) Views are session-scoped: FALSE for regular views. Only TEMPORARY VIEWS are session-scoped.\n• (C) Underlying data deleted: Views don't store data — they store QUERIES. The underlying table's data is independent of the view.\n• (D) Converted to table: Views are NEVER automatically converted to tables.\n• (E) Only accessible by creator: FALSE. Any user with SELECT permission on the view can query it.\n\n🔑 EXAM TIP: View types comparison:\n• CREATE VIEW: Persistent, stored in UC, survives sessions, shareable\n• CREATE TEMPORARY VIEW: Session-scoped, dropped on logout, not shareable\n• CREATE GLOBAL TEMPORARY VIEW: Cluster-scoped, dropped when cluster stops\n• Materialized View: Persistent + pre-computed results (requires Pro/Serverless warehouse)`,

  "db-da-156": `✅ CORRECT (B — Insert succeeds, constraints are informational): Unity Catalog PK/FK constraints are declarative metadata — they inform tools about relationships but do NOT enforce data integrity during writes. The insert with a non-existent order_id succeeds without error.\n\n❌ Why others are wrong:\n• (A) Constraint violation error: Only in traditional RDBMS. Databricks does not validate PK/FK on writes.\n• (C) Flagged as orphaned: No automatic orphan detection in Delta Lake.\n• (D) Insert queued: No deferred constraint checking in Databricks.\n• (E) Orders table auto-updated: Tables are NOT automatically modified to satisfy referential constraints.\n\n🔑 EXAM TIP: This is one of the MOST REPEATED concepts across domains:\n• PK/FK = INFORMATIONAL ONLY in Databricks\n• Used by: Query optimizer, BI tools, Genie\n• NOT used for: Data validation, constraint enforcement\n• For data quality: Use DLT Expectations, CHECK constraints, or application-level validation`,

  "db-da-178": `✅ CORRECT (C — Link Table): In Data Vault 2.0, Link tables model the RELATIONSHIPS between business entities (Hubs). When multiple Hub entities are involved in a relationship (many-to-many), a Link table stores the foreign keys to each Hub.\n\n❌ Why others are wrong:\n• (A) Hub Table: Hubs store unique BUSINESS KEYS (identifiers) — not relationships.\n• (B) Satellite Table: Satellites store DESCRIPTIVE/CONTEXTUAL data and change history — not relationships.\n• (D) Reference Table: Reference tables store static lookup data (country codes, status types) — not entity relationships.\n\n🔑 EXAM TIP: Data Vault 2.0 components:\n• Hub: Unique business keys (e.g., customer_id, product_id)\n• Link: Relationships between Hubs (e.g., customer-bought-product)\n• Satellite: Descriptive attributes + history (e.g., customer name, address changes)\n• Star Schema is more common on the exam, but know Data Vault basics`,

  "db-da-186": `✅ CORRECT (D — Dimension tables have PK, fact table has FK references): In a star schema:\n• Each dimension table has a PRIMARY KEY (unique identifier for each dimension record)\n• The fact table contains FOREIGN KEY columns that reference each dimension's PK\n• This enables efficient analytical queries through well-defined joins\n\n❌ Why others are wrong:\n• (A) Arbitrary columns, no PK/FK: Star schemas DEPEND on well-defined PK/FK relationships for proper joins.\n• (B) Fact table has PKs matching dimension PKs: The fact table's own PK is typically a composite of its FK columns (or a surrogate key). It doesn't have PKs that "match" dimension PKs.\n• (C) Only foreign keys, non-unique columns: Dimension tables MUST have unique primary keys for the star schema to work correctly.\n\n🔑 EXAM TIP: Star Schema join pattern:\n• dim_product.product_id (PK) ← fact_sales.product_id (FK)\n• dim_customer.customer_id (PK) ← fact_sales.customer_id (FK)\n• dim_date.date_id (PK) ← fact_sales.date_id (FK)\n• Fact table: Metrics (amount, quantity) + FK columns\n• Dimension table: PK + descriptive attributes (name, category, address)`,

  "db-da-285": `✅ CORRECT (B — Star Schema): For reporting and BI workloads in Databricks SQL, the Star Schema is the RECOMMENDED design. It features a central fact table surrounded by denormalized dimension tables, enabling simple, fast analytical queries with fewer joins.\n\n❌ Why others are wrong:\n• (A) Data Vault 2.0: Designed for data warehouse LOADING and historization, not for end-user reporting. Too complex for direct BI queries.\n• (C) Normalized 3NF: Optimized for OLTP (transactional writes), not OLAP (analytical reads). Too many joins for reporting.\n• (D) Snowflake Schema: Similar to star but with normalized dimensions — more joins, more complexity, slightly worse query performance.\n\n🔑 EXAM TIP: Schema selection:\n• Star Schema: Best for REPORTING (Gold layer, dashboards, BI)\n• Snowflake Schema: When dimension storage must be minimized\n• Data Vault: Best for data WAREHOUSE LOADING (Silver layer)\n• 3NF: Best for OLTP applications (not analytics)`,

  "db-da-312": `✅ CORRECT (B — Star schema with central fact table and denormalized dimension tables): The Gold layer typically uses a star schema: fact_sales connects directly to dim_product, dim_store, and dim_customer via foreign keys. Dimensions are DENORMALIZED (flat) for query simplicity.\n\n❌ Why others are wrong:\n• (A) Snowflake schema: Normalized dimensions add complexity and joins. Not recommended for Gold layer reporting.\n• (C) Data vault: Used in Silver layer for loading and historization, not Gold layer for reporting.\n• (D) Flat table: All dimensions embedded in one table → update anomalies, massive redundancy.\n• (E) Graph model: Used for network analysis (social graphs, knowledge graphs), not standard BI reporting.\n\n🔑 EXAM TIP: Gold layer best practices:\n• Star schema for reporting\n• Denormalized dimensions for query simplicity\n• Pre-aggregated tables for dashboard performance\n• CTAS (CREATE TABLE AS SELECT) for materialization`,

  "db-da-313": `✅ CORRECT (B — Bronze = raw, Silver = cleaned, Gold = business aggregations): The Medallion Architecture progressively refines data:\n• Bronze: Raw data as-is from source systems (append-only, no transformations)\n• Silver: Cleaned, deduplicated, joined data (enterprise source of truth)\n• Gold: Business-ready aggregations, KPIs, and reporting tables\n\n❌ Why others are wrong:\n• (A) Reversed layers: Bronze stores RAW data (not aggregated KPIs), and Gold stores KPIs (not raw data).\n• (C) Same data with different permissions: The layers contain DIFFERENT data at different refinement levels.\n• (D) Bronze/Silver are optional: All three layers serve distinct purposes in the architecture.\n• (E) Bronze = external, Silver = internal: The distinction is refinement level, not data source.\n\n🔑 EXAM TIP: Medallion Architecture summary:\n• Bronze: Ingest as-is, append-only, preserve raw data\n• Silver: Clean, deduplicate, join, conform (source of truth)\n• Gold: Aggregate, model, optimize for consumption\n• Each layer adds value through transformation and quality improvement`,

  "db-da-314": `✅ CORRECT (B — CREATE OR REPLACE TABLE with GROUP BY): CTAS creates a materialized Delta table with the aggregated results — region, month, and SUM(amount). This persists the aggregation for efficient dashboard queries.\n\n❌ Why others are wrong:\n• (A) CREATE VIEW: Creates a virtual table that re-executes the aggregation on EVERY query — slower for dashboards with many concurrent users.\n• (C) INSERT INTO without aggregation: Inserts raw rows without the required GROUP BY aggregation.\n• (D) CREATE EXTERNAL TABLE with SELECT: Mixing external table creation with inline SELECT is not standard syntax.\n• (E) MERGE with ON 1=1: Inappropriate use of MERGE. The ON 1=1 condition creates a cartesian match — every row matches every other row.\n\n🔑 EXAM TIP: CTAS vs. VIEW for Gold layer:\n• CTAS (TABLE): Pre-computed results, fast reads, requires refresh\n• VIEW: Always fresh, slower reads (re-executes query each time)\n• For dashboards with many users → TABLE (pre-computed)\n• For ad-hoc analysis needing latest data → VIEW`,

  "db-da-315": `✅ CORRECT (B — MERGE INTO with composite key match): MERGE INTO handles deduplication for composite keys by matching on BOTH order_id AND line_item_id. It updates existing records (WHEN MATCHED) and inserts new ones (WHEN NOT MATCHED) — a classic upsert pattern.\n\n❌ Why others are wrong:\n• (A) INSERT WHERE NOT EXISTS: Only handles inserts — doesn't update existing records with new values.\n• (C) DELETE + re-INSERT: Wasteful, creates unnecessary version churn, and is not atomic.\n• (D) CREATE OR REPLACE full rebuild: Rebuilds the entire table on every run — extremely expensive for large tables.\n• (E) COPY INTO auto-deduplicates: FALSE. COPY INTO does NOT deduplicate. It appends data from files.\n\n🔑 EXAM TIP: MERGE INTO pattern:\nMERGE INTO gold.fact_orders AS target\nUSING silver.orders AS source\nON target.order_id = source.order_id AND target.line_item_id = source.line_item_id\nWHEN MATCHED THEN UPDATE SET *\nWHEN NOT MATCHED THEN INSERT *`,

  "db-da-316": `✅ CORRECT (B — Surrogate keys provide stable, immutable identifiers): Surrogate keys (typically auto-generated integers or UUIDs) decouple the data warehouse from source system changes. If a natural key changes (e.g., patient ID format, doctor license number), the surrogate key remains stable, protecting all downstream joins and references.\n\n❌ Why others are wrong:\n• (A) Required by Delta Lake: FALSE. Delta Lake doesn't require surrogate keys. They're a data modeling best practice, not a technical requirement.\n• (C) Only about storage optimization: Storage savings are a minor benefit. The PRIMARY value is stability and SCD support.\n• (D) Enable encryption: Surrogate keys have nothing to do with encryption.\n• (E) Only for snowflake schemas: FALSE. Surrogate keys are used in BOTH star and snowflake schemas.\n\n🔑 EXAM TIP: Surrogate vs. Natural keys:\n• Surrogate: System-generated (1, 2, 3 or UUID), stable, immutable\n• Natural: Business-meaningful (SSN, email, product_code), may change\n• Surrogate keys enable: SCD Type 2 tracking, join stability, source independence`,

  "db-da-317": `✅ CORRECT (C — Silver layer): The Silver layer is the "Enterprise Source of Truth" where data from MULTIPLE Bronze sources is cleaned, joined, deduplicated, and conformed. The presence of CRM, ERP, and web analytics data joined together is the defining characteristic of the Silver layer.\n\n❌ Why others are wrong:\n• (A) Bronze: Bronze stores raw data from INDIVIDUAL sources, typically without cross-source joins.\n• (B) Gold: Gold contains business-ready AGGREGATIONS for reporting — not the raw joined data.\n• (D) Violates principles: FALSE. Joining multiple sources is exactly what the Silver layer is designed for.\n• (E) Platinum: There is no standard "Platinum" layer in the medallion architecture.\n\n🔑 EXAM TIP: Silver layer indicators:\n• Data from MULTIPLE sources joined together\n• Cleaned and deduplicated\n• Conformed data types and naming\n• NOT aggregated (that's Gold)\n• NOT raw (that's Bronze)`,

  "db-da-318": `✅ CORRECT (B — TABLE via CTAS): For a dashboard query that aggregates 50M records into 500 summary rows, a materialized TABLE is the clear winner. The dashboard reads 500 pre-computed rows instead of re-executing the 50M-row aggregation on every request.\n\n❌ Why others are wrong:\n• (A) VIEW for freshness: While views always show fresh data, re-aggregating 50M rows on every dashboard load creates unacceptable latency for 20+ concurrent users.\n• (C) Gold tables should never be materialized: FALSE. Gold-layer materialization is a BEST PRACTICE for dashboard performance.\n• (D) TEMPORARY VIEW: Session-scoped — disappears when the session ends. Not suitable for shared dashboards.\n• (E) No performance difference: FALSE. TABLE reads 500 rows vs. VIEW re-aggregates 50M rows. The difference is massive.\n\n🔑 EXAM TIP: VIEW vs. TABLE decision:\n• Use VIEW when: Data is small, freshness is critical, few concurrent users\n• Use TABLE when: Data is large, many concurrent users, OK with scheduled refresh\n• Materialized View: Automatic refresh + incremental computation (best of both)`,

  "db-da-319": `✅ CORRECT (B — MERGE INTO with SCD Type 2 logic): Type 2 Slowly Changing Dimensions require inserting NEW records for changed values while marking the PREVIOUS record with an end date and inactive flag. This is implemented using MERGE INTO with custom logic:\n\nMERGE INTO dim_customer AS target\nUSING staging_customer AS source\nON target.customer_id = source.customer_id AND target.is_current = TRUE\nWHEN MATCHED AND target.address <> source.address\n  THEN UPDATE SET target.end_date = CURRENT_DATE(), target.is_current = FALSE\nWHEN NOT MATCHED\n  THEN INSERT (customer_id, address, start_date, end_date, is_current)\n  VALUES (source.customer_id, source.address, CURRENT_DATE(), NULL, TRUE);\n\n❌ Why others are wrong:\n• (A) Time Travel VERSION AS OF: Provides read-only snapshots but doesn't create persistent SCD records. When data files are VACUUMed, historical versions are lost.\n• (C) Auto Loader: Auto Loader ingests files — it doesn't implement SCD logic.\n• (D) OPTIMIZE with ZORDER: Optimizes FILE LAYOUT for query performance, not record versioning.\n• (E) Change Data Feed creates SCD: CDF tracks row-level changes but doesn't automatically create SCD tables.\n\n🔑 EXAM TIP: SCD Types:\n• Type 1: Overwrite old values (no history)\n• Type 2: Add new row with version tracking (start_date, end_date, is_current)\n• Type 3: Add new column for previous value (limited history)\n• Delta Lake + MERGE INTO = standard SCD Type 2 implementation`,

  "db-da-320": `✅ CORRECT (B — Historical records have inconsistent category values): When dimension attributes are embedded directly in the fact table (denormalized), a change to the dimension (e.g., product reclassified to a different category) only affects NEW records. Historical records retain the OLD category value — creating data inconsistency.\n\n❌ Why others are wrong:\n• (A) Always denormalize: FALSE. Denormalization has trade-offs. Star schema with separate dimension tables is preferred for maintaining consistency.\n• (C) Can't use GROUP BY: FALSE. GROUP BY works on any table structure.\n• (D) Only storage cost: FALSE. The analytical impact (inconsistent categories) is the PRIMARY concern, not storage.\n• (E) Prevents Time Travel: FALSE. Time Travel is a Delta Lake feature independent of table denormalization.\n\n🔑 EXAM TIP: Update anomalies in denormalized tables:\n• Product reclassification → old fact records have stale category\n• Customer address change → old transactions show previous address\n• Solution: Use star schema with separate dimension tables\n• SCD Type 2 in dimensions handles history correctly`,

  "db-da-331": `✅ CORRECT (C — Materialized Delta TABLE via CTAS): For 20 concurrent dashboard users, a pre-computed Delta table is the best choice:\n• Pre-computed: No redundant aggregation on each access\n• Concurrent reads: Delta Lake handles many simultaneous readers efficiently\n• Persistent: Survives sessions, scheduled maintenance possible\n\n❌ Why others are wrong:\n• (A) TEMPORARY VIEW: Session-scoped — disappears when the creator logs out. Other users can't access it.\n• (B) VIEW with fresh data: Re-executes the heavy query for each of 20 concurrent users — creates significant compute load.\n• (D) GLOBAL TEMPORARY VIEW: Cluster-scoped (not truly global). Dropped when cluster stops. Not suitable for production dashboards.\n• (E) All perform identically: FALSE. Materialized tables significantly outperform views for concurrent access.\n\n🔑 EXAM TIP: Gold layer object selection:\n• High concurrency + large data → Materialized TABLE (CTAS)\n• Low concurrency + must be fresh → VIEW\n• Session-only analysis → TEMPORARY VIEW\n• Automatic refresh needed → MATERIALIZED VIEW (Pro/Serverless warehouse)`,

  "db-da-332": `✅ CORRECT (B — VACUUM removed data files that version 5 referenced): VACUUM with RETAIN 24 HOURS permanently deletes data files older than 24 hours that are no longer referenced by the CURRENT table version. Version 5's data files (which were part of an older snapshot) were deleted, so the Time Travel query can't reconstruct that version.\n\n❌ Why others are wrong:\n• (A) Transaction log entries deleted: VACUUM does NOT delete transaction log entries. The log has its own separate retention period (30 days).\n• (C) Version counter resets: FALSE. Delta Lake version numbers are monotonically increasing and never reset.\n• (D) Time Travel disabled: FALSE. Time Travel is not "disabled" by VACUUM. It fails only for versions whose data files have been removed.\n• (E) Only affects metadata: FALSE. VACUUM specifically removes DATA FILES, not metadata.\n\n🔑 EXAM TIP: VACUUM + Time Travel interaction:\n• VACUUM removes: data files older than retention period\n• VACUUM does NOT remove: transaction log entries\n• Result: DESCRIBE HISTORY still shows old versions, but querying them FAILS\n• Prevention: Never set retention below 7 days in production\n• Recovery: Once VACUUMed, data is PERMANENTLY gone — no recovery`
};

const filePath = './questions_databricks.js';
let content = fs.readFileSync(filePath, 'utf-8');

let upgraded = 0, failed = 0;

global.window = { questionsData: [] };
require(filePath);
const questions = window.questionsData;

for (const [id, newExpl] of Object.entries(upgrades)) {
  const escapedExpl = newExpl.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
  
  // Try finding by ID marker in file content first
  const idMarker = `"${id}"`;
  let idIdx = content.indexOf(idMarker);
  
  if (idIdx === -1) {
    console.log(`❌ ${id} not found by ID marker`);
    failed++;
    continue;
  }
  
  const explStart = content.indexOf('"explanation":', idIdx);
  if (explStart === -1 || explStart - idIdx > 5000) {
    console.log(`❌ ${id} explanation not in range`);
    failed++;
    continue;
  }
  
  const valueStart = content.indexOf('"', explStart + '"explanation":'.length);
  if (valueStart === -1) {
    console.log(`❌ ${id} value start not found`);
    failed++;
    continue;
  }
  
  let valueEnd = valueStart + 1;
  while (valueEnd < content.length) {
    if (content[valueEnd] === '\\') { valueEnd += 2; continue; }
    if (content[valueEnd] === '"') break;
    valueEnd++;
  }
  
  content = content.substring(0, valueStart) + '"' + escapedExpl + '"' + content.substring(valueEnd + 1);
  console.log(`✅ ${id} upgraded`);
  upgraded++;
}

fs.writeFileSync(filePath, content, 'utf-8');
console.log(`\nDone! Upgraded ${upgraded}/${Object.keys(upgrades).length}`);
if (failed > 0) console.log(`Failed: ${failed}`);

try {
  delete require.cache[require.resolve(filePath)];
  global.window = { questionsData: [] };
  require(filePath);
  console.log(`✅ File valid! Total questions: ${window.questionsData.length}`);
} catch(e) {
  console.log(`❌ Syntax error: ${e.message.substring(0, 300)}`);
}
