/**
 * Script to upgrade all Importing Data explanations with deep, exam-focused analysis.
 * Each explanation now covers:
 *   - WHY the correct answer is right (with technical detail)
 *   - WHY each wrong option is wrong (with specific reasoning)
 *   - KEY CONCEPT to remember for the exam
 */
const fs = require('fs');
const filePath = 'questions_databricks.js';
let content = fs.readFileSync(filePath, 'utf-8');

const upgrades = {
  'db-da-4': `"explanation": "✅ CORRECT (D): Partner Connect creates a SQL WAREHOUSE (not a cluster) for Fivetran. This is key — Fivetran is a data ingestion tool that connects via SQL interface, so it needs a SQL Warehouse endpoint.\\n\\n❌ Why others are wrong:\\n• (A) Workflows: Workflows orchestrate jobs/notebooks, they don't create SQL endpoints for external tools.\\n• (B) Delta Live Tables: DLT defines data pipelines, not connection endpoints for 3rd-party tools.\\n• (C) Partner Connect + cluster: Close, but Partner Connect creates a SQL Warehouse, NOT a cluster. Clusters are for notebooks/Spark jobs.\\n• (E) Workflows + cluster: Same issue — Workflows don't create connection endpoints.\\n\\n🎯 EXAM TIP: Partner Connect = automated setup wizard. For BI/ingestion tools, it always provisions a SQL Warehouse (the SQL interface), never a general-purpose cluster.",`,

  'db-da-8': `"explanation": "✅ CORRECT (E): To ingest from cloud storage (S3/ADLS/GCS), you create an external table with a LOCATION clause pointing to the object storage path (e.g., 's3://bucket/path/'). The key is using the cloud-native URL format.\\n\\n❌ Why others are wrong:\\n• (A, B) DBFS path: DBFS (Databricks File System) is an internal abstraction layer. While DBFS can mount external storage, specifying a 'DBFS storage path' is NOT the same as directly ingesting from cloud storage. The question asks about DIRECT ingestion.\\n• (C) 'Not possible': Completely false — Databricks natively supports external tables on cloud storage.\\n• (D) Object storage + DBFS storage path: Contradictory. If you're pointing to object storage, you use the object storage URL, not a DBFS path.\\n\\n🎯 EXAM TIP: CREATE EXTERNAL TABLE + LOCATION 'cloud-url' = direct cloud ingestion. DBFS paths (dbfs:/) are the legacy internal filesystem.",`,

  'db-da-67': `"explanation": "✅ CORRECT (A): Partner Connect does THREE things when connecting BI tools (Power BI/Tableau):\\n1. Creates a Personal Access Token (PAT) for authentication\\n2. Downloads/installs the ODBC/JDBC driver needed for connectivity\\n3. Downloads a pre-configured connection file (.dbc or .tds) with server hostname, HTTP path, and credentials\\n\\n❌ Why others are wrong:\\n• (B) 'Creates PAT and emails it': Partner Connect creates the PAT but configures it directly in the connection file — it doesn't email anything.\\n• (C) 'Downloads config file only': Incomplete — it also handles driver installation and PAT creation. The power of Partner Connect is that it automates ALL steps, not just one.\\n• (D) 'ODBC driver only': Same issue — this is only 1 of 3 steps.\\n\\n🎯 EXAM TIP: Partner Connect = FULL automation (PAT + Driver + Config File). If an answer mentions only a partial step, it's wrong.",`,

  'db-da-71': `"explanation": "✅ CORRECT (B): Partner Connect enables MULTI-DIRECTIONAL connections between Databricks and partner ecosystems. This means:\\n- Inbound: Ingestion tools (Fivetran, Airbyte) push data INTO Databricks\\n- Outbound: BI tools (Tableau, Power BI) pull data FROM Databricks\\n- It exposes the necessary connection info (hostname, PAT, warehouse ID) for both directions.\\n\\n❌ Why others are wrong:\\n• (A) 'Free use': Partner Connect does NOT make partner tools free. It simplifies the CONNECTION setup, but you still need licenses for Fivetran, Tableau, etc.\\n• (C) 'Exposes connection info via Databricks': This is partially true but too narrow — Partner Connect doesn't just expose info, it actively automates the setup (creating SQL warehouses, PATs, config files).\\n• (D) 'Runs partner tools on Databricks': Partner tools run on their OWN infrastructure. Partner Connect just bridges the connection — it doesn't host the tools.\\n\\n🎯 EXAM TIP: Partner Connect = connection automation hub. It's NOT a hosting platform and NOT a free license program.",`,

  'db-da-80': `"explanation": "✅ CORRECT (A): For a small, 50-row CSV lookup file, the CREATE TABLE UI (drag-and-drop) is the simplest approach. In Databricks SQL, go to Create → Upload File → drag your CSV → it auto-detects schema → creates a managed Delta table.\\n\\n❌ Why others are wrong:\\n• (B) 'Connection to data store': Overkill — this implies setting up a full ingestion pipeline (Fivetran/Partner Connect) for a tiny file. That's designed for continuous, large-scale data flows.\\n• (C) 'Upload to cloud storage first': Unnecessary extra step — why upload to S3/ADLS first when you can directly upload through the UI? This adds complexity for no benefit.\\n• (D) 'Copy-paste data values': Not a real Databricks feature. There's no copy-paste table creation wizard. Even if there were, it would be error-prone for structured data.\\n\\n🎯 EXAM TIP: Small file (< few hundred rows) + one-time upload = UI drag-and-drop. Large/continuous ingestion = Auto Loader or COPY INTO. Complex pipeline = Partner Connect/Fivetran.",`,

  'db-da-111': `"explanation": "✅ CORRECT (A): read_files() with 'cloud_files' format invokes Auto Loader, which is specifically designed for:\\n1. INCREMENTAL ingestion (processes only new files, not re-reading old ones)\\n2. SCHEMA EVOLUTION (automatically adds new columns without breaking existing data)\\n3. It maintains checkpoints to track which files have been processed.\\n\\n❌ Why others are wrong:\\n• (B) COPY INTO with defaults: COPY INTO tracks processed files but does NOT support automatic schema evolution by default. You'd need mergeSchema = true, and even then it's less robust than Auto Loader for frequent schema changes.\\n• (C) INSERT INTO ... SELECT FROM json.path: This re-reads ALL files every time (no idempotency), and has NO schema evolution support. Running this repeatedly creates duplicates.\\n• (D) CREATE EXTERNAL TABLE: This creates a pointer to the files but doesn't actively ingest or evolve schema. It's a read-only reference, not an ingestion mechanism.\\n\\n🎯 EXAM TIP: Frequent schema changes + incremental load = Auto Loader (read_files with cloud_files). COPY INTO = simpler idempotent load but limited schema evolution.",`,

  'db-da-114': `"explanation": "✅ CORRECT (B): Databricks Marketplace data products appear as a READ-ONLY CATALOG (or schema) in Unity Catalog. This uses 'Delta Sharing' under the hood — the provider shares data WITHOUT copying it (Zero-Copy Sharing). You can query it immediately with SELECT *.\\n\\n❌ Why others are wrong:\\n• (A) 'CSV files in DBFS': Marketplace data is NOT raw files. It's shared as governed Delta tables through Unity Catalog, not dumped as CSVs.\\n• (C) 'As a Dashboard': Dashboards are visualizations, not data storage. Marketplace provides DATA, not pre-built dashboards.\\n• (D) 'Download via API': No download needed — the whole point of Delta Sharing is that data appears instantly in your catalog without manual download or ETL.\\n\\n🎯 EXAM TIP: Marketplace = read-only catalog in Unity Catalog via Delta Sharing (zero-copy). No ETL, no downloads, no file management needed. Just query it.",`,

  'db-da-124': `"explanation": "✅ CORRECT (A): mergeSchema = true tells COPY INTO to ADD any new columns found in the source file to the target Delta table's schema. Existing columns remain unchanged, new columns get added. This is called SCHEMA EVOLUTION.\\n\\n❌ Why others are wrong:\\n• (B) overwriteSchema = true: This REPLACES the entire schema with the new one — it doesn't merge. This would DELETE existing columns not present in the new file. Dangerous!\\n• (C) enforceSchema = false: This option doesn't exist in COPY INTO. The real option is mergeSchema. Databricks enforces schema by default.\\n• (D) autoEvolve = true: This is NOT a valid COPY INTO option. autoEvolve is used in Delta Live Tables (DLT), not in COPY INTO/Spark writes.\\n\\n🎯 EXAM TIP: mergeSchema = ADD new columns (safe). overwriteSchema = REPLACE entire schema (dangerous). For the exam, COPY INTO uses mergeSchema; DLT uses schema evolution policies.",`,

  'db-da-136': `"explanation": "✅ CORRECT (C): Upload File via the Databricks SQL UI is the best fit because:\\n1. It's a SMALL file (20 rows) — no need for streaming/batch infrastructure\\n2. No cloud storage access — eliminates Auto Loader and COPY INTO (both need a cloud storage path)\\n3. It creates a managed Delta table directly from the UI (drag-and-drop)\\n\\n❌ Why others are wrong:\\n• (A) Auto Loader: Requires files to be in cloud object storage (S3/ADLS/GCS). The analyst has NO storage access, so Auto Loader can't reach the file.\\n• (B) COPY INTO: Same issue — needs a cloud storage path or external location. Without storage access, there's no path to point to.\\n• (D) Delta Sharing: This is for sharing data BETWEEN organizations, not for uploading local files.\\n• (E) CREATE TABLE AS SELECT: This requires querying an existing data source. There's no source table to SELECT from yet — the data is in a local CSV.\\n\\n🎯 EXAM TIP: No cloud storage access + small local file = UI Upload. This is the ONLY option that works without external storage configuration.",`,

  'db-da-152': `"explanation": "✅ CORRECT (C): FLOW AUTO CDC in streaming tables is purpose-built for CDC processing. It automatically:\\n1. Handles INSERTs, UPDATEs, and DELETEs based on a primary key\\n2. Manages OUT-OF-ORDER records using a sequence column (e.g., timestamp)\\n3. Supports SCD Type 1 (overwrite current) and SCD Type 2 (track history)\\n\\nSyntax: APPLY FLOW AUTO CDC INTO target FROM source KEYS (id) SEQUENCE BY (ts)\\n\\n❌ Why others are wrong:\\n• (A) MERGE INTO with manual logic: Works but requires you to manually write all the WHEN MATCHED / WHEN NOT MATCHED logic, handle out-of-order records yourself, and manage SCD manually. Much more complex and error-prone.\\n• (B) COPY INTO with schema evolution: COPY INTO only APPENDS data — it has NO concept of updates or deletes. It cannot process CDC records.\\n• (D) INSERT OVERWRITE: This replaces ALL data in the table, not individual records. No CDC capability.\\n• (E) CREATE VIEW with filtering: Views don't modify data. This would just filter the view of CDC records without actually applying them.\\n\\n🎯 EXAM TIP: CDC processing = FLOW AUTO CDC (managed, automatic). MERGE INTO = manual alternative. COPY INTO = append-only (no updates/deletes).",`,

  'db-da-231': `"explanation": "✅ CORRECT (B): Auto Loader is the recommended solution for incremental cloud storage ingestion because:\\n1. AUTOMATIC CHECKPOINTING: Tracks which files have been processed — never re-processes a file\\n2. SCHEMA EVOLUTION: cloudFiles.schemaEvolution = true handles new/changed fields\\n3. SCALABLE: Handles millions of small files efficiently using file notification mode\\n4. NO CUSTOM CODE needed for state management\\n\\n❌ Why others are wrong:\\n• (A) Custom Spark Structured Streaming: Works but requires YOU to build file tracking, checkpoint management, schema handling, and error recovery. Auto Loader does all this automatically.\\n• (C) Custom API pipeline: Pulling data from S3 via API is architecturally wrong — S3 doesn't have a streaming API. You'd scan the bucket repeatedly. Auto Loader uses native cloud notifications.\\n• (D) Delta Sharing: This shares data BETWEEN organizations. It doesn't ingest files from your own S3 bucket.\\n\\n🎯 EXAM TIP: Cloud storage + continuous ingestion + schema evolution = Auto Loader. Custom streaming = only if you need logic Auto Loader can't provide.",`,

  'db-da-283': `"explanation": "✅ CORRECT (A): The Create Table UI (drag-and-drop) is the ONLY fully no-code solution. Key features:\\n1. Drag and drop the CSV directly in the Databricks workspace\\n2. Auto-detects schema (column names, types)\\n3. Creates a MANAGED Delta table in Unity Catalog (automatically governed)\\n4. Requires ZERO SQL, ZERO cloud storage configuration\\n\\n❌ Why others are wrong:\\n• (B) Auto Loader: While 'low-code', Auto Loader still requires SQL/Python commands (CREATE STREAMING TABLE + read_files). It's designed for continuous cloud storage ingestion, not one-off file uploads.\\n• (C) SQL Batch ingestion (COPY INTO): Requires writing SQL code (COPY INTO ... FROM ... FILEFORMAT = CSV). Not 'no-code'.\\n• (D) Notebook scheduled ETL: The most complex option — requires writing code in a notebook AND setting up a scheduled workflow. Opposite of no-code.\\n\\n🎯 EXAM TIP: 'No-code' in the exam ALWAYS means the UI drag-and-drop. Any option requiring SQL or Python is at minimum 'low-code'.",`,

  'db-da-286': `"explanation": "✅ CORRECT (B): The 'rescue' schema evolution mode stores mismatched data in a special _rescued_data column (JSON format). This means:\\n1. If a column expected as INT arrives as STRING → the row is NOT rejected\\n2. The valid columns are loaded normally\\n3. The mismatched value goes to _rescued_data for manual review\\n4. Extra/unexpected columns also go to _rescued_data\\n\\n❌ Why others are wrong:\\n• (A) 'failFast' mode: This ABORTS the entire load on the FIRST schema mismatch. Good for strict pipelines but terrible for inconsistent data — you'd never finish loading.\\n• (C) 'Automatic by default': While Auto Loader does have sensible defaults, the _rescued_data column is NOT enabled by default in all configurations. You need to explicitly enable rescuedDataColumn.\\n• (D) 'addNewColumns' mode: This mode ADDS new columns to the schema but does NOT rescue type mismatches. If a numeric column arrives as string, it fails rather than rescuing.\\n\\n🎯 EXAM TIP: rescue mode = capture mismatches without failing. failFast = abort on error. addNewColumns = evolve schema but strict on types.",`,

  'db-da-287': `"explanation": "✅ CORRECT (C): COPY INTO with VALIDATE ALL performs a DRY RUN that:\\n1. Reads and parses all source files\\n2. Checks for format errors (wrong delimiters, encoding issues)\\n3. Checks for schema mismatches (wrong column count, type errors)\\n4. Reports errors WITHOUT writing any data to the target table\\n\\nSyntax: COPY INTO target FROM path FILEFORMAT = CSV VALIDATE ALL\\n\\n❌ Why others are wrong:\\n• (A) 'DRY RUN': This clause does NOT exist in Databricks SQL. It's not valid syntax.\\n• (B) SELECT * FROM read_files LIMIT 10: This shows you 10 rows of data but doesn't systematically validate ALL files for errors. You might miss corrupted rows beyond the first 10.\\n• (D) 'CHECK ERROR': This clause does NOT exist in Databricks SQL. Not valid syntax.\\n\\n🎯 EXAM TIP: VALIDATE ALL is the only pre-check for COPY INTO. It validates without writing. Remember: VALIDATE ALL (all rows) or VALIDATE <n> (specific number of rows).",`,

  'db-da-288': `"explanation": "✅ CORRECT (C): File Notification mode (cloudFiles.useNotifications = true) uses cloud-native event services:\\n- AWS: SQS + SNS (S3 event notifications → SQS queue)\\n- Azure: Event Grid (Blob storage events)\\n- GCP: Pub/Sub (GCS notifications)\\n\\nInstead of scanning millions of files, Databricks only processes files that triggered a notification. This reduces:\\n1. API calls to storage (no LIST operations)\\n2. Processing time (from hours to seconds for new file discovery)\\n3. Cost (fewer API calls = lower cloud bills)\\n\\n❌ Why others are wrong:\\n• (A) 'Increase SQL Warehouse size': Bigger compute doesn't fix the directory scanning bottleneck. The problem is the NUMBER of API calls to list files, not processing power.\\n• (B) COPY INTO with modifiedAfter: COPY INTO still needs to SCAN the directory to find files modified after the timestamp. With millions of files, this scan itself is the bottleneck.\\n• (D) RESTORE command: RESTORE reverts a Delta table to a previous version. It has NOTHING to do with file discovery or ingestion.\\n\\n🎯 EXAM TIP: Millions of files + slow discovery = File Notification mode. This is an Auto Loader feature, not available in COPY INTO.",`,

  'db-da-289': `"explanation": "✅ CORRECT (B): DESCRIBE HISTORY shows the complete transaction log for a Delta table, including:\\n- Operation type (COPY INTO, WRITE, OPTIMIZE, MERGE, etc.)\\n- Timestamp of each operation\\n- operationMetrics: files added, rows inserted, bytes written\\n- operationParameters: source file paths, format options used\\n- userName: who performed the operation\\n\\nThis is exactly what you need to audit which files were loaded and when.\\n\\n❌ Why others are wrong:\\n• (A) table_changes(): This is for Change Data Feed (CDF) — it shows ROW-LEVEL changes (what data changed), not FILE-LEVEL audit info. It doesn't tell you which files were ingested.\\n• (C) SHOW TBLPROPERTIES: Shows table configuration (owner, location, format, etc.) but NOT transaction history or file-level audit information.\\n• (D) DESCRIBE DETAIL: Shows current table metadata (location, size, number of files, format) but NOT the history of operations or which files were loaded.\\n\\n🎯 EXAM TIP: DESCRIBE HISTORY = transaction audit log (who did what, when, which files). DESCRIBE DETAIL = current table snapshot. table_changes = CDF row-level changes.",`,

  'db-da-290': `"explanation": "✅ CORRECT (A): Unity Catalog's external access model has a strict 2-layer hierarchy:\\n\\n1️⃣ STORAGE CREDENTIAL → holds the cloud IAM identity (Azure Service Principal, AWS IAM Role, GCP Service Account)\\n2️⃣ EXTERNAL LOCATION → maps a storage path (e.g., abfss://container@account/) to a Storage Credential\\n\\nThe question asks what's needed FIRST — you must create the Storage Credential before you can define an External Location. Without the credential, there's no way to authenticate to the cloud storage.\\n\\n❌ Why others are wrong:\\n• (B) External Location: This is needed too, but it DEPENDS on a Storage Credential. You can't create an External Location without first having a credential. The question asks what's needed to 'define a path' — the credential is the foundation.\\n• (C) Volume: Volumes are for managing individual files within Unity Catalog (like a folder), not for defining access to external storage containers.\\n• (D) Managed Table: Managed tables store data IN Databricks' own storage. The question is about EXTERNAL storage (ADLS Gen2), which requires external access configuration.\\n\\n🎯 EXAM TIP: Credential → Location → External Table. This order is ALWAYS the same. Credential = WHO can access. Location = WHERE they can access. Table = WHAT data to expose.",`,

  'db-da-342': `"explanation": "✅ CORRECT (B): COPY INTO is designed specifically for IDEMPOTENT incremental ingestion:\\n1. Tracks processed files using file-level checksums stored in the Delta transaction log\\n2. On subsequent runs, automatically SKIPS already-processed files\\n3. Only new/unprocessed files are loaded → no duplicates\\n\\nSyntax: COPY INTO target_table FROM 's3://...' FILEFORMAT = JSON\\n\\n❌ Why others are wrong:\\n• (A) INSERT INTO ... SELECT: Re-reads ALL files in the directory every single run. Run it 5 times = 5x duplicated data. No file tracking mechanism.\\n• (C) CREATE TABLE AS SELECT: Creates a NEW table each time. Doesn't support incremental appends. Only useful for one-time table creation.\\n• (D) MERGE INTO: Can deduplicate records using a key, but still RE-READS all source files every time. More expensive and complex than COPY INTO for simple append scenarios.\\n• (E) LOAD DATA INPATH: This is a Hive command, not supported in Databricks SQL. Even in Hive, it moves files rather than copying them.\\n\\n🎯 EXAM TIP: 'Idempotent' in the exam = COPY INTO or Auto Loader. INSERT INTO = always creates duplicates. MERGE = deduplicates rows but re-reads all files.",`,

  'db-da-343': `"explanation": "✅ CORRECT (A): The correct COPY INTO configuration for this scenario:\\n- delimiter = '|' (pipe-separated)\\n- dateFormat = 'dd-MM-yyyy' (custom date parsing)\\n- header = 'true' (first row is column names)\\n- mode = 'PERMISSIVE' (malformed rows get NULL values instead of failing)\\n\\nFull syntax:\\nCOPY INTO target FROM '/path' FILEFORMAT = CSV\\nFORMAT_OPTIONS('delimiter'='|', 'dateFormat'='dd-MM-yyyy', 'header'='true')\\nCOPY_OPTIONS('mode'='PERMISSIVE')\\n\\n❌ Why others are wrong:\\n• (B) mode = 'FAILFAST': Aborts the ENTIRE load on the FIRST malformed row. With 2GB of real-world data containing known quality issues, this would almost certainly fail immediately.\\n• (C) FILEFORMAT = PARQUET: The source file is CSV, not Parquet. PARQUET format can't parse pipe-delimited text files.\\n• (D) INSERT INTO ... SELECT: No FORMAT_OPTIONS support — you can't specify custom delimiters or date formats with INSERT INTO.\\n• (E) mode = 'DROPMALFORMED': Silently DROPS bad rows entirely. You lose data without knowing it. PERMISSIVE is safer because it keeps the row with NULLs for review.\\n\\n🎯 EXAM TIP: PERMISSIVE = keep rows with nulls (safest). FAILFAST = abort on error. DROPMALFORMED = silently delete bad rows (data loss risk).",`,

  'db-da-344': `"explanation": "✅ CORRECT (A): Databricks supports direct file path querying with the syntax: format.\\x60path\\x60\\n\\nExamples:\\n- SELECT * FROM parquet.\\x60s3://bucket/data/\\x60\\n- SELECT * FROM json.\\x60s3://bucket/logs/\\x60\\n- SELECT * FROM csv.\\x60s3://bucket/files/\\x60\\n\\nThis is called PATH-BASED querying. Backticks around the path are REQUIRED. No table registration needed — perfect for ad-hoc exploration.\\n\\n❌ Why others are wrong:\\n• (B) 'SELECT FROM EXTERNAL ... FORMAT': This syntax doesn't exist in Databricks SQL. Not valid.\\n• (C) MOUNT + SELECT: MOUNT is a LEGACY approach (pre-Unity Catalog). Modern Databricks uses External Locations instead. Also, MOUNT requires admin privileges.\\n• (D) CREATE TEMP VIEW AS PARQUET: This syntax is invalid. TEMP VIEWs are created with SQL queries, not format declarations.\\n• (E) 'Not possible': Completely false — path-based querying is a core Databricks feature.\\n\\n🎯 EXAM TIP: format.\\x60path\\x60 with backticks = instant ad-hoc querying. No registration, no table creation. Works for parquet, json, csv, delta, avro.",`,

  'db-da-345': `"explanation": "✅ CORRECT (A): REFRESH TABLE forces Databricks to rescan the external location and update its metadata cache. This is necessary because:\\n1. External tables point to data managed OUTSIDE Databricks\\n2. When external systems add files, Databricks' metadata cache doesn't know about them\\n3. REFRESH TABLE triggers a full rescan of the LOCATION path\\n\\nSyntax: REFRESH TABLE analytics.ext_logs\\n\\n❌ Why others are wrong:\\n• (B) 'Drop and recreate': Overkill and risky — you'd lose table metadata, permissions, and any views that depend on this table.\\n• (C) VACUUM: VACUUM removes old, unused data files from MANAGED Delta tables. It does NOT scan external locations for new files. Completely unrelated operation.\\n• (D) 'Appears automatically': True for MANAGED Delta tables (which use a transaction log), but FALSE for external tables pointing to non-Delta formats. External tables cache metadata and need manual refresh.\\n• (E) COPY INTO: This is for loading data INTO a table, not for refreshing metadata of an existing external table.\\n\\n🎯 EXAM TIP: External table + new files not appearing = REFRESH TABLE. Managed Delta table = automatic (uses transaction log). This distinction is a common exam trap.",`,

  'db-da-346': `"explanation": "✅ CORRECT (E): Both approaches are valid for different use cases:\\n\\n📌 Option B (Fivetran/Partner Connect):\\n- PHYSICAL REPLICATION: Copies data from PostgreSQL into a Delta table\\n- Best for: Frequent queries, low-latency dashboards, heavy analytics\\n- CDC support: Fivetran tracks changes and syncs incrementally\\n- Trade-off: Data has some latency (minutes to hours behind source)\\n\\n📌 Option D (Lakehouse Federation):\\n- VIRTUAL TABLE: Queries PostgreSQL directly without copying data\\n- Best for: Real-time freshness, infrequent queries, compliance (data stays in source)\\n- Trade-off: Slower queries (network round-trip to PostgreSQL each time)\\n\\n❌ Why others are wrong:\\n• (A) COPY INTO with JDBC: COPY INTO doesn't support JDBC connections. It's designed for file-based ingestion (CSV, JSON, Parquet from cloud storage), not database connections.\\n• (C) CSV export daily: Manual, error-prone, no automation, no CDC. This is 2010-era data engineering.\\n\\n🎯 EXAM TIP: Physical copy (Fivetran) = speed + latency. Virtual table (Federation) = freshness + cost. Both are valid = 'Both B and D' answers are common on the exam.",`,

  'db-da-347': `"explanation": "✅ CORRECT (B): When you upload a file through the Databricks UI, it becomes a MANAGED DELTA TABLE in Unity Catalog. This means:\\n1. Data is stored in the managed storage location of the target schema/catalog\\n2. The table is PERSISTENT — it survives session restarts and is accessible to other users\\n3. It's fully governed by Unity Catalog (permissions, lineage, audit)\\n4. Format is always Delta (even if you uploaded CSV, it converts to Delta)\\n\\n❌ Why others are wrong:\\n• (A) 'Temporary session-scoped table': The uploaded data is PERMANENT, not temporary. It persists after you close your browser.\\n• (C) 'Control Plane cached dataset': The Control Plane manages cluster orchestration and workspace metadata — it doesn't store user data.\\n• (D) 'Personal workspace folder CSV': The data is converted from CSV to Delta format and stored in cloud storage, NOT attached as a raw file to your workspace.\\n• (E) 'External S3 bucket': UI uploads create MANAGED tables (Databricks controls the storage location). No external storage configuration is needed.\\n\\n🎯 EXAM TIP: UI Upload = always creates a MANAGED Delta table. Managed = Databricks controls storage lifecycle. External = YOU control storage.",`,

  'db-da-348': `"explanation": "✅ CORRECT (B): In Databricks SQL, STRUCT fields use DOT NOTATION for nested access:\\n\\nuser.address.city\\n\\nSince the JSON was loaded into a STRUCT column (not a raw JSON string), the data is already parsed. Dot notation navigates the STRUCT hierarchy directly.\\n\\n❌ Why others are wrong:\\n• (A) user->address->city: Arrow notation (->) is used in PostgreSQL and MySQL, NOT in Databricks SQL. Databricks uses dot notation for STRUCTs.\\n• (C) GET_JSON_OBJECT(user, '$.address.city'): This function is for parsing RAW JSON STRINGS (type STRING), not STRUCT columns. Since the column is already a STRUCT, the data is already parsed — no need for JSON extraction.\\n• (D) user['address']['city']: Bracket notation is for MAP columns (key-value pairs) and ARRAY columns (index access), NOT for STRUCTs. STRUCT = dot, MAP = brackets, ARRAY = brackets with index.\\n• (E) FLATTEN(user).city: FLATTEN is for exploding ARRAY columns into rows, not for navigating STRUCT fields.\\n\\n🎯 EXAM TIP: STRUCT = dot.notation (user.address.city). MAP = brackets['key']. ARRAY = brackets[0]. JSON STRING = GET_JSON_OBJECT or json_column:path syntax.",`,

  'db-da-349': `"explanation": "✅ CORRECT (B): Unity Catalog requires an EXTERNAL LOCATION to be registered before you can create an external table pointing to that path. The access chain is:\\n\\n1. Storage Credential → authenticates to cloud provider (Service Principal / IAM Role)\\n2. External Location → maps a storage path (abfss://...) to a credential\\n3. External Table → references the External Location path\\n\\nWithout step 2, Unity Catalog blocks the CREATE TABLE because the path 'abfss://...' is not registered.\\n\\n❌ Why others are wrong:\\n• (A) 'LOCATION URL syntax incorrect': The abfss:// syntax IS correct for ADLS Gen2. The problem isn't syntax — it's the missing External Location registration.\\n• (C) 'External tables only for S3': False — Unity Catalog supports external tables on S3, ADLS Gen2, and GCS. All three major cloud providers.\\n• (D) 'MOUNT first': MOUNT is a LEGACY approach that bypasses Unity Catalog governance. Modern Databricks uses External Locations instead of MOUNTs.\\n• (E) 'UC doesn't support external tables': Completely false. Unity Catalog fully supports external tables — it just requires proper governance objects (credential + location).\\n\\n🎯 EXAM TIP: Missing External Location is the #1 reason CREATE EXTERNAL TABLE fails. Always check: Credential → Location → Table."`
};

// Perform replacements
let count = 0;
for (const [id, newExplanation] of Object.entries(upgrades)) {
  // Find the line with "explanation" for this question
  const idPattern = `"id": "${id}"`;
  const idIndex = content.indexOf(idPattern);
  if (idIndex === -1) {
    console.error(`Could not find question ${id}`);
    continue;
  }

  // Find the explanation line after the id
  const afterId = content.substring(idIndex);
  const explMatch = afterId.match(/"explanation":\s*"(?:[^"\\]|\\.)*"/);
  if (!explMatch) {
    console.error(`Could not find explanation for ${id}`);
    continue;
  }

  const oldExplanation = explMatch[0];
  const fullOldIndex = idIndex + afterId.indexOf(oldExplanation);
  
  // Replace
  content = content.substring(0, fullOldIndex) + newExplanation + content.substring(fullOldIndex + oldExplanation.length);
  count++;
  console.log(`✅ ${id} explanation upgraded`);
}

fs.writeFileSync(filePath, content, 'utf-8');
console.log(`\nDone! Upgraded ${count}/25 Importing Data explanations.`);
