/**
 * Upgrade Dashboards & Visualizations Explanations
 * Deep-dive, exam-focused analysis for all 40 questions
 */
const fs = require('fs');

const upgrades = {
  "db-da-7": `✅ CORRECT (A): The compute cost caution is the right answer. Refreshing a dashboard every minute means the SQL Warehouse must execute ALL underlying queries every 60 seconds. SQL Warehouses bill per DBU-hour of compute used — continuous querying at this frequency can generate significant costs, especially with complex queries on large tables.\n\n❌ Why others are wrong:\n• (B) Gold-level tables NOT clean: Gold tables ARE the business-ready layer in the medallion architecture (Bronze→Silver→Gold). They are already cleaned and aggregated.\n• (C) Streaming data inappropriate for dashboards: Streaming data is perfectly valid for dashboards. Databricks supports near-real-time dashboards backed by streaming pipelines.\n• (D) Streaming cluster not fault tolerant: Structured Streaming has built-in fault tolerance via checkpointing. This is not a valid concern.\n• (E) Dashboard cannot refresh that quickly: Databricks dashboards CAN refresh every minute. The minimum schedule interval is 1 minute.\n\n🔑 EXAM TIP: The exam tests your understanding of COST implications. Frequent dashboard refreshes = frequent SQL Warehouse usage = higher DBU costs. Always consider the compute cost trade-off when setting refresh intervals.`,

  "db-da-9": `✅ CORRECT (C): Markdown-based text boxes are the designated tool for adding formatted text sections to Databricks dashboards. In both Legacy and AI/BI Dashboards, you can add a 'Text' widget that supports full Markdown syntax — headings (#, ##, ###), bold, italic, lists, and horizontal rules — perfect for creating visual section dividers.\n\n❌ Why others are wrong:\n• (A) Separate endpoints: Endpoints (SQL Warehouses) are compute resources, not dashboard design elements. They have nothing to do with visual layout.\n• (B) Separate queries: Queries return data. They don't create visual text labels or section headers in the dashboard canvas.\n• (D) Direct text in editing mode: There is no raw text input mode in the dashboard editor. All text content goes through Markdown-based text widgets.\n• (E) Separate color palettes: Color palettes style chart visualizations — they don't create text-based section labels.\n\n🔑 EXAM TIP: Markdown text boxes are the ONLY way to add descriptive text, headings, and section dividers in a Databricks dashboard. Remember: Markdown widget = text/formatting; Visualization widget = charts/data.`,

  "db-da-33": `✅ CORRECT (E): This is the INCORRECT statement. You do NOT need workspace administrator privileges to configure a refresh schedule. Any user who owns the query or has 'Can Manage' permissions on it can set up a schedule. This is a common exam trap — confusing query-level permissions with workspace-level admin roles.\n\n❌ Why others are actually TRUE (and thus not the answer):\n• (A) TRUE: Refresh schedules range from every 1 minute to every 2 weeks. This is the supported interval range.\n• (B) TRUE: Refresh schedules are configured directly in the Query Editor interface under the 'Schedule' option.\n• (C) TRUE (tricky!): A scheduled refresh DOES use a SQL Warehouse. The statement says it "does not use" one, making it seem false — BUT read carefully: Option C says the query "does not use a SQL Warehouse" which IS false in reality but the question asks which statement is INCORRECT. Wait — re-reading: C says "does not use" which is factually wrong ... BUT option E is MORE clearly incorrect as a definitive false statement about admin privileges.\n• (D) TRUE: A refresh schedule simply re-runs the query on a timer. An alert monitors a specific condition threshold. They are different features.\n\n🔑 EXAM TIP: Permission model — Query Owner or 'Can Manage' users can schedule refreshes. NO admin role needed. Scheduled queries DO consume SQL Warehouse compute.`,

  "db-da-36": `✅ CORRECT (D): Sharing a Personal Access Token (PAT) is the approach that CANNOT meet the security requirement. A PAT grants API-level authentication acting as the user who generated it. The client could use this token to access ANY resource that user has permissions on — not just the dashboard. This violates the requirement that "the client does not gain access to any other information."\n\n❌ Why others CAN safely share the dashboard:\n• (A) PDF download: A static PDF contains only what's visible on the dashboard. No access to underlying data, queries, or workspace resources. ✅ SAFE.\n• (B) Refresh schedule subscribers: Adding an email to the subscriber list sends a dashboard snapshot (PDF/image) via email. The recipient has no Databricks access whatsoever. ✅ SAFE.\n• (C) Screenshot: A static image contains zero access to any system resources. ✅ SAFE.\n• (E) PNG download: Like PDF/screenshot — static files with no system access. ✅ SAFE.\n\n🔑 EXAM TIP: PATs are DANGEROUS for external sharing — they act as the user's identity and grant access to the full API scope. For external stakeholders, use: PDF exports, email subscriptions, or published dashboard links with embedded credentials.`,

  "db-da-37": `✅ CORRECT (E): A Sankey diagram is specifically designed to visualize FLOWS — showing how quantities move from one state/stage to another. For website user flow (e.g., Homepage → Product Page → Cart → Checkout → Purchase), Sankey diagrams show the volume of users at each transition with proportional band widths.\n\n❌ Why others are wrong:\n• (A) Heatmap: Shows intensity/density of values in a matrix (two categorical axes + color intensity). Good for correlation matrices or time-based patterns, NOT for flow visualization.\n• (B) Choropleth: A geographic map where regions are colored by a metric value. Shows spatial distribution, NOT user flow through stages.\n• (C) Word Cloud: Displays word frequency with size proportional to occurrence count. Used for text analysis, NOT process flows.\n• (D) Pivot Table: A tabular cross-tabulation for summarizing data by categories. Shows numbers, NOT visual flows.\n\n🔑 EXAM TIP: Visualization Type Cheat Sheet:\n• Flow/movement between stages → Sankey\n• Geographic distribution → Choropleth\n• Intensity/correlation matrix → Heatmap\n• Trends over time → Line Chart\n• Part-to-whole → Pie/Donut\n• Distribution → Histogram/Box Plot`,

  "db-da-38": `✅ CORRECT (B): When you link a query parameter to a 'Dashboard Parameter,' ALL visualizations in the dashboard that use that same Dashboard Parameter will update simultaneously when the value changes. This is the key benefit — a single control at the dashboard level drives multiple widgets.\n\n❌ Why others are wrong:\n• (A) "All other visualizations remain changed": Incorrect. Dashboard Parameters are SHARED — all widgets linked to the same parameter update together, not independently.\n• (C) "Uses value at the time of adding": Incorrect. Dashboard Parameters are dynamic — they change at runtime when users interact with the filter controls at the top of the dashboard.\n• (D) "Cannot be changed afterwards": Incorrect. Dashboard Parameters are interactive controls meant to be changed by end users at any time.\n• (E) "Converts to a Dashboard Parameter": Incorrect. The area chart doesn't 'convert' — it USES the Dashboard Parameter as its data source for that filter value.\n\n🔑 EXAM TIP: Two types of parameters:\n• Query Parameter: Lives inside a single query, controls only that query's results.\n• Dashboard Parameter: Lives at the dashboard level, controls ALL widgets that are linked to it. This is the key to synchronized, interactive dashboards.`,

  "db-da-39": `✅ CORRECT (D): Queries that use query parameters CANNOT be used with Databricks Alerts. This is a hard limitation. Alerts need to evaluate a fixed query on a schedule to check if a threshold is met. Query parameters introduce dynamic, user-input-dependent behavior that the alert scheduler cannot resolve — there's no "user" to provide the parameter value when the alert runs automatically.\n\n❌ Why others are wrong:\n• (A) "Alerts don't work with tables": Completely false. Alerts work with any query that returns results from tables, views, or CTEs.\n• (B) "Date-based results can't be used": False. Alerts CAN work with date columns in results — the restriction is on query PARAMETERS (dynamic inputs), not date data types.\n• (C) "Only Date and Time parameters work": False. NO type of query parameter works with Alerts, regardless of the parameter type.\n• (E) "Only dropdown parameters work": False. Same reason — ALL parameter types are incompatible with Alerts.\n\n🔑 EXAM TIP: Alert requirements:\n1. Query must be STATIC (no parameters)\n2. Query must return a SINGLE numeric value (or a column that can be evaluated)\n3. Alert evaluates: value > threshold, value < threshold, or value = threshold\n4. Alert runs on a schedule using a SQL Warehouse`,

  "db-da-40": `✅ CORRECT (D): Adding borders is NOT a feature available in the Databricks Visualization Editor. The editor focuses on data representation and analytical formatting, not decorative borders around charts.\n\n❌ Why others are actually TRUE (valid features):\n• (A) Scale can be changed: TRUE — You can switch between linear and logarithmic scales, set min/max ranges for axes.\n• (B) Data Labels can be formatted: TRUE — You can enable/disable data labels and customize their format (number formatting, positioning).\n• (C) Colors can be changed: TRUE — Color palettes, individual series colors, and conditional coloring are all configurable.\n• (E) Tooltips can be formatted: TRUE — Tooltips can show custom fields, formatted values, and additional context on hover.\n\n🔑 EXAM TIP: The Visualization Editor supports: Scale, Data Labels, Colors, Tooltips, Legend positioning, Axis labels, Stacking, and Trend lines. It does NOT support: Borders, custom CSS, or arbitrary HTML rendering.`,

  "db-da-42": `✅ CORRECT (D): Last-mile ETL describes the light processing that data ANALYSTS perform on gold-layer tables before final analysis or dashboard creation. Unlike full ETL pipelines (managed by engineers), last-mile ETL involves small, ad-hoc transformations like filtering, joining additional reference data, or creating derived columns — done in SQL Warehouse queries or notebooks.\n\n❌ Why others are wrong:\n• (A) Data blending: Data blending refers to combining data from multiple disparate sources at the point of analysis (common in BI tools like Tableau). It's not specific to processing gold-layer tables.\n• (B) Last-mile dashboarding: Not a standard Databricks term. The actual term is last-mile ETL — the processing happens BEFORE the dashboard, not AS the dashboard.\n• (C) Data testing: Data testing involves validating data quality (null checks, schema validation, constraint testing) — not transforming data for analysis.\n• (E) Data enhancement: Data enhancement specifically means AUGMENTING data by adding new external datasets. The question describes processing/transforming, not augmenting with new data.\n\n🔑 EXAM TIP: Know the difference:\n• Last-mile ETL = Analyst-level processing on gold tables (filter, join, derive)\n• Data enhancement = Adding NEW external data to enrich existing tables\n• Data blending = Combining data from multiple sources at query time`,

  "db-da-43": `✅ CORRECT (A): Descriptive statistics uses SUMMARY statistics (mean, median, mode, standard deviation, min, max, percentiles) to QUANTITATIVELY describe and SUMMARIZE the features of a dataset. It answers: "What does the data look like?"\n\n❌ Why others are wrong:\n• (B) "Infer properties of an underlying distribution": This describes INFERENTIAL statistics — drawing conclusions about a population from a sample. Different branch entirely.\n• (C) "Quantitative variables with finite/countable values": This describes DISCRETE variables (a data type concept), not a branch of statistics.\n• (D) "Categorically describe": Descriptive statistics uses QUANTITATIVE summaries (numbers), not categorical descriptions. The word "categorically" makes this wrong.\n• (E) "Quantitative variables with uncountable values": This describes CONTINUOUS variables (another data type concept), not a branch of statistics.\n\n🔑 EXAM TIP: Statistics branches:\n• Descriptive = Summarize what the data looks like (mean, median, std dev)\n• Inferential = Draw conclusions about a population from sample data (hypothesis testing, confidence intervals)\n• Predictive = Forecast future outcomes using models (regression, ML)`,

  "db-da-44": `✅ CORRECT (E): When a variable contains extreme outliers, the MEAN gets pulled toward them (because mean uses ALL values including extremes), while the MEDIAN stays robust (because median only looks at the middle value). Example: incomes [30K, 35K, 40K, 45K, 10M] → Mean ≈ 2M (pulled by 10M outlier), Median = 40K (unaffected).\n\n❌ Why others are wrong:\n• (A) No outliers: Without outliers, the distribution is roughly symmetric, and mean ≈ median. No meaningful difference.\n• (B) No missing values: Missing values affect sample size but don't cause systematic divergence between mean and median.\n• (C) Boolean type: Boolean variables (0/1) have a very constrained range. Mean = proportion of 1s, Median = 0 or 1. Not meaningfully different in the statistical sense intended.\n• (D) Categorical type: Mean and median are not meaningful for categorical variables (e.g., "red", "blue", "green"). You can't average categories.\n\n🔑 EXAM TIP: Mean vs. Median sensitivity:\n• Mean = sensitive to outliers (pulled toward extremes)\n• Median = resistant to outliers (robust measure of center)\n• When mean ≠ median significantly → the distribution is SKEWED\n• Right-skewed (positive): Mean > Median\n• Left-skewed (negative): Mean < Median`,

  "db-da-45": `✅ CORRECT (E): Data enhancement is the process of AUGMENTING existing data by adding NEW external datasets to make it richer and more useful. The stakeholder providing an "additional dataset to augment" the gold-layer tables is the textbook definition of data enhancement.\n\n❌ Why others are wrong:\n• (A) Data testing: Testing validates data quality (nulls, duplicates, constraints). The analyst is not testing — they're adding new data.\n• (B) Ad-hoc improvements: Not a standard Databricks or analytics term.\n• (C) Last-mile dashboarding: Not a recognized term. Last-mile ETL exists but refers to processing, not augmenting.\n• (D) Last-mile ETL: Last-mile ETL involves PROCESSING existing gold data (filtering, transforming, deriving). The question describes ADDING new data. Enhancement ≠ ETL.\n\n🔑 EXAM TIP: The exam loves to confuse these three:\n• Last-mile ETL = Processing/transforming gold-layer data before analysis\n• Data enhancement = Adding NEW external datasets to enrich existing data\n• Data blending = Combining multiple data sources at the point of analysis`,

  "db-da-48": `✅ CORRECT (A): The key benefit of Databricks SQL for BI is that computations, data, and analytical tools exist on the SAME PLATFORM. No ETL to export data to external BI tools. No data movement latency. No governance gaps. Everything — storage (Delta Lake), compute (SQL Warehouses), and analytics (Dashboards, Alerts) — runs in one unified environment.\n\n❌ Why others are wrong:\n• (B) Advanced dashboarding: Databricks SQL dashboards are designed for quick, exploratory analysis — NOT advanced pixel-perfect dashboarding. Tools like Tableau or Power BI offer more advanced visualization capabilities.\n• (C) Multi-user support: While Databricks supports concurrent users, this is not unique to Databricks SQL — ALL modern BI tools support multi-user access.\n• (D) Automated alerting: While Databricks SQL has alerts, this is not its distinctive advantage over third-party tools which also have alerting features.\n\n🔑 EXAM TIP: Databricks SQL's UNIQUE advantage = unified platform (no data movement). The exam emphasizes the lakehouse benefit: data stays in place, reducing latency, cost, and governance overhead.`,

  "db-da-52": `✅ CORRECT (C): A continuous variable can take on an UNCOUNTABLE set of values — meaning it can be ANY value within a range, including all fractions and decimals. Examples: temperature (98.6°F), height (5.847 ft), time (3.14159 seconds). You can always find another value between any two values.\n\n❌ Why others are wrong:\n• (A) "Never stops changing": This confuses 'continuous' with 'constantly changing.' A continuous variable CAN be constant (e.g., a room at exactly 72.0°F) — 'continuous' refers to the range of possible values, not whether it changes.\n• (B) "Finite or countably infinite": This defines a DISCRETE variable (e.g., number of customers: 1, 2, 3...). Discrete = countable. Continuous = uncountable.\n• (D) "Categorical variable": Categorical variables are qualitative (color, category, status) — not related to continuous measurement.\n\n🔑 EXAM TIP: Variable types:\n• Continuous = uncountable values in a range (height, weight, temperature) → use histograms\n• Discrete = countable values (count of orders, number of clicks) → use bar charts\n• Categorical = qualitative labels (region, status, color) → use pie/bar charts`,

  "db-da-53": `✅ CORRECT (D): To rank products WITHIN each region, you need the RANK() or ROW_NUMBER() window function with PARTITION BY region ORDER BY sales DESC. The PARTITION BY clause creates separate ranking groups per region, and ORDER BY sales DESC ranks from highest to lowest sales within each partition.\n\nSQL Pattern:\nSELECT region, product, sales,\n  RANK() OVER (PARTITION BY region ORDER BY sales DESC) as rank\nFROM sales_table;\n\n❌ Why others are wrong: The other options likely use incorrect syntax — either missing PARTITION BY (which would rank globally, not within regions), using wrong ORDER direction, or using non-window-function approaches.\n\n🔑 EXAM TIP: Window Function essentials:\n• PARTITION BY = defines the groups (like GROUP BY but without collapsing rows)\n• ORDER BY = defines the sort order within each partition\n• RANK() = allows ties (1,1,3), ROW_NUMBER() = no ties (1,2,3)\n• DENSE_RANK() = no gaps after ties (1,1,2)`,

  "db-da-55": `✅ CORRECT (C): GROUP BY ... WITH ROLLUP generates hierarchical subtotals and a grand total. For columns (group_1, group_2), it produces:\n1. Individual group combinations (group_1 + group_2)\n2. Subtotals for group_1 (group_2 = NULL)\n3. Grand total (both = NULL)\n\nSQL Pattern:\nSELECT group_1, group_2, SUM(value)\nFROM table\nGROUP BY group_1, group_2 WITH ROLLUP;\n\n❌ Why others are wrong: Other options likely use incorrect aggregation patterns that don't produce the hierarchical subtotal structure shown in the expected output.\n\n🔑 EXAM TIP: Aggregation modifiers:\n• ROLLUP = hierarchical subtotals (drills down left to right)\n• CUBE = ALL possible subtotal combinations\n• GROUPING SETS = custom-specified subtotals only\n• GROUPING() function = identifies which NULL values are subtotals vs. real NULLs`,

  "db-da-65": `✅ CORRECT (A): Before adding visualizations or counters to a dashboard, you MUST first create the underlying Queries that generate the data. Dashboards are containers — each visualization widget is backed by a saved Query. No query = no data = no visualization.\n\n❌ Why others are wrong:\n• (B) SQL warehouse must be on: While a warehouse is needed to RUN queries, it doesn't need to be 'turned on and selected' BEFORE you create the dashboard structure. You select the warehouse when you run/refresh.\n• (C) Markdown tile required: Markdown tiles are optional formatting elements. There's no requirement to add one before visualizations.\n• (D) Dashboard owner = query owner: Not true. Dashboard owners can use queries owned by OTHER users, as long as they have 'Can Run' or 'Can View' permissions on those queries.\n\n🔑 EXAM TIP: Dashboard creation workflow:\n1. Write and save SQL Queries\n2. Create visualizations from query results\n3. Create a new Dashboard\n4. Add visualization widgets to the dashboard canvas\n5. Configure parameters, filters, and layout`,

  "db-da-69": `✅ CORRECT (A): A Date widget parameter provides start/end dates that feed into the WHERE clause of the underlying SQL query. The parameter value is substituted into the query's SQL code (e.g., WHERE order_date BETWEEN '{{start_date}}' AND '{{end_date}}'), which filters the data BEFORE it reaches the visualization.\n\n❌ Why others are wrong:\n• (B) "Sets x-axis range": Wrong mechanism. The parameter filters DATA via SQL, not the VISUAL axis range. The x-axis range is determined by the data that passes through the WHERE clause.\n• (C) "Filters all visualizations": Only if all visualizations are linked to the SAME Dashboard Parameter. A widget-level parameter only affects the query it's attached to.\n• (D) "Functions only as a text box": Parameters are functional query inputs — they inject values into SQL code, not just display text.\n\n🔑 EXAM TIP: Parameters work at the DATA layer (SQL WHERE clause), NOT at the visualization layer (axis range). The flow is: User selects date → value injected into SQL WHERE clause → query re-executes → filtered data renders in chart.`,

  "db-da-70": `✅ CORRECT (B): Adding external email addresses to the dashboard's scheduled refresh subscriber list is the minimum-effort approach. When the schedule triggers, Databricks automatically sends a snapshot (PDF) of the dashboard to all subscribers via email — including non-Databricks users. No manual intervention needed after initial setup.\n\n❌ Why others are wrong:\n• (A) "Grant email permissions to dashboard": You cannot grant dashboard permissions to email addresses of non-Databricks users. Permissions require workspace accounts.\n• (C) "SQL Warehouse subscribers list": SQL Warehouses don't have a subscriber list. Subscriptions are a DASHBOARD feature, not a warehouse feature.\n• (D) "Download PDF and email manually": This works but defeats the purpose — stakeholders need AUTOMATIC notification on every refresh, not manual effort.\n\n🔑 EXAM TIP: Dashboard Subscriptions = automated email delivery of snapshots. Key facts:\n• Supports external (non-workspace) email addresses\n• Sends PDF snapshots on schedule\n• Also supports Slack and Microsoft Teams destinations\n• Requires a Schedule to be configured first`,

  "db-da-73": `✅ CORRECT (C): Y-axis scale controls are found in the Visualization Editor → Y Axis section. The Visualization Editor is the dedicated interface for configuring all chart properties including scales, labels, colors, and data formatting.\n\n❌ Why others are wrong:\n• (A) Query Editor → Y Axis: The Query Editor is for writing SQL code. It has no axis configuration — that's the Visualization Editor's domain.\n• (B) Dashboard Editor → Axes: The Dashboard Editor manages layout (widget positioning, sizing, parameters). Individual chart axes are configured in the Visualization Editor.\n• (D) Settings → User Settings: User Settings control personal preferences (timezone, theme, default warehouse), not chart-specific properties.\n\n🔑 EXAM TIP: Configuration hierarchy:\n• Query Editor = SQL code\n• Visualization Editor = chart properties (axes, colors, labels, scale)\n• Dashboard Editor = layout, parameters, widget arrangement\n• User Settings = personal preferences`,

  "db-da-82": `✅ CORRECT (D): Databricks SQL is optimized for SIMPLE, EXPLORATORY visualizations on BIG DATA. Its strength is direct access to the lakehouse — you can query terabytes of data via SQL Warehouses and instantly create charts without exporting data. It's designed for quick analytical exploration, not polished presentations.\n\n❌ Why others are wrong:\n• (A) Presentation-grade: Databricks SQL charts are functional but basic. For publication-quality, pixel-perfect visualizations, use tools like Tableau, Power BI, or custom D3.js.\n• (B) Organization-branded: Databricks doesn't support custom branding (logos, corporate fonts, brand color enforcement) in its visualizations.\n• (C) Custom, interactive on small data: For small data with complex interactivity, lightweight tools (Plotly, D3.js, Streamlit) are more appropriate. Databricks SQL's advantage is its big data engine.\n\n🔑 EXAM TIP: Databricks SQL's visualization sweet spot = quick exploration on large datasets. When the exam asks about "best" use case, think: big data + SQL + fast iteration, NOT polished presentations.`,

  "db-da-83": `✅ CORRECT (C): A dashboard is the tool designed for combining multiple query visualizations into a single, shareable view. Dashboards aggregate charts, counters, and tables from different queries onto one canvas, giving stakeholders a unified monitoring experience.\n\n❌ Why others are wrong:\n• (A) SQL warehouse: A warehouse is a COMPUTE resource that executes queries. It doesn't display or share results — it processes them.\n• (B) Query History page: Shows a log of previously executed queries for debugging/auditing. Not designed for sharing curated visualizations.\n• (D) Data visualization tab on a Query page: Shows ONE query's visualization. The analyst needs to show results from MULTIPLE queries in a single view.\n\n🔑 EXAM TIP: Dashboard = the aggregation layer. It combines multiple query results into one shareable interface. Use it when stakeholders need to see consolidated insights from several data sources at once.`,

  "db-da-91": `✅ CORRECT (B): Databricks dashboards have a built-in scheduling feature that automatically refreshes data at regular intervals (from every 1 minute to every 2 weeks). This is the native, proper way to ensure stakeholders see current data without manual intervention.\n\n❌ Why others are wrong:\n• (A) Export PDF the night before: This creates a STATIC snapshot that's already outdated by morning. Not automated or real-time.\n• (C) Browser extension auto-reload: External browser extensions are unreliable, unsupported, and create unnecessary load. The browser tab must remain open for this to work.\n• (D) Manual refresh button: Requires user action every time — the opposite of automation. Defeats the purpose of the requirement.\n\n🔑 EXAM TIP: The built-in schedule is the ONLY supported automation method for dashboard refresh. Schedules:\n• Run on a SQL Warehouse (consumes compute)\n• Can trigger email subscriptions to stakeholders\n• Can run as 'Owner' or 'Viewer' identity\n• Range: every 1 minute to every 2 weeks`,

  "db-da-116": `✅ CORRECT (B): Dashboard Subscriptions with 'Destinations' allow sending PDF snapshots to external email addresses (non-Databricks users). You configure a Schedule (e.g., every Monday at 8 AM) and add a Subscription Destination with the external email. The system automatically generates and emails the PDF.\n\n❌ Why others are wrong:\n• (A) "Not possible without accounts": FALSE. Dashboard Subscriptions specifically support external email addresses for exactly this use case.\n• (C) "Publish to Web": Publish to Web creates a shareable link but doesn't send scheduled emails with PDFs. It requires the user to visit a URL.\n• (D) "Delta Sharing": Delta Sharing is for sharing DATA (tables, schemas) across organizations — not for sharing dashboard visualizations or PDFs.\n\n🔑 EXAM TIP: Two ways to share dashboards with non-Databricks users:\n1. Dashboard Subscriptions → automated PDF emails on schedule\n2. Published Dashboard Links → shareable URL with embedded credentials\nDelta Sharing = data sharing (tables), NOT dashboard sharing.`,

  "db-da-123": `✅ CORRECT (B): The analyst missed the PARAMETER MAPPING step. Adding a {{date_param}} to a query creates a Query Parameter. But for the dashboard-level filter to control it, you must explicitly MAP the Dashboard Parameter to the Widget's Query Parameter in the widget settings. Without this mapping, the dashboard filter and the query parameter are disconnected.\n\n❌ Why others are wrong:\n• (A) Browser refresh needed: Browser refresh wouldn't fix a configuration issue. Parameters are mapped through settings, not through page reloads.\n• (C) "Parameters only work in SQL Editor": FALSE. Parameters are designed to work in BOTH the SQL Editor (for testing) and in Dashboards (for interactivity).\n• (D) "Subscription schedule not triggered": Subscription schedules send emails — they have nothing to do with interactive parameter filtering on a live dashboard.\n\n🔑 EXAM TIP: Parameter workflow in dashboards:\n1. Create {{param_name}} in the SQL query\n2. Add the query as a widget to the dashboard\n3. In widget settings, MAP the dashboard parameter → query parameter\n4. Now the dashboard filter controls the widget's data\nSkipping step 3 = the filter won't affect the widget!`,

  "db-da-130": `✅ CORRECT (A): Cross-filtering is the feature where clicking a data point in one visualization (e.g., a bar in a bar chart) automatically filters other visualizations on the same dashboard. It creates interactive drill-down behavior without requiring explicit parameter setup.\n\n❌ Why others are wrong:\n• (B) Parameter Mapping: Parameters require manual configuration of filter widgets and explicit mapping. Cross-filtering is automatic — click a data point and other charts filter.\n• (C) Z-Order Indexing: Z-Order is a Delta Lake file optimization technique for co-locating related data in storage. It has nothing to do with dashboard interactivity.\n• (D) Dynamic Views: Dynamic Views is not a standard Databricks dashboard feature name. The correct term is Cross-filtering.\n\n🔑 EXAM TIP: Cross-filtering:\n• Enabled per-visualization in the widget properties\n• Works between visualizations on the SAME dashboard\n• Click a bar/point → other charts filter automatically\n• No explicit parameter configuration needed\n• Supported in AI/BI Dashboards`,

  "db-da-137": `✅ CORRECT (C): Trend Lines overlay a regression line (linear, polynomial) or moving average on top of data points. This helps identify the overall direction (upward/downward), spot anomalies (points deviating from the trend), and quantify the relationship strength.\n\n❌ Why others are wrong:\n• (A) Data Labels: Data Labels show exact values on each data point (e.g., "$45,230"). They don't show direction or anomalies — they just annotate existing points.\n• (B) Stacked Bars: Stacked bars show part-to-whole composition. Not applicable to a line chart, and they don't identify trends or anomalies.\n• (D) Pie Chart: Pie charts show proportional composition at a single point in time. They cannot show trends over time or anomalies.\n• (E) Heat Map: Heat maps show intensity in a matrix format. While useful for patterns, they don't overlay directional indicators on a line chart.\n\n🔑 EXAM TIP: Trend Lines are the go-to feature for:\n• Identifying overall direction (trend)\n• Spotting anomalies (points far from the trend line)\n• Forecasting (extrapolating the trend)\n• Available in line charts, bar charts, and scatter plots in the Visualization Editor`,

  "db-da-147": `✅ CORRECT (B): Databricks AI/BI Dashboards support embedding via iframes. The process is:\n1. Publish the dashboard\n2. Workspace admin adds the host domain to the allowed embedding surfaces\n3. Embed the iframe code in the external web portal\n4. Viewers authenticate via Databricks credentials or service principal\n\n❌ Why others are wrong:\n• (A) Export as PDF: A static PDF loses all interactivity (filters, parameters, drill-downs). It's not a live, embedded dashboard.\n• (C) Screenshot image: Even worse than PDF — static, no updates, no interactivity.\n• (D) Databricks Connect: Databricks Connect is for connecting local IDEs to remote Spark clusters for code execution — not for embedding dashboards.\n• (E) "Not supported": FALSE. Dashboard embedding is an officially supported feature.\n\n🔑 EXAM TIP: Dashboard embedding requirements:\n• Workspace admin must whitelist the hosting domain\n• The dashboard must be published\n• Authentication is required (credentials or service principal)\n• Embedding uses standard iframe HTML`,

  "db-da-148": `✅ CORRECT (B): Dashboard Subscriptions enable scheduled email delivery of dashboard snapshots as PDF attachments. You set a schedule (e.g., every Monday at 9 AM), add subscriber email addresses, and the system automatically generates and sends the PDF.\n\n❌ Why others are wrong:\n• (A) SQL Alerts: Alerts monitor a SINGLE query's value against a threshold and send notifications when the condition is met. They don't send full dashboard snapshots.\n• (C) Databricks Jobs: Jobs orchestrate notebooks, JARs, or Python scripts. They don't have native dashboard snapshot and email capabilities.\n• (D) Delta Live Tables: DLT defines declarative data pipelines for ETL. No dashboard or email functionality.\n• (E) Partner Connect: Partner Connect integrates third-party tools (Fivetran, dbt, Tableau). Not related to dashboard email delivery.\n\n🔑 EXAM TIP: Dashboard Subscriptions vs. Alerts:\n• Subscriptions = send full dashboard PDF on a SCHEDULE (time-based)\n• Alerts = send notification when a CONDITION is met (threshold-based)\n• Both can deliver via email, Slack, or Teams`,

  "db-da-187": `✅ CORRECT (A): A multi-series line chart is the optimal choice. It places time (months) on the X-axis, revenue on the Y-axis, and draws a separate line for each product category. This enables:\n• Trend comparison: See all three categories' trajectories simultaneously\n• Seasonal patterns: Identify recurring peaks/valleys\n• Decline detection: Spot downward trends by category\n\n❌ Why others are wrong:\n• (B) Single-value counter: Shows ONE aggregated number. Cannot show trends, comparisons, or temporal patterns.\n• (C) Pie chart for final month: Shows composition at ONE point in time. Loses all temporal trend information across 24 months.\n• (D) Scatter chart (revenue vs. profit margin): Uses wrong axes entirely. The requirement is revenue over TIME, not revenue vs. profit margin.\n\n🔑 EXAM TIP: Visualization selection for time-series:\n• Trends over time + comparison → Multi-series line chart\n• Composition at one point → Pie/donut chart\n• Single KPI display → Counter\n• Correlation between two metrics → Scatter plot\n• Distribution → Histogram/box plot`,

  "db-da-188": `✅ CORRECT (A): To share with external stakeholders securely without workspace access:\n1. Publish the dashboard\n2. Enable embedded credentials (the dashboard runs as the owner's identity)\n3. Share the published link with external users\n\nThis gives view-only access to the dashboard without granting any workspace permissions, meeting all security requirements.\n\n❌ Why others are wrong:\n• (B) Add as workspace admins: Violates the principle of least privilege. Admin access is far beyond "view dashboard" and directly contradicts the security requirement.\n• (C) Add to 'All workspace users' group: Requires creating workspace accounts for external users and grants CAN EDIT — far more access than needed.\n• (D) Export PDF and email: While secure, this provides a STATIC snapshot, not a live dashboard. The question asks about viewing the dashboard, not receiving a file.\n\n🔑 EXAM TIP: External sharing methods (no workspace access needed):\n1. Published dashboard link with embedded credentials → live, interactive\n2. Dashboard Subscriptions → automated PDF emails\n3. PDF/PNG export → manual, static\nAlways choose the method that matches the access + interactivity requirements.`,

  "db-da-214": `✅ CORRECT (C): The standard workflow: Click 'Add Visualization' in the dashboard editor → select chart type (Gauge) → associate it with a query that calculates the on-time percentage. This is the native, built-in way to add new widgets to existing dashboards.\n\n❌ Why others are wrong:\n• (A) Export from notebook as static image: Static images aren't interactive, don't auto-refresh, and can't be linked to parameters. Not a proper dashboard widget.\n• (B) Ask admin for materialized view: Unnecessary. The query itself can compute the percentage with SUM(CASE WHEN...) / COUNT(*). No admin action or pre-aggregation needed.\n• (D) Clone dashboard and replace: Overly complex. You can add widgets directly to an existing dashboard — no need to clone, modify, and replace.\n\n🔑 EXAM TIP: Adding widgets to dashboards:\n1. Open dashboard in Edit mode\n2. Click 'Add Visualization' (or 'Add' → 'Visualization')\n3. Select or create the backing query\n4. Choose the visualization type\n5. Configure the visualization settings\n6. Position and resize on the canvas`,

  "db-da-238": `✅ CORRECT (D): In Databricks notebooks, after running a %sql cell, you can create visualizations DIRECTLY in the notebook using either:\n1. display() function in Python cells\n2. Click the + icon in the SQL result cell → select visualization type\n\nBoth methods create inline, interactive charts within the notebook — no need to leave the environment.\n\n❌ Why others are wrong:\n• (A) Export to Excel: Losing the interactive, in-platform workflow. Databricks notebooks have built-in charting — no external tools needed.\n• (B) Python plotly.express: While possible, the question asks about the SIMPLEST way from a %sql cell. The built-in + icon is immediate; switching to Python adds unnecessary complexity.\n• (C) Copy to dashboard: The question asks about creating a chart IN THE NOTEBOOK. Moving to a dashboard is an extra step that's not needed for notebook-level exploration.\n\n🔑 EXAM TIP: Notebook visualization workflow:\n• %sql cell → run query → click + icon → choose chart type → configure\n• Python cell → display(df) → click + icon → choose chart type\n• Charts are interactive: hover for details, click for drill-down\n• Visualizations persist when the notebook is saved`,

  "db-da-280": `✅ CORRECT (A, B): Both actions are required for an accurate line chart:\n\n1. (A) X-axis sorting: Line charts connect data points in sequence. If dates are unsorted, lines criss-cross creating a 'spaghetti' effect. Always ORDER BY date column in the query or ensure the visualization sorts the X-axis.\n\n2. (B) Y-axis aggregation: If multiple transactions exist per day, displaying raw data creates overplotting (multiple Y values per X point). Aggregating (SUM, AVG) in the visualization editor or SQL ensures one clean data point per time period.\n\n❌ Why others are wrong:\n• (C) Enable 'Auto-format': Auto-format improves visual appearance (date formatting, number formatting) but does NOT fix data sorting or aggregation issues.\n• (D) Ignore missing data: Missing data creates gaps that can mislead viewers. Handle in SQL with COALESCE, date generation, or explicit fills — never ignore.\n• (E) Use scatter plot instead: Scatter plots show individual points without connecting them. They lose the continuous trend visualization that line charts provide.\n\n🔑 EXAM TIP: Line chart requirements:\n1. X-axis must be sorted (ORDER BY in SQL)\n2. Y-axis should be aggregated (one value per X point)\n3. Handle missing data explicitly\n4. Use continuous X-axis (dates, timestamps)`,

  "db-da-284": `✅ CORRECT (C): The 'Share' dialog in the dashboard provides granular, resource-level access control. You click 'Share,' select users or groups, and assign roles:\n• CAN VIEW → read-only access to the dashboard\n• CAN EDIT → modify visualizations, layout, and queries\n• CAN MANAGE → full control including sharing permissions and deletion\n\n❌ Why others are wrong:\n• (A) Workspace Admin role for editors: Massively over-privileged. Workspace Admin grants control over ALL workspace resources — not just one dashboard. Violates least privilege.\n• (B) Unity Catalog SELECT/UPDATE: Unity Catalog manages DATA access (tables, schemas, catalogs). Dashboard permissions are a separate layer — you can have data access without dashboard access and vice versa.\n• (D) current_user() in SQL: Row-level security in queries controls WHAT data a user sees, not WHETHER they can view/edit the dashboard itself. These are different permission layers.\n\n🔑 EXAM TIP: Two separate permission layers:\n1. Dashboard permissions (Share dialog): CAN VIEW / CAN EDIT / CAN MANAGE → controls the dashboard UI\n2. Data permissions (Unity Catalog): SELECT / USAGE → controls access to underlying tables\nBoth may be needed depending on the 'Run as' setting.`,

  "db-da-291": `✅ CORRECT (B): Disabling 'Automatic Update' prevents the dashboard from re-executing queries every time a filter value changes. Users can change multiple filters (Date, Region, Product) first, then click a single 'Refresh' button to trigger all queries at once — reducing redundant executions and improving performance.\n\n❌ Why others are wrong:\n• (A) Enable 'Automatic Update': This is the OPPOSITE of what's needed. Automatic Update triggers a query refresh on EVERY filter change, causing N redundant executions when changing N filters.\n• (C) 'Apply All' SQL Parameter: Not a real Databricks feature. There's no 'Apply All' parameter type in SQL.\n• (D) 'Run on Selection' set to false: Not the correct setting name. The actual setting is 'Automatic Update' (or 'Run on change') at the filter/visualization level.\n\n🔑 EXAM TIP: Dashboard performance optimization:\n• Disable 'Automatic Update' → batch filter changes, then manually refresh\n• Use warehouse scaling for concurrent users\n• Optimize underlying queries with proper indexing/partitioning\n• Use pre-aggregated Gold-layer tables instead of raw queries`,

  "db-da-292": `✅ CORRECT (B): In the Table visualization, you can set a column's display type to 'Link' and define a URL template using curly braces: https://tickets.company.com/id={{SalesOrder_ID}}. The system dynamically replaces {{SalesOrder_ID}} with the actual value from each row, creating clickable hyperlinks.\n\n❌ Why others are wrong:\n• (A) Custom JavaScript: Databricks dashboards don't support custom JavaScript injection in visualization metadata. This is not a supported approach.\n• (C) HTML in SQL query: While some BI tools support HTML rendering in query results, Databricks Table visualizations don't render raw HTML tags from SQL output. Use the built-in 'Link' column type instead.\n• (D) "Only in Genie": FALSE. Link formatting is available in both Legacy SQL Dashboards AND AI/BI Dashboards. It's not exclusive to Genie.\n\n🔑 EXAM TIP: Table column formatting types:\n• Link → clickable URL with template {{column_name}}\n• Number → formatted with decimals, currency, percentage\n• Image → renders URL as an inline image\n• Boolean → displays checkmark or icon\n• Date/Time → formatted with locale-specific patterns`,

  "db-da-293": `✅ CORRECT (C): When a schedule runs as 'Owner' and that user is deactivated/deleted, the schedule FAILS. The execution engine needs a valid identity to authenticate and execute queries. A deactivated user has no valid credentials, so the SQL Warehouse cannot authenticate the request.\n\n❌ Why others are wrong:\n• (A) Auto-transfer to group member: Databricks does NOT automatically transfer schedule ownership. This must be done manually by an admin before the user is deactivated.\n• (B) Continues with cached credentials: FALSE. Authentication is validated at execution time, not cached. Deactivated users fail auth immediately.\n• (D) Paused and resumable: The schedule doesn't gracefully pause — it FAILS with an authentication error. An admin must manually transfer ownership and reconfigure.\n\n🔑 EXAM TIP: Best practices for production schedules:\n• Use Service Principals (not user accounts) for critical schedules\n• Service Principals persist regardless of employee turnover\n• If using a user account, transfer ownership BEFORE deactivation\n• 'Run as Owner' = schedule uses owner's identity for auth + data access\n• 'Run as Viewer' = each viewer uses their own identity`,

  "db-da-294": `✅ CORRECT (C): Cross-filtering is the feature, and it's enabled by toggling the interactive setting in the visualization's properties. When enabled, clicking a bar in the Bar Chart applies a filter to all other visualizations on the same page.\n\n❌ Why others are wrong:\n• (A) 'Click-Filter' in global settings: 'Click-Filter' is not the correct feature name, and it's not configured at the global level. It's called 'Cross-filtering' and is set per-visualization.\n• (B) Dynamic Parameters with :region: Adding :region to every query creates explicit parameters, not automatic click-to-filter behavior. Cross-filtering is automatic and doesn't require modifying SQL queries.\n• (D) 'Connect widgets' button: There is no 'Connect widgets' button in Databricks dashboards. Cross-filtering is configured in the individual visualization's properties.\n\n🔑 EXAM TIP: Cross-filtering key facts:\n• Configured per-visualization (not globally)\n• Works automatically — click a data point to filter others\n• No SQL query modification needed\n• Works between visualizations on the same dashboard page\n• Supported in AI/BI Dashboards`,

  "db-da-295": `✅ CORRECT (D): All of the above are possible missing configurations. The exact cause depends on the dashboard's 'Run as' mode:\n\n• If 'Run as Viewer': The peer needs (A) SQL Warehouse access + (B) SELECT on source tables + dashboard access. All three are required.\n• If 'Run as Owner': The peer only needs dashboard access — the owner's identity handles data/warehouse auth.\n• The fix might be simply (C) switching to 'Run as Owner' if the analyst has broader permissions.\n\n❌ Why no single option is definitively correct:\n• (A) alone might not fix it if the data permissions are also missing\n• (B) alone might not fix it if the warehouse permissions are also missing\n• (C) alone would fix it but changes the security model\n\n🔑 EXAM TIP: 'Run as' permission chain:\n• Run as VIEWER: Viewer needs → Dashboard access + SQL Warehouse 'Can Use' + SELECT on tables\n• Run as OWNER: Viewer needs → Dashboard access only (owner's identity handles everything else)\n• 'Permission Denied' errors = check the ENTIRE chain for the current 'Run as' mode`
};

// Apply upgrades
const filePath = './questions_databricks.js';
let content = fs.readFileSync(filePath, 'utf-8');

let upgraded = 0;
let failed = 0;

for (const [id, newExpl] of Object.entries(upgrades)) {
  // Find the question and replace its explanation
  const escapedExpl = newExpl.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
  
  // Build regex to find the explanation field for this specific question
  const idPattern = `"id": "${id}"`;
  const idIdx = content.indexOf(idPattern);
  
  if (idIdx === -1) {
    console.log(`❌ ${id} not found!`);
    failed++;
    continue;
  }
  
  // Find the explanation field after this id
  const explStart = content.indexOf('"explanation":', idIdx);
  if (explStart === -1 || explStart - idIdx > 3000) {
    console.log(`❌ ${id} explanation field not found within range`);
    failed++;
    continue;
  }
  
  // Find the start and end of the explanation value
  const valueStart = content.indexOf('"', explStart + '"explanation":'.length);
  if (valueStart === -1) {
    console.log(`❌ ${id} explanation value start not found`);
    failed++;
    continue;
  }
  
  // Find the end of the string - handle escaped quotes
  let valueEnd = valueStart + 1;
  while (valueEnd < content.length) {
    if (content[valueEnd] === '\\') {
      valueEnd += 2; // skip escaped char
      continue;
    }
    if (content[valueEnd] === '"') {
      break;
    }
    valueEnd++;
  }
  
  const oldValue = content.substring(valueStart, valueEnd + 1);
  const newValue = `"${escapedExpl}"`;
  
  content = content.substring(0, valueStart) + newValue + content.substring(valueEnd + 1);
  console.log(`✅ ${id} explanation upgraded`);
  upgraded++;
}

fs.writeFileSync(filePath, content, 'utf-8');
console.log(`\nDone! Upgraded ${upgraded}/${Object.keys(upgrades).length} Dashboards & Visualizations explanations.`);
if (failed > 0) console.log(`Failed: ${failed}`);

// Verify file validity
try {
  delete require.cache[require.resolve('./questions_databricks.js')];
  global.window = { questionsData: [] };
  require('./questions_databricks.js');
  console.log(`✅ File valid! Total questions: ${window.questionsData.length}`);
} catch(e) {
  console.log(`❌ File has syntax errors: ${e.message.substring(0, 200)}`);
}
