/* Author (GPT-5) | 2026-09-20 CST | Literal transcription of supplied images. */
window.questionsEn=[
["An organization has many agents and many tools. Without a standard, each agent-to-tool integration is one-off custom code, which becomes unmanageable as both grow.\n\nWhat does the Model Context Protocol (MCP) standardize, and what analogy does the course use?",["It is a model that replaces the need for tools","It is a standard interface each tool exposes so any agent that speaks the protocol can connect directly, like a USB port","It routes traffic between models; it is like a load balancer","It is a database that stores all agent memory"],1],
["An engineer is deciding what information to place in front of the model on each turn of an agent, and a reviewer calls this the biggest lever on agent quality.\n\nWhich discipline is being described?",["Hyperparameter tuning of the model weights","Prompt engineering, meaning writing one clever prompt once","Data labeling for supervised training","Context engineering: deciding what goes into the composed input the model sees each turn"],3],
["A team is setting up evaluation for a multi-step agent and tries to reuse the single-response scoring they used for a plain model. A reviewer says agent evaluation is different.\n\nWhy must agent evaluation judge the trajectory, not just the final answer?",["Because an agent produces a sequence of tool calls and intermediate results, evaluation must check which tools were called, in what order, and whether the final answer is grounded in them","It does not; scoring the final answer is sufficient for agents","Because agents never produce a final answer","Because trajectories are cheaper to store than answers"],0],
["An architect is describing how AI maturity progresses in an organization, from personal productivity gains up to work being redesigned around what agents can do.\n\nWhat does the course say higher stages of the maturity ladder depend on?",["Removing all human oversight","Governed data and identity, not just a better model","Buying more GPUs","Only a more capable model"],1],
["A team is separating two governance questions for a production agent: who is allowed to reach a tool, versus what content is permitted to pass.\n\nWhich pairing is correct?",["Both are handled only by the model's system prompt","Access policies decide what content is allowed; guardrails decide who can connect","Neither is configurable on Databricks","Access policies (Unity Catalog grants) decide who can reach a service; guardrails (service policies at the gateway) decide what content is allowed, with allow, require-approval, or deny outcomes"],3],
["A business user wants to ask questions in plain language over governed tables and have the system write and run the SQL, with answers respecting Unity Catalog permissions.\n\nWhich Genie surface fits this user?",["Genie One, which answers business users in natural language over governed tables","A fine-tuned open-weight model","Genie Agents, which data teams curate as trusted domains","Genie Code, a coding and data agent in notebooks"],0],
["A team lists the parts of their agent: something that reasons and sequences actions, something that lets it act and return trustworthy results, something that carries state across steps, and something it can choose to call for knowledge.\n\nWhich mapping to building blocks is correct?",["All four are the same component with different names","Tools reason and sequence; the model brain only stores state","Model brain = memory; tools = retrieval; memory = brain; RAG = tools","Model brain reasons and sequences; tools and structured outputs let it act; memory carries state; agentic RAG is retrieval it chooses to call"],3],
["A CIO's team can prototype an agent quickly but keeps stalling before production. The course names three specific challenges that stop agentic apps from shipping.\n\nWhich set correctly names those three enterprise challenges?",["Choice of programming language, cloud region, and logo design","Only the price of the frontier model","Model size, GPU cost, and UI polish","Complexity across AI and infrastructure, missing business context, and gaps in enterprise access and governance"],3],
["A developer has two systems. One follows the same coded steps every run over data it owns. The other reasons about a request, decides which tools to call, and changes its path based on what it observes.\n\nWhat property makes the second system agentic?",["It runs on faster hardware","Agency: it decides what to do at runtime instead of following a path a developer wrote in advance","It uses a larger language model than the first","It stores more data than the first system"],1],
["A request spans several specialties at once: it needs structured sales data, an answer from internal documents, and a call to an external service. A single agent handles it poorly.\n\nWhich coordination pattern does the course prescribe, and how does it relate to the harness idea?",["A single monolithic prompt that lists all steps","Manual handoff between human operators","Round-robin calls to the same model with no routing","A Supervisor Agent that routes each part to a specialist and synthesizes the results; it is the harness idea one level up, with whole agents as its tools"],3],
["A team is explaining why an agent can complete a multi-step task that a single model call cannot.\n\nWhich description of the reason-act loop is correct?",["The agent asks the user to approve every token","The agent makes one model call and returns whatever it produces","The agent reasons, acts by calling a tool or retrieving information, observes the result, and reasons again, repeating until the task is done","The agent calls all tools at once and merges the outputs without reasoning"],2],
["A team wants automatic, scalable scoring of their agent's behavior on Databricks, both before deployment and continuously in production, without hand-reading every trace.\n\nWhich capabilities support this?",["A spreadsheet of prompts and expected answers checked by hand","Statistical feature-drift monitoring designed for predictive ML","Only manual review by domain experts","MLflow Tracing captures each run as spans, and scorers (built-in or custom LLM-as-judge) score those traces via mlflow.genai.evaluate(), gating promotion and running on sampled production traffic"],3],
["A newcomer places three things on a spectrum: a plain model, a model with retrieval, and an agent, and asks how they relate.\n\nWhich progression matches the course's framing?",["All three are identical; the names are marketing","A plain model answers from what it learned, RAG grounds the answer in your data, and an agent reasons and acts to complete a task, each doing more than the last","RAG replaces the model entirely","An agent is simpler than a plain model"],1],
["During a design review, an engineer claims that once you pick a powerful enough model, the model itself is essentially the whole agent.\n\nWhy is that framing incomplete, per the course?",["The model is only the brain; a harness around it runs the loop, calls tools, manages context, and decides when to stop","The agent is only the tools, and the model is optional","The harness replaces the need for a model","The model is the whole agent; the claim is correct"],0],
["In the course's platform stack, a team needs the layer that gives tables, files, models, and agents one consistent permission model.\n\nWhich component provides that unified governance?",["A single foundation model endpoint","The AI Playground","The notebook editor","Unity Catalog, one permission model across data and AI assets"],3],
["Leadership is skeptical that agentic systems work outside demos. The course closes Module 1 by pointing to production deployments with measured outcomes.\n\nWhich statement best reflects how the course frames 'agents in production today'?",["Production agents require abandoning governance to move fast","Organizations are running agentic apps in production at scale with measured outcomes, on the same governed platform the course teaches","No organization runs agents in production yet; it is all theoretical","Agents only work for consumer chatbots, never enterprise workflows"],1],
["A production agent runs as a service principal with broad access. A security architect worries the agent could reach data a given user should not see.\n\nWhich mechanism ensures the agent cannot exceed the querying user's own permissions?",["On-behalf-of authorization passes the user's identity with the request, so Unity Catalog checks that user's grants","Cache the first user's permissions and reuse them for everyone","Disable Unity Catalog for the agent to simplify access","Give the service principal admin rights so it never errors"],0],
["A platform team compares three application types: a dashboard with little AI, a support copilot where AI is central, and a digital coworker that takes actions on its own. Each has a different hardest problem.\n\nWhich pairing of app flavor to its main source of difficulty is correct?",["Data apps: infrastructure (network, SSO, RBAC); AI apps: governing data at query time; agentic apps: tools, guardrails, state, and audit logging","Data apps: guardrails and audit; agentic apps: infrastructure plumbing","All three share the identical hardest problem: model accuracy","AI apps: nothing hard; agentic apps: only cost"],0],
["In a Supervisor-based app, the team currently sends every step, including simple classification and routing, to a top-tier frontier reasoning model. Cost is high.\n\nWhat does multi-model orchestration recommend?",["Right-size the model per step: small fast models for high-volume routing, mid-tier for retrieval and synthesis, frontier only for hard planning and judgment","Use the cheapest possible model for every step regardless of quality","Randomly assign models to steps to balance load","Always use the single best model for every step for consistency"],0],
["In the hands-on demo, a Sales Prospecting assistant takes one plain-language request and must answer from governed sales tables, answer from internal positioning documents, and reach an external firmographic source, without hand-written orchestration code.\n\nWhich assembly of Databricks components matches the demo's governed architecture?",["Three separate human teams answering each part","A spreadsheet macro calling a public chatbot","A single fine-tuned model doing everything, with no Unity Catalog","An Agent Bricks Supervisor Agent routing to a Genie Agent (governed tables), a Knowledge Assistant (documents), and an MCP tool (external data), with Unity Catalog governing every tool"],3]
];
